/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o nimcache/nimFinLib_nimFinT5.o nimcache/nimFinLib_nimFinT5.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>

#include <stdlib.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TY120008 TY120008;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct TY272097 TY272097;
typedef struct Df259013 Df259013;
typedef struct Nf259011 Nf259011;
typedef struct TY259026 TY259026;
typedef struct TY259038 TY259038;
typedef struct Pf259009 Pf259009;
typedef struct TY259018 TY259018;
typedef struct Runningstat144047 Runningstat144047;
typedef struct Table329036 Table329036;
typedef struct Keyvaluepairseq329039 Keyvaluepairseq329039;
typedef struct TY100570 TY100570;
typedef struct Ts259015 Ts259015;
typedef struct Format188215 Format188215;
typedef struct Mersennetwister197035 Mersennetwister197035;
typedef struct Cf259017 Cf259017;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
typedef struct Keyvaluepair329042 Keyvaluepair329042;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
struct  Nf259011  {
TNimType* m_type;
NimStringDesc* nx;
TY272097* dx;
};
struct  Df259013  {
  Nf259011 Sup;
NimStringDesc* stock;
TY120008* date;
TY259026* open;
TY259026* high;
TY259026* low;
TY259026* close;
TY259026* vol;
TY259026* adjc;
TY259038* rc;
TY259038* rca;
};
struct  Pf259009  {
TY259018* pf;
};
struct  Table329036  {
Keyvaluepairseq329039* data;
NI counter;
};
struct TY100570 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef TY100570 TY329015[6];
struct  Ts259015  {
TNimType* m_type;
TY120008* dd;
TY259026* tx;
};
struct Format188215 {
NU8 Field0;
NI Field1;
NI Field2;
NimStringDesc* Field3;
NU8 Field4;
NU8 Field5;
NIM_BOOL Field6;
NIM_BOOL Field7;
NIM_BOOL Field8;
NimStringDesc* Field9;
};
typedef NimStringDesc* TY347897[11];
typedef NU32 TY197036[624];
struct  Mersennetwister197035  {
TY197036 mt;
NI mti;
};
struct  Cf259017  {
TNimType* m_type;
TY120008* cu;
TY259026* ra;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Runningstat144047  {
NI n;
NF sum;
NF min;
NF max;
NF mean;
NF oldm;
NF olds;
NF news;
};
struct Keyvaluepair329042 {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
struct TY120008 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY272097 {
  TGenericSeq Sup;
  Df259013 data[SEQ_DECL_SIZE];
};
struct TY259018 {
  TGenericSeq Sup;
  Nf259011 data[SEQ_DECL_SIZE];
};
struct TY259026 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct TY259038 {
  TGenericSeq Sup;
  Runningstat144047 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq329039 {
  TGenericSeq Sup;
  Keyvaluepair329042 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(void, setforegroundcolor_138057)(NU8 fg, NIM_BOOL bright);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_79604, TNimType* mt);
N_NIMCALL(TY120008*, deduplicate_328127)(TY120008* seq1);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(TY272097*, initpool_272095)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_50622)(Cell44747* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48267)(Cell44747* c);
static N_INLINE(void, rtladdcycleroot_49023)(Cell44747* c);
N_NOINLINE(void, incl_45465)(Cellset44759* s, Cell44747* cell);
static N_INLINE(void, decref_50204)(Cell44747* c);
N_NIMCALL(void, getsymbol2_289133)(NimStringDesc* symb, NimStringDesc* startdate, NimStringDesc* enddate, Df259013* Result);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, initpf_271800)(Pf259009* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, initnf_271827)(Nf259011* Result);
N_NIMCALL(void, initdf_271854)(Df259013* Result);
N_NIMCALL(NF, last_328495)(TY259026* self);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(NF, standarddeviation_144106)(Runningstat144047* s);
N_NIMCALL(void, last_328609)(TY272097* self, Df259013* Result);
N_NIMCALL(void, last_328591)(TY259018* self, Nf259011* Result);
N_NIMCALL(void, decho_272601)(NI z);
N_NIMCALL(void, showhistdata_301458)(Df259013* adf, NimStringDesc* s, NimStringDesc* e);
N_NIMCALL(void, showdailyreturnscl_307941)(Df259013* self, NI N);
N_NIMCALL(void, showdailyreturnsadcl_313258)(Df259013* self, NI N);
N_NIMCALL(TY259026*, dailyreturns_307946)(TY259026* self);
N_NIMCALL(TY259026*, tail_328750)(TY259026* self, NI n);
N_NIMCALL(NimStringDesc*, HEX24_147921)(NI rune);
N_NIMCALL(NF, sumdailyreturnscl_319258)(Df259013* self);
N_NIMCALL(NF, sumdailyreturnsadcl_319349)(Df259013* self);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, totable_329026)(TY100570* pairs, NI pairsLen0, Table329036* Result);
N_NIMCALL(void, timeseries_329481)(Df259013* self, NimStringDesc* ty, Ts259015* Result);
N_NIMCALL(void, showtimeseries_259101)(Ts259015* ats, NimStringDesc* header, NimStringDesc* ty, NI N);
N_NIMCALL(NimStringDesc*, HEX5BHEX5D_329504)(Table329036 t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, first_329571)(TY120008* self);
N_NIMCALL(NF, first_329589)(TY259026* self);
static N_INLINE(void, addformat_259404)(NimStringDesc** o, NimStringDesc* x, Format188215* fmt);
N_NIMCALL(void, writeformat_261004)(NimStringDesc** o, NimStringDesc* s, Format188215* fmt);
static N_INLINE(void, addformat_188850)(NimStringDesc** s, NimStringDesc* x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(void, addformat_264004)(NimStringDesc** o, NF x, Format188215* fmt);
N_NIMCALL(void, writeformat_265604)(NimStringDesc** o, NF x, Format188215* fmt_265614);
N_NIMCALL(TY120008*, head_331624)(TY120008* self, NI n);
N_NIMCALL(TY259026*, head_331890)(TY259026* self, NI n);
static N_INLINE(void, addformat_333204)(NimStringDesc** o, TY120008* x, Format188215* fmt);
N_NIMCALL(void, writeformat_334805)(NimStringDesc** o, NimStringDesc** ary, NI aryLen0, Format188215* fmt);
static N_INLINE(void, addformat_338804)(NimStringDesc** o, TY259026* x, Format188215* fmt);
N_NIMCALL(void, writeformat_340405)(NimStringDesc** o, NF* ary, NI aryLen0, Format188215* fmt);
N_NIMCALL(NimStringDesc*, last_343663)(TY120008* self);
N_NIMCALL(TY120008*, tail_331748)(TY120008* self, NI n);
N_NIMCALL(void, ema_319433)(Df259013* dx, NI N, Ts259015* Result);
N_NIMCALL(void, showema_319609)(Ts259015* emx, NI N);
N_NIMCALL(void, statistics_319388)(Runningstat144047* x);
N_NIMCALL(NimStringDesc*, min_347741)(NimStringDesc** x, NI xLen0);
N_NIMCALL(NimStringDesc*, max_347785)(NimStringDesc** x, NI xLen0);
N_NIMCALL(NF, intervalyears_289113)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NF, intervalmonths_289091)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NF, intervalweeks_289072)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NF, intervaldays_289055)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NF, intervalhours_289040)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NF, intervalmins_289026)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NF, intervalsecs_289011)(NimStringDesc* startdate, NimStringDesc* enddate);
N_NIMCALL(NimStringDesc*, year_288875)(NimStringDesc* adate);
N_NIMCALL(NimStringDesc*, month_288864)(NimStringDesc* adate);
N_NIMCALL(NimStringDesc*, day_288843)(NimStringDesc* adate);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, validdate_288885)(NimStringDesc* adate);
static N_INLINE(NF, random_203535)(void);
static N_INLINE(NF, random_199023)(Mersennetwister197035* self);
N_NIMCALL(NF, genrandres53_197780)(Mersennetwister197035* s);
N_NIMCALL(NF, logisticf_327041)(NF z);
N_NIMCALL(NF, logisticfderivative_327058)(NF z);
N_NIMCALL(void, showcurrentstocks_288823)(NimStringDesc* stcks);
N_NIMCALL(void, showcurrentstocks_288802)(Nf259011* apf);
N_NIMCALL(void, showcurrentindexes_288760)(NimStringDesc* idxs);
N_NIMCALL(void, showcurrentindexes_288780)(TY272097* adf);
N_NIMCALL(void, showcurrentforex_322965)(TY120008* curs);
N_NIMCALL(void, getcurrentforex_322831)(TY120008* curs, Cf259017* Result);
N_NOCONV(void, resetattributes_137209)(void);
N_NIMCALL(void, Gcfullcollect_8805)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_fenvInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_fenvDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pegsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pegsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_utilInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_utilDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_random_realInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_random_realDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_commonInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_commonDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mt19937arInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mt19937arDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mersenneInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_mersenneDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_urandomInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_urandomDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_randomInit)(void);
NIM_EXTERNC N_NOINLINE(void, random_randomDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimfinlib_nimFinLibInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimfinlib_nimFinLibDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimFinT5Init)(void);
NIM_EXTERNC N_NOINLINE(void, nimFinT5DatInit)(void);
STRING_LITERAL(TMP145, "###############################################", 47);
STRING_LITERAL(TMP146, "# Testing nimFinLib                           #", 47);
STRING_LITERAL(TMP148, "0386.HK", 7);
STRING_LITERAL(TMP149, "0880.HK", 7);
STRING_LITERAL(TMP150, "0555.HK", 7);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[3];
} CNSTSEQ152 = {{3, 3}, {((NimStringDesc*) &TMP148),
((NimStringDesc*) &TMP149),
((NimStringDesc*) &TMP150)}};
NIM_CONST TY120008* TMP147 = ((TY120008*)&CNSTSEQ152);
STRING_LITERAL(TMP154, "0005.HK", 7);
STRING_LITERAL(TMP155, "3311.HK", 7);
STRING_LITERAL(TMP156, "3688.HK", 7);
STRING_LITERAL(TMP157, "2727.HK", 7);
STRING_LITERAL(TMP158, "3337.HK", 7);
STRING_LITERAL(TMP159, "3968.HK", 7);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[8];
} CNSTSEQ161 = {{8, 8}, {((NimStringDesc*) &TMP148),
((NimStringDesc*) &TMP154),
((NimStringDesc*) &TMP149),
((NimStringDesc*) &TMP155),
((NimStringDesc*) &TMP156),
((NimStringDesc*) &TMP157),
((NimStringDesc*) &TMP158),
((NimStringDesc*) &TMP159)}};
NIM_CONST TY120008* TMP153 = ((TY120008*)&CNSTSEQ161);
STRING_LITERAL(TMP162, "1766.HK", 7);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[4];
} CNSTSEQ164 = {{4, 4}, {((NimStringDesc*) &TMP162),
((NimStringDesc*) &TMP148),
((NimStringDesc*) &TMP149),
((NimStringDesc*) &TMP150)}};
NIM_CONST TY120008* TMP161 = ((TY120008*)&CNSTSEQ164);
STRING_LITERAL(TMP165, "SNP", 3);
STRING_LITERAL(TMP166, "SBUX", 4);
STRING_LITERAL(TMP167, "IBM", 3);
STRING_LITERAL(TMP168, "BP.L", 4);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[4];
} CNSTSEQ170 = {{4, 4}, {((NimStringDesc*) &TMP165),
((NimStringDesc*) &TMP166),
((NimStringDesc*) &TMP167),
((NimStringDesc*) &TMP168)}};
NIM_CONST TY120008* TMP164 = ((TY120008*)&CNSTSEQ170);
STRING_LITERAL(TMP171, "AFK", 3);
STRING_LITERAL(TMP172, "ASHR", 4);
STRING_LITERAL(TMP173, "ECH", 3);
STRING_LITERAL(TMP174, "EGPT", 4);
STRING_LITERAL(TMP175, "EIDO", 4);
STRING_LITERAL(TMP176, "EIRL", 4);
STRING_LITERAL(TMP177, "EIS", 3);
STRING_LITERAL(TMP178, "ENZL", 4);
STRING_LITERAL(TMP179, "EPHE", 4);
STRING_LITERAL(TMP180, "EPI", 3);
STRING_LITERAL(TMP181, "EPOL", 4);
STRING_LITERAL(TMP182, "EPU", 3);
STRING_LITERAL(TMP183, "EWA", 3);
STRING_LITERAL(TMP184, "EWC", 3);
STRING_LITERAL(TMP185, "EWD", 3);
STRING_LITERAL(TMP186, "EWG", 3);
STRING_LITERAL(TMP187, "EWH", 3);
STRING_LITERAL(TMP188, "EWI", 3);
STRING_LITERAL(TMP189, "EWJ", 3);
STRING_LITERAL(TMP190, "EWK", 3);
STRING_LITERAL(TMP191, "EWL", 3);
STRING_LITERAL(TMP192, "EWM", 3);
STRING_LITERAL(TMP193, "EWN", 3);
STRING_LITERAL(TMP194, "EWO", 3);
STRING_LITERAL(TMP195, "EWP", 3);
STRING_LITERAL(TMP196, "EWQ", 3);
STRING_LITERAL(TMP197, "EWS", 3);
STRING_LITERAL(TMP198, "EWT", 3);
STRING_LITERAL(TMP199, "EWU", 3);
STRING_LITERAL(TMP200, "EWW", 3);
STRING_LITERAL(TMP201, "EWY", 3);
STRING_LITERAL(TMP202, "EWZ", 3);
STRING_LITERAL(TMP203, "EZA", 3);
STRING_LITERAL(TMP204, "FM", 2);
STRING_LITERAL(TMP205, "FRN", 3);
STRING_LITERAL(TMP206, "FXI", 3);
STRING_LITERAL(TMP207, "GAF", 3);
STRING_LITERAL(TMP208, "GULF", 4);
STRING_LITERAL(TMP209, "GREK", 4);
STRING_LITERAL(TMP210, "GXG", 3);
STRING_LITERAL(TMP211, "IDX", 3);
STRING_LITERAL(TMP212, "MCHI", 4);
STRING_LITERAL(TMP213, "MES", 3);
STRING_LITERAL(TMP214, "NORW", 4);
STRING_LITERAL(TMP215, "QQQ", 3);
STRING_LITERAL(TMP216, "RSX", 3);
STRING_LITERAL(TMP217, "THD", 3);
STRING_LITERAL(TMP218, "TUR", 3);
STRING_LITERAL(TMP219, "VNM", 3);
STRING_LITERAL(TMP220, "TLT", 3);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[50];
} CNSTSEQ222 = {{50, 50}, {((NimStringDesc*) &TMP171),
((NimStringDesc*) &TMP172),
((NimStringDesc*) &TMP173),
((NimStringDesc*) &TMP174),
((NimStringDesc*) &TMP175),
((NimStringDesc*) &TMP176),
((NimStringDesc*) &TMP177),
((NimStringDesc*) &TMP178),
((NimStringDesc*) &TMP179),
((NimStringDesc*) &TMP180),
((NimStringDesc*) &TMP181),
((NimStringDesc*) &TMP182),
((NimStringDesc*) &TMP183),
((NimStringDesc*) &TMP184),
((NimStringDesc*) &TMP185),
((NimStringDesc*) &TMP186),
((NimStringDesc*) &TMP187),
((NimStringDesc*) &TMP188),
((NimStringDesc*) &TMP189),
((NimStringDesc*) &TMP190),
((NimStringDesc*) &TMP191),
((NimStringDesc*) &TMP192),
((NimStringDesc*) &TMP193),
((NimStringDesc*) &TMP194),
((NimStringDesc*) &TMP195),
((NimStringDesc*) &TMP196),
((NimStringDesc*) &TMP197),
((NimStringDesc*) &TMP198),
((NimStringDesc*) &TMP199),
((NimStringDesc*) &TMP200),
((NimStringDesc*) &TMP201),
((NimStringDesc*) &TMP202),
((NimStringDesc*) &TMP203),
((NimStringDesc*) &TMP204),
((NimStringDesc*) &TMP205),
((NimStringDesc*) &TMP206),
((NimStringDesc*) &TMP207),
((NimStringDesc*) &TMP208),
((NimStringDesc*) &TMP209),
((NimStringDesc*) &TMP210),
((NimStringDesc*) &TMP211),
((NimStringDesc*) &TMP212),
((NimStringDesc*) &TMP213),
((NimStringDesc*) &TMP214),
((NimStringDesc*) &TMP215),
((NimStringDesc*) &TMP216),
((NimStringDesc*) &TMP217),
((NimStringDesc*) &TMP218),
((NimStringDesc*) &TMP219),
((NimStringDesc*) &TMP220)}};
NIM_CONST TY120008* TMP170 = ((TY120008*)&CNSTSEQ222);
STRING_LITERAL(TMP223, "SPY", 3);
STRING_LITERAL(TMP224, "^HSI", 4);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[2];
} CNSTSEQ226 = {{2, 2}, {((NimStringDesc*) &TMP223),
((NimStringDesc*) &TMP224)}};
NIM_CONST TY120008* TMP222 = ((TY120008*)&CNSTSEQ226);
STRING_LITERAL(TMP226, "2014-01-01", 10);
STRING_LITERAL(TMP397, "TestPortfolio", 13);
STRING_LITERAL(TMP398, "# Tests for Pf , Nf ,Df types                 #", 47);
STRING_LITERAL(TMP399, "Name    : ", 10);
STRING_LITERAL(TMP400, "Open    : ", 10);
STRING_LITERAL(TMP404, "High    : ", 10);
STRING_LITERAL(TMP405, "Low     : ", 10);
STRING_LITERAL(TMP406, "Close   : ", 10);
STRING_LITERAL(TMP407, "Volume  : ", 10);
STRING_LITERAL(TMP408, "AdjClose: ", 10);
STRING_LITERAL(TMP409, "StDevCl : ", 10);
STRING_LITERAL(TMP410, "StDevClA: ", 10);
STRING_LITERAL(TMP411, "Using shortcut to display most recent open value", 48);
STRING_LITERAL(TMP412, "Show hist. stock data between 2 dates incl. if available", 56);
STRING_LITERAL(TMP463, "2015-04-12", 10);
STRING_LITERAL(TMP464, "2015-05-10", 10);
STRING_LITERAL(TMP465, "# Tests for dailyReturns                      #", 47);
STRING_LITERAL(TMP466, "Most recent 5 dailyreturns based on close price", 47);
STRING_LITERAL(TMP477, "Most recent 5 dailyreturns based on adjc price", 46);
STRING_LITERAL(TMP487, "Show tail 2 rows = most recent dailyreturns based on adjc", 57);
STRING_LITERAL(TMP488, "  ", 2);
STRING_LITERAL(TMP489, "DailyReturns sum based on Close Price     : ", 44);
STRING_LITERAL(TMP490, " ", 1);
STRING_LITERAL(TMP492, "DailyReturns sum based on AdjClose Price  : ", 44);
STRING_LITERAL(TMP493, "# Tests for timeseries                        #", 47);
STRING_LITERAL(TMP494, "\012Test timeseries - show recent 5 rows for $1\012", 45);
STRING_LITERAL(TMP499, "o", 1);
STRING_LITERAL(TMP500, "Open", 4);
STRING_LITERAL(TMP501, "h", 1);
STRING_LITERAL(TMP502, "High", 4);
STRING_LITERAL(TMP503, "l", 1);
STRING_LITERAL(TMP504, "Low", 3);
STRING_LITERAL(TMP505, "c", 1);
STRING_LITERAL(TMP506, "Close", 5);
STRING_LITERAL(TMP507, "v", 1);
STRING_LITERAL(TMP508, "Volume", 6);
STRING_LITERAL(TMP509, "a", 1);
STRING_LITERAL(TMP510, "Adj.Close", 9);
NIM_CONST TY329015 TMP498 = {{((NimStringDesc*) &TMP499),
((NimStringDesc*) &TMP500)}
,
{((NimStringDesc*) &TMP501),
((NimStringDesc*) &TMP502)}
,
{((NimStringDesc*) &TMP503),
((NimStringDesc*) &TMP504)}
,
{((NimStringDesc*) &TMP505),
((NimStringDesc*) &TMP506)}
,
{((NimStringDesc*) &TMP507),
((NimStringDesc*) &TMP508)}
,
{((NimStringDesc*) &TMP509),
((NimStringDesc*) &TMP510)}
}
;
STRING_LITERAL(TMP518, "Head", 4);
STRING_LITERAL(TMP532, "head", 4);
STRING_LITERAL(TMP533, "Tail", 4);
STRING_LITERAL(TMP534, "tail", 4);
STRING_LITERAL(TMP535, "Timeseries display test ", 24);
STRING_LITERAL(TMP536, "first   ", 8);
NIM_CONST Format188215 TMP537 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP538 = {((NU8) 0),
((NI) -1),
((NI) 10),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP539 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP540, "head(1) ", 8);
NIM_CONST Format188215 TMP541 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP544 = {((NU8) 0),
((NI) -1),
((NI) 10),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP545 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP546, "last    ", 8);
NIM_CONST Format188215 TMP547 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP548 = {((NU8) 0),
((NI) -1),
((NI) 10),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP549 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP550, "tail(1) ", 8);
NIM_CONST Format188215 TMP551 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP552 = {((NU8) 0),
((NI) -1),
((NI) 10),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP553 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP554, "# Tests for ema (exponential moving average)  #", 47);
STRING_LITERAL(TMP556, "EMA for : ", 10);
STRING_LITERAL(TMP562, "# Tests for statistics on Df type             #", 47);
STRING_LITERAL(TMP563, "Stats for : ", 12);
STRING_LITERAL(TMP564, " based on close price", 21);
STRING_LITERAL(TMP571, "# Tests for date and logistic helper procs    #", 47);
STRING_LITERAL(TMP572, "\012Interval Information\012", 22);
STRING_LITERAL(TMP573, "  -  ", 5);
STRING_LITERAL(TMP574, "Years      : ", 13);
STRING_LITERAL(TMP642, "Months     : ", 13);
STRING_LITERAL(TMP643, "Weeks      : ", 13);
STRING_LITERAL(TMP644, "Days       : ", 13);
STRING_LITERAL(TMP645, "Hours      : ", 13);
STRING_LITERAL(TMP646, "Mins       : ", 13);
STRING_LITERAL(TMP647, "Secs       : ", 13);
STRING_LITERAL(TMP648, "Extract items from date string ", 31);
STRING_LITERAL(TMP649, "Test validDate proc", 19);
STRING_LITERAL(TMP650, "2015-02-29", 10);
STRING_LITERAL(TMP651, "3000-15-10", 10);
STRING_LITERAL(TMP652, "1899-12-31", 10);
STRING_LITERAL(TMP653, "2018-12-31", 10);
STRING_LITERAL(TMP654, "2016-02-29", 10);
STRING_LITERAL(TMP655, "2017-02-29", 10);
STRING_LITERAL(TMP656, "2018-02-29", 10);
STRING_LITERAL(TMP657, "2019-02-29", 10);
STRING_LITERAL(TMP658, "2019-01-02", 10);
STRING_LITERAL(TMP659, "true", 4);
NIM_CONST Format188215 TMP660 = {((NU8) 0),
((NI) -1),
((NI) 11),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP661 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP662, "false", 5);
NIM_CONST Format188215 TMP663 = {((NU8) 0),
((NI) -1),
((NI) 11),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP664 = {((NU8) 0),
((NI) -1),
((NI) -1),
NIM_NIL,
((NU8) 0),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP665, "Testing logistics functions", 27);
STRING_LITERAL(TMP666, "Value", 5);
STRING_LITERAL(TMP667, "logisticf", 9);
STRING_LITERAL(TMP668, "logistic_derivative", 19);
NIM_CONST Format188215 TMP669 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP670 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP671 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP672 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP673 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format188215 TMP674 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP675, "############################################", 44);
STRING_LITERAL(TMP676, "# Tests for Current Stocks and Indexes     #", 44);
STRING_LITERAL(TMP702, "AAPL+IBM+BP.L", 13);
STRING_LITERAL(TMP717, "# Tests for Forex rates                       #", 47);
STRING_LITERAL(TMP718, "Yahoo Exchange Rates", 20);
STRING_LITERAL(TMP720, "EURUSD", 6);
STRING_LITERAL(TMP721, "GBPUSD", 6);
STRING_LITERAL(TMP722, "GBPHKD", 6);
STRING_LITERAL(TMP723, "JPYUSD", 6);
STRING_LITERAL(TMP724, "AUDUSD", 6);
STRING_LITERAL(TMP725, "EURHKD", 6);
STRING_LITERAL(TMP726, "JPYHKD", 6);
STRING_LITERAL(TMP727, "CNYHKD", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[8];
} CNSTSEQ729 = {{8, 8}, {((NimStringDesc*) &TMP720),
((NimStringDesc*) &TMP721),
((NimStringDesc*) &TMP722),
((NimStringDesc*) &TMP723),
((NimStringDesc*) &TMP724),
((NimStringDesc*) &TMP725),
((NimStringDesc*) &TMP726),
((NimStringDesc*) &TMP727)}};
NIM_CONST TY120008* TMP719 = ((TY120008*)&CNSTSEQ729);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[2];
} CNSTSEQ747 = {{2, 2}, {((NimStringDesc*) &TMP720),
((NimStringDesc*) &TMP725)}};
NIM_CONST TY120008* TMP745 = ((TY120008*)&CNSTSEQ747);
STRING_LITERAL(TMP747, "Current EURUSD Rate : ", 22);
NIM_CONST Format188215 TMP748 = {((NU8) 0),
((NI) -1),
((NI) 8),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP749, "Current EURHKD Rate : ", 22);
NIM_CONST Format188215 TMP750 = {((NU8) 0),
((NI) -1),
((NI) 8),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP751, "Elapsed           : ", 20);
STRING_LITERAL(TMP752, " secs\012", 6);
STRING_LITERAL(TMP753, "nimlibFin Version : ", 20);
NF start_328004;
TY120008* symbols1_328050;
extern TNimType NTI120008; /* seq[string] */
TY120008* symbols2_328067;
TY120008* symbols3_328084;
TY120008* symbols4_328101;
TY120008* symbols5_328118;
TY120008* symbols_328122;
extern Gcheap46616 gch_46648;
TY120008* indexes_328216;
NimStringDesc* startdate_328232;
NimStringDesc* enddate_328233;
TY272097* stockpool_328237;
TY272097* indexpool_328241;
NimStringDesc* symbx_328254;
extern TNimType NTI259013; /* Df */
NimStringDesc* symbx_328299;
Pf259009 account_328335;
extern TNimType NTI259009; /* Pf */
Nf259011 portfolio_328339;
extern TNimType NTI259011; /* Nf */
Df259013 stockdata_328343;
Df259013 stockdata_328411;
Df259013 data_328626;
TY259026* rets_328745;
NI x_328916;
Table329036 htable_329472;
extern TNimType NTI329036; /* Table */
NimStringDesc* ohlcva_329476;
Ts259015 ts_329494;
extern TNimType NTI259015; /* Ts */
NimStringDesc* ret_329606;
NimStringDesc* arg0_329607;
NimStringDesc* arg1_329608;
NF arg2_329609;
NimStringDesc* ret_332076;
NimStringDesc* arg0_332077;
TY120008* arg1_332078;
TY259026* arg2_332079;
NimStringDesc* ret_343688;
NimStringDesc* arg0_343689;
NimStringDesc* arg1_343690;
NF arg2_343691;
NimStringDesc* ret_345645;
NimStringDesc* arg0_345646;
TY120008* arg1_345647;
TY259026* arg2_345648;
NI ndays_347650;
Ts259015 ema22_347654;
NimStringDesc* s_347779;
NimStringDesc* e_347823;
TY120008* somedates_347910;
NimStringDesc* sd_347923;
NI a_350248;
NimStringDesc* ret_350254;
NimStringDesc* arg0_350255;
NimStringDesc* arg1_350256;
NimStringDesc* arg2_350257;
NI x_352231;
extern Mersennetwister197035 mersennetwisterinst_201010;
NimStringDesc* idx_354273;
TY120008* checkcurrencies_354338;
Cf259017 curs_354358;
extern TNimType NTI259017; /* Cf */
NimStringDesc* ret_354381;
NF arg0_354382;
NimStringDesc* ret_354831;
NF arg0_354832;
extern NimStringDesc* Version_259004;

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell44747* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_48246(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell44747* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_48246((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_49804(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

static N_INLINE(NIM_BOOL, canbecycleroot_48267)(Cell44747* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(void, rtladdcycleroot_49023)(Cell44747* c) {
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		incl_45465((&gch_46648.cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, incref_50622)(Cell44747* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_48267(c);
		if (!LOC3) goto LA4;
		rtladdcycleroot_49023(c);
	}
	LA4: ;
}

static N_INLINE(void, decref_50204)(Cell44747* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_48267(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_49023(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		Cell44747* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_48246(src);
		incref_50622(LOC5);
	}
	LA3: ;
	{
		Cell44747* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_48246((*dest));
		decref_50204(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

static N_INLINE(void, addformat_259404)(NimStringDesc** o, NimStringDesc* x, Format188215* fmt) {
	writeformat_261004(o, x, fmt);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, addformat_188850)(NimStringDesc** s, NimStringDesc* x) {
	(*s) = resizeString((*s), x->Sup.len + 0);
appendString((*s), x);
}

static N_INLINE(void, addformat_264004)(NimStringDesc** o, NF x, Format188215* fmt) {
	writeformat_265604(o, x, fmt);
}

static N_INLINE(void, addformat_333204)(NimStringDesc** o, TY120008* x, Format188215* fmt) {
	writeformat_334805(o, x->data, x->Sup.len, fmt);
}

static N_INLINE(void, addformat_338804)(NimStringDesc** o, TY259026* x, Format188215* fmt) {
	writeformat_340405(o, x->data, x->Sup.len, fmt);
}

static N_INLINE(NF, random_199023)(Mersennetwister197035* self) {
	NF result;
	result = 0;
	result = genrandres53_197780(self);
	return result;
}

static N_INLINE(NF, random_203535)(void) {
	NF result;
	result = 0;
	result = random_199023((&mersennetwisterinst_201010));
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_timesDatInit();
	stdlib_posixDatInit();
	stdlib_osDatInit();
	stdlib_macrosDatInit();
	stdlib_termiosDatInit();
	stdlib_unsignedDatInit();
	stdlib_terminalDatInit();
	stdlib_sequtilsDatInit();
	stdlib_mathDatInit();
	stdlib_unicodeDatInit();
	stdlib_etcprivDatInit();
	stdlib_hashesDatInit();
	stdlib_tablesDatInit();
	stdlib_fenvDatInit();
	stdlib_pegsDatInit();
	stdlib_streamsDatInit();
	HEX00_strfmtDatInit();
	stdlib_intsetsDatInit();
	random_utilDatInit();
	random_random_realDatInit();
	random_commonDatInit();
	random_mt19937arDatInit();
	random_mersenneDatInit();
	random_urandomDatInit();
	random_randomDatInit();
	stdlib_rawsocketsDatInit();
	stdlib_opensslDatInit();
	stdlib_netDatInit();
	stdlib_uriDatInit();
	stdlib_strtabsDatInit();
	stdlib_base64DatInit();
	stdlib_mimetypesDatInit();
	stdlib_endiansDatInit();
	stdlib_oidsDatInit();
	stdlib_epollDatInit();
	stdlib_selectorsDatInit();
	stdlib_asyncdispatchDatInit();
	stdlib_asyncnetDatInit();
	stdlib_httpclientDatInit();
	stdlib_lexbaseDatInit();
	stdlib_parsecsvDatInit();
	stdlib_algorithmDatInit();
	nimfinlib_nimFinLibDatInit();
	nimFinT5DatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_timesInit();
	stdlib_posixInit();
	stdlib_osInit();
	stdlib_macrosInit();
	stdlib_termiosInit();
	stdlib_unsignedInit();
	stdlib_terminalInit();
	stdlib_sequtilsInit();
	stdlib_mathInit();
	stdlib_unicodeInit();
	stdlib_etcprivInit();
	stdlib_hashesInit();
	stdlib_tablesInit();
	stdlib_fenvInit();
	stdlib_pegsInit();
	stdlib_streamsInit();
	HEX00_strfmtInit();
	stdlib_intsetsInit();
	random_utilInit();
	random_random_realInit();
	random_commonInit();
	random_mt19937arInit();
	random_mersenneInit();
	random_urandomInit();
	random_randomInit();
	stdlib_rawsocketsInit();
	stdlib_opensslInit();
	stdlib_netInit();
	stdlib_uriInit();
	stdlib_strtabsInit();
	stdlib_base64Init();
	stdlib_mimetypesInit();
	stdlib_endiansInit();
	stdlib_oidsInit();
	stdlib_epollInit();
	stdlib_selectorsInit();
	stdlib_asyncdispatchInit();
	stdlib_asyncnetInit();
	stdlib_httpclientInit();
	stdlib_lexbaseInit();
	stdlib_parsecsvInit();
	stdlib_algorithmInit();
	nimfinlib_nimFinLibInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nimFinT5Init();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, nimFinT5Init)(void) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC12;
	NF LOC16;
	NimStringDesc* LOC17;
	NF LOC18;
	NimStringDesc* LOC19;
	NF LOC20;
	NimStringDesc* LOC21;
	NF LOC22;
	NimStringDesc* LOC23;
	NF LOC24;
	NimStringDesc* LOC25;
	NF LOC26;
	NimStringDesc* LOC27;
	NF LOC28;
	NimStringDesc* LOC29;
	NF LOC30;
	NimStringDesc* LOC31;
	Nf259011 LOC32;
	NF LOC33;
	NimStringDesc* LOC34;
	NimStringDesc* LOC40;
	NF LOC41;
	NimStringDesc* LOC42;
	NimStringDesc* LOC43;
	NF LOC44;
	NimStringDesc* LOC45;
	NimStringDesc* LOC46;
	NimStringDesc* LOC47;
	NimStringDesc* LOC48;
	NimStringDesc* LOC49;
	NimStringDesc* LOC50;
	NimStringDesc* LOC51;
	NimStringDesc* LOC52;
	NimStringDesc* LOC53;
	NF LOC54;
	NimStringDesc* LOC55;
	NF LOC56;
	NimStringDesc* LOC57;
	NF LOC58;
	NimStringDesc* LOC59;
	NF LOC60;
	NimStringDesc* LOC61;
	NF LOC62;
	NimStringDesc* LOC63;
	NF LOC64;
	NimStringDesc* LOC65;
	NF LOC66;
	NimStringDesc* LOC67;
	NimStringDesc* LOC68;
	NimStringDesc* LOC69;
	NimStringDesc* LOC70;
	TY347897 LOC71;
	NimStringDesc* LOC72;
	NimStringDesc* LOC73;
	NimStringDesc* LOC74;
	NimStringDesc* LOC75;
	NimStringDesc* LOC76;
	NimStringDesc* LOC77;
	NimStringDesc* LOC78;
	NimStringDesc* LOC79;
	NimStringDesc* LOC80;
	NimStringDesc* LOC81;
	NimStringDesc* LOC82;
	NimStringDesc* LOC93;
	NimStringDesc* LOC94;
	NimStringDesc* LOC95;
	NimStringDesc* LOC100;
	NF LOC101;
	NimStringDesc* LOC102;
	portfolio_328339.m_type = (&NTI259011);
	stockdata_328343.Sup.m_type = (&NTI259013);
	stockdata_328411.Sup.m_type = (&NTI259013);
	data_328626.Sup.m_type = (&NTI259013);
	ts_329494.m_type = (&NTI259015);
	ema22_347654.m_type = (&NTI259015);
	curs_354358.m_type = (&NTI259017);
	start_328004 = ntepochTime();
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP146)? (((NimStringDesc*) &TMP146))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	genericSeqAssign((&symbols1_328050), TMP147, (&NTI120008));
	genericSeqAssign((&symbols2_328067), TMP153, (&NTI120008));
	genericSeqAssign((&symbols3_328084), TMP161, (&NTI120008));
	genericSeqAssign((&symbols4_328101), TMP164, (&NTI120008));
	genericSeqAssign((&symbols5_328118), TMP170, (&NTI120008));
	genericSeqAssign((&symbols_328122), symbols1_328050, (&NTI120008));
	asgnRefNoCycle((void**) (&symbols_328122), deduplicate_328127(symbols_328122));
	genericSeqAssign((&indexes_328216), TMP222, (&NTI120008));
	asgnRefNoCycle((void**) (&indexes_328216), deduplicate_328127(indexes_328216));
	LOC1 = 0;
	LOC1 = startdate_328232; startdate_328232 = copyStringRC1(((NimStringDesc*) &TMP226));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	asgnRefNoCycle((void**) (&enddate_328233), ntgetDateStr());
	asgnRef((void**) (&stockpool_328237), initpool_272095());
	asgnRef((void**) (&indexpool_328241), initpool_272095());
	{
		NI i_328268;
		NI L_328270;
		i_328268 = ((NI) 0);
		L_328270 = (symbols_328122 ? symbols_328122->Sup.len : 0);
		{
			while (1) {
				NimStringDesc* LOC5;
				Df259013 LOC6;
				if (!(i_328268 < L_328270)) goto LA4;
				LOC5 = 0;
				LOC5 = symbx_328254; symbx_328254 = copyStringRC1(symbols_328122->data[i_328268]);
				if (LOC5) nimGCunrefNoCycle(LOC5);
				memset((void*)(&LOC6), 0, sizeof(LOC6));
				LOC6.Sup.m_type = (&NTI259013);
				getsymbol2_289133(symbx_328254, startdate_328232, enddate_328233, (&LOC6));
				stockpool_328237 = (TY272097*) incrSeq(&(stockpool_328237)->Sup, sizeof(Df259013));
				genericAssign((void*)(&stockpool_328237->data[stockpool_328237->Sup.len-1]), (void*)(&LOC6), (&NTI259013));
				i_328268 += ((NI) 1);
			} LA4: ;
		}
	}
	printf("\012");
	{
		NI i_328313;
		NI L_328315;
		i_328313 = ((NI) 0);
		L_328315 = (indexes_328216 ? indexes_328216->Sup.len : 0);
		{
			while (1) {
				NimStringDesc* LOC10;
				Df259013 LOC11;
				if (!(i_328313 < L_328315)) goto LA9;
				LOC10 = 0;
				LOC10 = symbx_328299; symbx_328299 = copyStringRC1(indexes_328216->data[i_328313]);
				if (LOC10) nimGCunrefNoCycle(LOC10);
				memset((void*)(&LOC11), 0, sizeof(LOC11));
				LOC11.Sup.m_type = (&NTI259013);
				getsymbol2_289133(symbx_328299, startdate_328232, enddate_328233, (&LOC11));
				indexpool_328241 = (TY272097*) incrSeq(&(indexpool_328241)->Sup, sizeof(Df259013));
				genericAssign((void*)(&indexpool_328241->data[indexpool_328241->Sup.len-1]), (void*)(&LOC11), (&NTI259013));
				i_328313 += ((NI) 1);
			} LA9: ;
		}
	}
	printf("\012");
	chckNil((void*)(&account_328335));
	genericReset((void*)(&account_328335), (&NTI259009));
	initpf_271800((&account_328335));
	chckNil((void*)(&portfolio_328339));
	genericReset((void*)(&portfolio_328339), (&NTI259011));
	portfolio_328339.m_type = (&NTI259011);
	initnf_271827((&portfolio_328339));
	chckNil((void*)(&stockdata_328343));
	genericReset((void*)(&stockdata_328343), (&NTI259013));
	stockdata_328343.Sup.m_type = (&NTI259013);
	initdf_271854((&stockdata_328343));
	LOC12 = 0;
	LOC12 = portfolio_328339.nx; portfolio_328339.nx = copyStringRC1(((NimStringDesc*) &TMP397));
	if (LOC12) nimGCunrefNoCycle(LOC12);
	{
		NI i_328425;
		NI L_328427;
		i_328425 = ((NI) 0);
		L_328427 = (stockpool_328237 ? stockpool_328237->Sup.len : 0);
		{
			while (1) {
				if (!(i_328425 < L_328427)) goto LA15;
				genericAssign((void*)(&stockdata_328411), (void*)(&stockpool_328237->data[i_328425]), (&NTI259013));
				portfolio_328339.dx = (TY272097*) incrSeq(&(portfolio_328339.dx)->Sup, sizeof(Df259013));
				genericAssign((void*)(&portfolio_328339.dx->data[portfolio_328339.dx->Sup.len-1]), (void*)(&stockdata_328411), (&NTI259013));
				i_328425 += ((NI) 1);
			} LA15: ;
		}
	}
	account_328335.pf = (TY259018*) incrSeq(&(account_328335.pf)->Sup, sizeof(Nf259011));
	genericAssign((void*)(&account_328335.pf->data[account_328335.pf->Sup.len-1]), (void*)(&portfolio_328339), (&NTI259011));
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP398)? (((NimStringDesc*) &TMP398))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	printf("%s\012", account_328335.pf->data[((NI) 0)].nx? (account_328335.pf->data[((NI) 0)].nx)->data:"nil");
	printf("%s%s\012", ((NimStringDesc*) &TMP399)? (((NimStringDesc*) &TMP399))->data:"nil", account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].stock? (account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].stock)->data:"nil");
	LOC16 = 0;
	LOC16 = last_328495(account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].open);
	LOC17 = 0;
	LOC17 = nimFloatToStr(LOC16);
	printf("%s%s\012", ((NimStringDesc*) &TMP400)? (((NimStringDesc*) &TMP400))->data:"nil", LOC17? (LOC17)->data:"nil");
	LOC18 = 0;
	LOC18 = last_328495(account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].high);
	LOC19 = 0;
	LOC19 = nimFloatToStr(LOC18);
	printf("%s%s\012", ((NimStringDesc*) &TMP404)? (((NimStringDesc*) &TMP404))->data:"nil", LOC19? (LOC19)->data:"nil");
	LOC20 = 0;
	LOC20 = last_328495(account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].low);
	LOC21 = 0;
	LOC21 = nimFloatToStr(LOC20);
	printf("%s%s\012", ((NimStringDesc*) &TMP405)? (((NimStringDesc*) &TMP405))->data:"nil", LOC21? (LOC21)->data:"nil");
	LOC22 = 0;
	LOC22 = last_328495(account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].close);
	LOC23 = 0;
	LOC23 = nimFloatToStr(LOC22);
	printf("%s%s\012", ((NimStringDesc*) &TMP406)? (((NimStringDesc*) &TMP406))->data:"nil", LOC23? (LOC23)->data:"nil");
	LOC24 = 0;
	LOC24 = last_328495(account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].vol);
	LOC25 = 0;
	LOC25 = nimFloatToStr(LOC24);
	printf("%s%s\012", ((NimStringDesc*) &TMP407)? (((NimStringDesc*) &TMP407))->data:"nil", LOC25? (LOC25)->data:"nil");
	LOC26 = 0;
	LOC26 = last_328495(account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].adjc);
	LOC27 = 0;
	LOC27 = nimFloatToStr(LOC26);
	printf("%s%s\012", ((NimStringDesc*) &TMP408)? (((NimStringDesc*) &TMP408))->data:"nil", LOC27? (LOC27)->data:"nil");
	LOC28 = 0;
	LOC28 = standarddeviation_144106((&account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].rc->data[((NI) 0)]));
	LOC29 = 0;
	LOC29 = nimFloatToStr(LOC28);
	printf("%s%s\012", ((NimStringDesc*) &TMP409)? (((NimStringDesc*) &TMP409))->data:"nil", LOC29? (LOC29)->data:"nil");
	LOC30 = 0;
	LOC30 = standarddeviation_144106((&account_328335.pf->data[((NI) 0)].dx->data[((NI) 0)].rca->data[((NI) 0)]));
	LOC31 = 0;
	LOC31 = nimFloatToStr(LOC30);
	printf("%s%s\012", ((NimStringDesc*) &TMP410)? (((NimStringDesc*) &TMP410))->data:"nil", LOC31? (LOC31)->data:"nil");
	memset((void*)(&LOC32), 0, sizeof(LOC32));
	LOC32.m_type = (&NTI259011);
	last_328591(account_328335.pf, (&LOC32));
	chckNil((void*)(&data_328626));
	genericReset((void*)(&data_328626), (&NTI259013));
	data_328626.Sup.m_type = (&NTI259013);
	last_328609(LOC32.dx, (&data_328626));
	printf("\012");
	printf("%s\012", ((NimStringDesc*) &TMP411)? (((NimStringDesc*) &TMP411))->data:"nil");
	LOC33 = 0;
	LOC33 = last_328495(data_328626.open);
	LOC34 = 0;
	LOC34 = nimFloatToStr(LOC33);
	printf("%s\012", LOC34? (LOC34)->data:"nil");
	decho_272601(((NI) 2));
	printf("%s\012", ((NimStringDesc*) &TMP412)? (((NimStringDesc*) &TMP412))->data:"nil");
	showhistdata_301458((&data_328626), ((NimStringDesc*) &TMP463), ((NimStringDesc*) &TMP464));
	printf("\012");
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP465)? (((NimStringDesc*) &TMP465))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP466)? (((NimStringDesc*) &TMP466))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	showdailyreturnscl_307941((&data_328626), ((NI) 5));
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP477)? (((NimStringDesc*) &TMP477))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	showdailyreturnsadcl_313258((&data_328626), ((NI) 5));
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP487)? (((NimStringDesc*) &TMP487))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	asgnRefNoCycle((void**) (&rets_328745), dailyreturns_307946(data_328626.adjc));
	{
		NI HEX3Atmp_328920;
		TY259026* LOC36;
		NI res_328923;
		HEX3Atmp_328920 = 0;
		LOC36 = 0;
		LOC36 = tail_328750(rets_328745, ((NI) 2));
		HEX3Atmp_328920 = ((LOC36 ? LOC36->Sup.len : 0) - 1);
		res_328923 = ((NI) 0);
		{
			while (1) {
				NimStringDesc* LOC39;
				if (!(res_328923 <= HEX3Atmp_328920)) goto LA38;
				x_328916 = res_328923;
				LOC39 = 0;
				LOC39 = nimFloatToStr(rets_328745->data[x_328916]);
				printf("%s%s%s\012", data_328626.date->data[x_328916]? (data_328626.date->data[x_328916])->data:"nil", ((NimStringDesc*) &TMP488)? (((NimStringDesc*) &TMP488))->data:"nil", LOC39? (LOC39)->data:"nil");
				res_328923 += ((NI) 1);
			} LA38: ;
		}
	}
	showdailyreturnsadcl_313258((&data_328626), ((NI) 2));
	printf("\012");
	LOC40 = 0;
	LOC40 = HEX24_147921(((NI) 11593));
	LOC41 = 0;
	LOC41 = sumdailyreturnscl_319258((&data_328626));
	LOC42 = 0;
	LOC42 = nimFloatToStr(LOC41);
	printf("%s%s%s%s\012", ((NimStringDesc*) &TMP489)? (((NimStringDesc*) &TMP489))->data:"nil", LOC40? (LOC40)->data:"nil", ((NimStringDesc*) &TMP490)? (((NimStringDesc*) &TMP490))->data:"nil", LOC42? (LOC42)->data:"nil");
	LOC43 = 0;
	LOC43 = HEX24_147921(((NI) 11593));
	LOC44 = 0;
	LOC44 = sumdailyreturnsadcl_319349((&data_328626));
	LOC45 = 0;
	LOC45 = nimFloatToStr(LOC44);
	printf("%s%s%s%s\012", ((NimStringDesc*) &TMP492)? (((NimStringDesc*) &TMP492))->data:"nil", LOC43? (LOC43)->data:"nil", ((NimStringDesc*) &TMP490)? (((NimStringDesc*) &TMP490))->data:"nil", LOC45? (LOC45)->data:"nil");
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP493)? (((NimStringDesc*) &TMP493))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	LOC46 = 0;
	LOC46 = nsuFormatSingleElem(((NimStringDesc*) &TMP494), data_328626.stock);
	printf("%s\012", LOC46? (LOC46)->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	chckNil((void*)(&htable_329472));
	genericReset((void*)(&htable_329472), (&NTI329036));
	totable_329026(TMP498, 6, (&htable_329472));
	LOC47 = 0;
	LOC47 = ohlcva_329476; ohlcva_329476 = copyStringRC1(((NimStringDesc*) &TMP509));
	if (LOC47) nimGCunrefNoCycle(LOC47);
	chckNil((void*)(&ts_329494));
	genericReset((void*)(&ts_329494), (&NTI259015));
	ts_329494.m_type = (&NTI259015);
	timeseries_329481((&data_328626), ohlcva_329476, (&ts_329494));
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP518)? (((NimStringDesc*) &TMP518))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	LOC48 = 0;
	LOC48 = HEX5BHEX5D_329504(htable_329472, ohlcva_329476);
	showtimeseries_259101((&ts_329494), LOC48, ((NimStringDesc*) &TMP532), ((NI) 5));
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP533)? (((NimStringDesc*) &TMP533))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	LOC49 = 0;
	LOC49 = HEX5BHEX5D_329504(htable_329472, ohlcva_329476);
	showtimeseries_259101((&ts_329494), LOC49, ((NimStringDesc*) &TMP534), ((NI) 5));
	printf("\012");
	setforegroundcolor_138057(((NU8) 32), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP535)? (((NimStringDesc*) &TMP535))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	asgnRefNoCycle((void**) (&ret_329606), mnewString(((NI) 0)));
	LOC50 = 0;
	LOC50 = arg0_329607; arg0_329607 = copyStringRC1(((NimStringDesc*) &TMP536));
	if (LOC50) nimGCunrefNoCycle(LOC50);
	asgnRefNoCycle((void**) (&arg1_329608), first_329571(ts_329494.dd));
	arg2_329609 = first_329589(ts_329494.tx);
	addformat_259404((&ret_329606), arg0_329607, (&TMP537));
	addformat_188850((&ret_329606), ((NimStringDesc*) &TMP488));
	addformat_259404((&ret_329606), arg1_329608, (&TMP538));
	addformat_188850((&ret_329606), ((NimStringDesc*) &TMP490));
	addformat_264004((&ret_329606), arg2_329609, (&TMP539));
	printf("%s\012", ret_329606? (ret_329606)->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	asgnRefNoCycle((void**) (&ret_332076), mnewString(((NI) 0)));
	LOC51 = 0;
	LOC51 = arg0_332077; arg0_332077 = copyStringRC1(((NimStringDesc*) &TMP540));
	if (LOC51) nimGCunrefNoCycle(LOC51);
	asgnRefNoCycle((void**) (&arg1_332078), head_331624(ts_329494.dd, ((NI) 1)));
	asgnRefNoCycle((void**) (&arg2_332079), head_331890(ts_329494.tx, ((NI) 1)));
	addformat_259404((&ret_332076), arg0_332077, (&TMP541));
	addformat_188850((&ret_332076), ((NimStringDesc*) &TMP488));
	addformat_333204((&ret_332076), arg1_332078, (&TMP544));
	addformat_188850((&ret_332076), ((NimStringDesc*) &TMP490));
	addformat_338804((&ret_332076), arg2_332079, (&TMP545));
	printf("%s\012", ret_332076? (ret_332076)->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	asgnRefNoCycle((void**) (&ret_343688), mnewString(((NI) 0)));
	LOC52 = 0;
	LOC52 = arg0_343689; arg0_343689 = copyStringRC1(((NimStringDesc*) &TMP546));
	if (LOC52) nimGCunrefNoCycle(LOC52);
	asgnRefNoCycle((void**) (&arg1_343690), last_343663(ts_329494.dd));
	arg2_343691 = last_328495(ts_329494.tx);
	addformat_259404((&ret_343688), arg0_343689, (&TMP547));
	addformat_188850((&ret_343688), ((NimStringDesc*) &TMP488));
	addformat_259404((&ret_343688), arg1_343690, (&TMP548));
	addformat_188850((&ret_343688), ((NimStringDesc*) &TMP490));
	addformat_264004((&ret_343688), arg2_343691, (&TMP549));
	printf("%s\012", ret_343688? (ret_343688)->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	asgnRefNoCycle((void**) (&ret_345645), mnewString(((NI) 0)));
	LOC53 = 0;
	LOC53 = arg0_345646; arg0_345646 = copyStringRC1(((NimStringDesc*) &TMP550));
	if (LOC53) nimGCunrefNoCycle(LOC53);
	asgnRefNoCycle((void**) (&arg1_345647), tail_331748(ts_329494.dd, ((NI) 1)));
	asgnRefNoCycle((void**) (&arg2_345648), tail_328750(ts_329494.tx, ((NI) 1)));
	addformat_259404((&ret_345645), arg0_345646, (&TMP551));
	addformat_188850((&ret_345645), ((NimStringDesc*) &TMP488));
	addformat_333204((&ret_345645), arg1_345647, (&TMP552));
	addformat_188850((&ret_345645), ((NimStringDesc*) &TMP490));
	addformat_338804((&ret_345645), arg2_345648, (&TMP553));
	printf("%s\012", ret_345645? (ret_345645)->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP554)? (((NimStringDesc*) &TMP554))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	ndays_347650 = ((NI) 22);
	chckNil((void*)(&ema22_347654));
	genericReset((void*)(&ema22_347654), (&NTI259015));
	ema22_347654.m_type = (&NTI259015);
	ema_319433((&data_328626), ndays_347650, (&ema22_347654));
	printf("%s%s\012", ((NimStringDesc*) &TMP556)? (((NimStringDesc*) &TMP556))->data:"nil", data_328626.stock? (data_328626.stock)->data:"nil");
	showema_319609((&ema22_347654), ((NI) 5));
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP562)? (((NimStringDesc*) &TMP562))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s%s%s\012", ((NimStringDesc*) &TMP563)? (((NimStringDesc*) &TMP563))->data:"nil", data_328626.stock? (data_328626.stock)->data:"nil", ((NimStringDesc*) &TMP564)? (((NimStringDesc*) &TMP564))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	statistics_319388((&data_328626.rc->data[((NI) 0)]));
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP571)? (((NimStringDesc*) &TMP571))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	asgnRefNoCycle((void**) (&s_347779), min_347741(ts_329494.dd->data, ts_329494.dd->Sup.len));
	asgnRefNoCycle((void**) (&e_347823), max_347785(ts_329494.dd->data, ts_329494.dd->Sup.len));
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP572)? (((NimStringDesc*) &TMP572))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("%s%s%s\012", s_347779? (s_347779)->data:"nil", ((NimStringDesc*) &TMP573)? (((NimStringDesc*) &TMP573))->data:"nil", e_347823? (e_347823)->data:"nil");
	LOC54 = 0;
	LOC54 = intervalyears_289113(s_347779, e_347823);
	LOC55 = 0;
	LOC55 = nimFloatToStr(LOC54);
	printf("%s%s\012", ((NimStringDesc*) &TMP574)? (((NimStringDesc*) &TMP574))->data:"nil", LOC55? (LOC55)->data:"nil");
	LOC56 = 0;
	LOC56 = intervalmonths_289091(s_347779, e_347823);
	LOC57 = 0;
	LOC57 = nimFloatToStr(LOC56);
	printf("%s%s\012", ((NimStringDesc*) &TMP642)? (((NimStringDesc*) &TMP642))->data:"nil", LOC57? (LOC57)->data:"nil");
	LOC58 = 0;
	LOC58 = intervalweeks_289072(s_347779, e_347823);
	LOC59 = 0;
	LOC59 = nimFloatToStr(LOC58);
	printf("%s%s\012", ((NimStringDesc*) &TMP643)? (((NimStringDesc*) &TMP643))->data:"nil", LOC59? (LOC59)->data:"nil");
	LOC60 = 0;
	LOC60 = intervaldays_289055(s_347779, e_347823);
	LOC61 = 0;
	LOC61 = nimFloatToStr(LOC60);
	printf("%s%s\012", ((NimStringDesc*) &TMP644)? (((NimStringDesc*) &TMP644))->data:"nil", LOC61? (LOC61)->data:"nil");
	LOC62 = 0;
	LOC62 = intervalhours_289040(s_347779, e_347823);
	LOC63 = 0;
	LOC63 = nimFloatToStr(LOC62);
	printf("%s%s\012", ((NimStringDesc*) &TMP645)? (((NimStringDesc*) &TMP645))->data:"nil", LOC63? (LOC63)->data:"nil");
	LOC64 = 0;
	LOC64 = intervalmins_289026(s_347779, e_347823);
	LOC65 = 0;
	LOC65 = nimFloatToStr(LOC64);
	printf("%s%s\012", ((NimStringDesc*) &TMP646)? (((NimStringDesc*) &TMP646))->data:"nil", LOC65? (LOC65)->data:"nil");
	LOC66 = 0;
	LOC66 = intervalsecs_289011(s_347779, e_347823);
	LOC67 = 0;
	LOC67 = nimFloatToStr(LOC66);
	printf("%s%s\012", ((NimStringDesc*) &TMP647)? (((NimStringDesc*) &TMP647))->data:"nil", LOC67? (LOC67)->data:"nil");
	printf("\012");
	printf("%s%s\012", ((NimStringDesc*) &TMP648)? (((NimStringDesc*) &TMP648))->data:"nil", s_347779? (s_347779)->data:"nil");
	LOC68 = 0;
	LOC68 = year_288875(s_347779);
	LOC69 = 0;
	LOC69 = month_288864(s_347779);
	LOC70 = 0;
	LOC70 = day_288843(s_347779);
	printf("%s%s%s%s%s\012", LOC68? (LOC68)->data:"nil", ((NimStringDesc*) &TMP490)? (((NimStringDesc*) &TMP490))->data:"nil", LOC69? (LOC69)->data:"nil", ((NimStringDesc*) &TMP490)? (((NimStringDesc*) &TMP490))->data:"nil", LOC70? (LOC70)->data:"nil");
	decho_272601(((NI) 2));
	printf("%s\012", ((NimStringDesc*) &TMP649)? (((NimStringDesc*) &TMP649))->data:"nil");
	if (somedates_347910) nimGCunrefNoCycle(somedates_347910);
	somedates_347910 = (TY120008*) newSeqRC1((&NTI120008), 11);
	memset((void*)LOC71, 0, sizeof(LOC71));
	LOC71[0] = copyString(((NimStringDesc*) &TMP464));
	LOC71[1] = copyString(((NimStringDesc*) &TMP650));
	LOC71[2] = copyString(((NimStringDesc*) &TMP651));
	LOC71[3] = copyString(((NimStringDesc*) &TMP652));
	LOC71[4] = copyString(((NimStringDesc*) &TMP653));
	LOC71[5] = copyString(((NimStringDesc*) &TMP654));
	LOC71[6] = copyString(((NimStringDesc*) &TMP655));
	LOC71[7] = copyString(((NimStringDesc*) &TMP656));
	LOC71[8] = copyString(((NimStringDesc*) &TMP657));
	LOC71[9] = copyString(((NimStringDesc*) &TMP658));
	LOC71[10] = ntgetDateStr();
	LOC72 = 0;
	LOC72 = somedates_347910->data[0]; somedates_347910->data[0] = copyStringRC1(LOC71[0]);
	if (LOC72) nimGCunrefNoCycle(LOC72);
	LOC73 = 0;
	LOC73 = somedates_347910->data[1]; somedates_347910->data[1] = copyStringRC1(LOC71[1]);
	if (LOC73) nimGCunrefNoCycle(LOC73);
	LOC74 = 0;
	LOC74 = somedates_347910->data[2]; somedates_347910->data[2] = copyStringRC1(LOC71[2]);
	if (LOC74) nimGCunrefNoCycle(LOC74);
	LOC75 = 0;
	LOC75 = somedates_347910->data[3]; somedates_347910->data[3] = copyStringRC1(LOC71[3]);
	if (LOC75) nimGCunrefNoCycle(LOC75);
	LOC76 = 0;
	LOC76 = somedates_347910->data[4]; somedates_347910->data[4] = copyStringRC1(LOC71[4]);
	if (LOC76) nimGCunrefNoCycle(LOC76);
	LOC77 = 0;
	LOC77 = somedates_347910->data[5]; somedates_347910->data[5] = copyStringRC1(LOC71[5]);
	if (LOC77) nimGCunrefNoCycle(LOC77);
	LOC78 = 0;
	LOC78 = somedates_347910->data[6]; somedates_347910->data[6] = copyStringRC1(LOC71[6]);
	if (LOC78) nimGCunrefNoCycle(LOC78);
	LOC79 = 0;
	LOC79 = somedates_347910->data[7]; somedates_347910->data[7] = copyStringRC1(LOC71[7]);
	if (LOC79) nimGCunrefNoCycle(LOC79);
	LOC80 = 0;
	LOC80 = somedates_347910->data[8]; somedates_347910->data[8] = copyStringRC1(LOC71[8]);
	if (LOC80) nimGCunrefNoCycle(LOC80);
	LOC81 = 0;
	LOC81 = somedates_347910->data[9]; somedates_347910->data[9] = copyStringRC1(LOC71[9]);
	if (LOC81) nimGCunrefNoCycle(LOC81);
	LOC82 = 0;
	LOC82 = somedates_347910->data[10]; somedates_347910->data[10] = copyStringRC1(LOC71[10]);
	if (LOC82) nimGCunrefNoCycle(LOC82);
	{
		NI i_350221;
		NI L_350223;
		i_350221 = ((NI) 0);
		L_350223 = (somedates_347910 ? somedates_347910->Sup.len : 0);
		{
			while (1) {
				NimStringDesc* LOC86;
				if (!(i_350221 < L_350223)) goto LA85;
				LOC86 = 0;
				LOC86 = sd_347923; sd_347923 = copyStringRC1(somedates_347910->data[i_350221]);
				if (LOC86) nimGCunrefNoCycle(LOC86);
				{
					NIM_BOOL LOC89;
					NimStringDesc* ret_347926;
					NimStringDesc* arg0_347927;
					NimStringDesc* arg1_347928;
					LOC89 = 0;
					LOC89 = validdate_288885(sd_347923);
					if (!(LOC89 == NIM_TRUE)) goto LA90;
					setforegroundcolor_138057(((NU8) 32), NIM_FALSE);
					ret_347926 = mnewString(((NI) 0));
					arg0_347927 = sd_347923;
					arg1_347928 = copyString(((NimStringDesc*) &TMP659));
					addformat_259404((&ret_347926), arg0_347927, (&TMP660));
					addformat_188850((&ret_347926), ((NimStringDesc*) &TMP490));
					addformat_259404((&ret_347926), arg1_347928, (&TMP661));
					printf("%s\012", ret_347926? (ret_347926)->data:"nil");
					setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
				}
				goto LA87;
				LA90: ;
				{
					NimStringDesc* ret_349020;
					NimStringDesc* arg0_349021;
					NimStringDesc* arg1_349022;
					setforegroundcolor_138057(((NU8) 31), NIM_FALSE);
					ret_349020 = mnewString(((NI) 0));
					arg0_349021 = sd_347923;
					arg1_349022 = copyString(((NimStringDesc*) &TMP662));
					addformat_259404((&ret_349020), arg0_349021, (&TMP663));
					addformat_188850((&ret_349020), ((NimStringDesc*) &TMP490));
					addformat_259404((&ret_349020), arg1_349022, (&TMP664));
					printf("%s\012", ret_349020? (ret_349020)->data:"nil");
					setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
				}
				LA87: ;
				i_350221 += ((NI) 1);
			} LA85: ;
		}
	}
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP665)? (((NimStringDesc*) &TMP665))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	a_350248 = ((NI) 5);
	asgnRefNoCycle((void**) (&ret_350254), mnewString(((NI) 0)));
	LOC93 = 0;
	LOC93 = arg0_350255; arg0_350255 = copyStringRC1(((NimStringDesc*) &TMP666));
	if (LOC93) nimGCunrefNoCycle(LOC93);
	LOC94 = 0;
	LOC94 = arg1_350256; arg1_350256 = copyStringRC1(((NimStringDesc*) &TMP667));
	if (LOC94) nimGCunrefNoCycle(LOC94);
	LOC95 = 0;
	LOC95 = arg2_350257; arg2_350257 = copyStringRC1(((NimStringDesc*) &TMP668));
	if (LOC95) nimGCunrefNoCycle(LOC95);
	addformat_259404((&ret_350254), arg0_350255, (&TMP669));
	addformat_188850((&ret_350254), ((NimStringDesc*) &TMP490));
	addformat_259404((&ret_350254), arg1_350256, (&TMP670));
	addformat_188850((&ret_350254), ((NimStringDesc*) &TMP490));
	addformat_259404((&ret_350254), arg2_350257, (&TMP671));
	printf("%s\012", ret_350254? (ret_350254)->data:"nil");
	{
		NI HEX3Atmp_354219;
		NI res_354222;
		HEX3Atmp_354219 = 0;
		HEX3Atmp_354219 = ((NI64)-(a_350248));
		res_354222 = HEX3Atmp_354219;
		{
			while (1) {
				NF xx;
				NF LOC99;
				NimStringDesc* ret_352236;
				NF arg0_352237;
				NF arg1_352238;
				NF arg2_352239;
				if (!(res_354222 <= a_350248)) goto LA98;
				x_352231 = res_354222;
				LOC99 = 0;
				LOC99 = random_203535();
				xx = ((NF)(LOC99) * (NF)(1.8000000000000000e+00));
				ret_352236 = mnewString(((NI) 0));
				arg0_352237 = xx;
				arg1_352238 = logisticf_327041(xx);
				arg2_352239 = logisticfderivative_327058(xx);
				addformat_264004((&ret_352236), arg0_352237, (&TMP672));
				addformat_188850((&ret_352236), ((NimStringDesc*) &TMP490));
				addformat_264004((&ret_352236), arg1_352238, (&TMP673));
				addformat_188850((&ret_352236), ((NimStringDesc*) &TMP490));
				addformat_264004((&ret_352236), arg2_352239, (&TMP674));
				printf("%s\012", ret_352236? (ret_352236)->data:"nil");
				res_354222 += ((NI) 1);
			} LA98: ;
		}
	}
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP675)? (((NimStringDesc*) &TMP675))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP676)? (((NimStringDesc*) &TMP676))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP675)? (((NimStringDesc*) &TMP675))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	showcurrentstocks_288823(((NimStringDesc*) &TMP702));
	showcurrentstocks_288802((&account_328335.pf->data[((NI) 0)]));
	LOC100 = 0;
	LOC100 = idx_354273; idx_354273 = copyStringRC1(indexpool_328241->data[((NI) 0)].stock);
	if (LOC100) nimGCunrefNoCycle(LOC100);
	showcurrentindexes_288760(idx_354273);
	showcurrentindexes_288780(indexpool_328241);
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP717)? (((NimStringDesc*) &TMP717))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP145)? (((NimStringDesc*) &TMP145))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	printf("\012");
	setforegroundcolor_138057(((NU8) 33), NIM_FALSE);
	printf("%s\012", ((NimStringDesc*) &TMP718)? (((NimStringDesc*) &TMP718))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	genericSeqAssign((&checkcurrencies_354338), TMP719, (&NTI120008));
	showcurrentforex_322965(checkcurrencies_354338);
	chckNil((void*)(&curs_354358));
	genericReset((void*)(&curs_354358), (&NTI259017));
	curs_354358.m_type = (&NTI259017);
	getcurrentforex_322831(TMP745, (&curs_354358));
	printf("\012");
	asgnRefNoCycle((void**) (&ret_354381), mnewString(((NI) 0)));
	arg0_354382 = last_328495(curs_354358.ra);
	addformat_264004((&ret_354381), arg0_354382, (&TMP748));
	printf("%s%s\012", ((NimStringDesc*) &TMP747)? (((NimStringDesc*) &TMP747))->data:"nil", ret_354381? (ret_354381)->data:"nil");
	asgnRefNoCycle((void**) (&ret_354831), mnewString(((NI) 0)));
	arg0_354832 = first_329589(curs_354358.ra);
	addformat_264004((&ret_354831), arg0_354832, (&TMP750));
	printf("%s%s\012", ((NimStringDesc*) &TMP749)? (((NimStringDesc*) &TMP749))->data:"nil", ret_354831? (ret_354831)->data:"nil");
	printf("\012");
	printf("\012");
	setforegroundcolor_138057(((NU8) 36), NIM_FALSE);
	LOC101 = 0;
	LOC101 = ntepochTime();
	LOC102 = 0;
	LOC102 = nimFloatToStr(((NF)(LOC101) - (NF)(start_328004)));
	printf("%s%s%s\012", ((NimStringDesc*) &TMP751)? (((NimStringDesc*) &TMP751))->data:"nil", LOC102? (LOC102)->data:"nil", ((NimStringDesc*) &TMP752)? (((NimStringDesc*) &TMP752))->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	setforegroundcolor_138057(((NU8) 32), NIM_FALSE);
	printf("%s%s\012", ((NimStringDesc*) &TMP753)? (((NimStringDesc*) &TMP753))->data:"nil", Version_259004? (Version_259004)->data:"nil");
	setforegroundcolor_138057(((NU8) 37), NIM_FALSE);
	printf("\012");
	printf("\012");
	atexit(resetattributes_137209);
	Gcfullcollect_8805();
	exit(((NI) 0));
}

NIM_EXTERNC N_NOINLINE(void, nimFinT5DatInit)(void) {
}

