/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/nimFinLib_example2.o /data4/NimStuff/NimFinLib/nimcache/nimFinLib_example2.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <stdlib.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, paramcount_123830)(void);
N_NIMCALL(void, showcurrentstocks_275823)(NimStringDesc* stcks);
N_NIMCALL(NimStringDesc*, paramstr_123809)(NI i);
N_NIMCALL(void, decho_259601)(NI z);
N_NIMCALL(void, setforegroundcolor_240057)(NU8 fg, NIM_BOOL bright);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_fenvInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_fenvDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pegsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pegsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimfinlib_nimFinLibInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimfinlib_nimFinLibDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, example2Init)(void);
NIM_EXTERNC N_NOINLINE(void, example2DatInit)(void);
STRING_LITERAL(TMP261, "Usage :", 7);
STRING_LITERAL(TMP262, "example2  IBM+BP.L+AAPL", 23);

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_timesDatInit();
	stdlib_posixDatInit();
	stdlib_osDatInit();
	stdlib_sequtilsDatInit();
	stdlib_unsignedDatInit();
	stdlib_rawsocketsDatInit();
	stdlib_opensslDatInit();
	stdlib_netDatInit();
	stdlib_uriDatInit();
	stdlib_etcprivDatInit();
	stdlib_hashesDatInit();
	stdlib_strtabsDatInit();
	stdlib_base64DatInit();
	stdlib_mimetypesDatInit();
	stdlib_mathDatInit();
	stdlib_endiansDatInit();
	stdlib_oidsDatInit();
	stdlib_tablesDatInit();
	stdlib_macrosDatInit();
	stdlib_epollDatInit();
	stdlib_selectorsDatInit();
	stdlib_asyncdispatchDatInit();
	stdlib_asyncnetDatInit();
	stdlib_httpclientDatInit();
	stdlib_unicodeDatInit();
	stdlib_fenvDatInit();
	stdlib_pegsDatInit();
	stdlib_streamsDatInit();
	HEX00_strfmtDatInit();
	stdlib_termiosDatInit();
	stdlib_terminalDatInit();
	stdlib_lexbaseDatInit();
	stdlib_parsecsvDatInit();
	stdlib_algorithmDatInit();
	nimfinlib_nimFinLibDatInit();
	example2DatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_timesInit();
	stdlib_posixInit();
	stdlib_osInit();
	stdlib_sequtilsInit();
	stdlib_unsignedInit();
	stdlib_rawsocketsInit();
	stdlib_opensslInit();
	stdlib_netInit();
	stdlib_uriInit();
	stdlib_etcprivInit();
	stdlib_hashesInit();
	stdlib_strtabsInit();
	stdlib_base64Init();
	stdlib_mimetypesInit();
	stdlib_mathInit();
	stdlib_endiansInit();
	stdlib_oidsInit();
	stdlib_tablesInit();
	stdlib_macrosInit();
	stdlib_epollInit();
	stdlib_selectorsInit();
	stdlib_asyncdispatchInit();
	stdlib_asyncnetInit();
	stdlib_httpclientInit();
	stdlib_unicodeInit();
	stdlib_fenvInit();
	stdlib_pegsInit();
	stdlib_streamsInit();
	HEX00_strfmtInit();
	stdlib_termiosInit();
	stdlib_terminalInit();
	stdlib_lexbaseInit();
	stdlib_parsecsvInit();
	stdlib_algorithmInit();
	nimfinlib_nimFinLibInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	example2Init();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, example2Init)(void) {
	{
		NI LOC3;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = paramcount_123830();
		if (!(((NI) 0) < LOC3)) goto LA4;
		LOC6 = 0;
		LOC6 = paramstr_123809(((NI) 1));
		showcurrentstocks_275823(LOC6);
		decho_259601(((NI) 2));
	}
	goto LA1;
	LA4: ;
	{
		setforegroundcolor_240057(((NU8) 33), NIM_FALSE);
		printf("%s\012", ((NimStringDesc*) &TMP261)? (((NimStringDesc*) &TMP261))->data:"nil");
		printf("%s\012", ((NimStringDesc*) &TMP262)? (((NimStringDesc*) &TMP262))->data:"nil");
		printf("\012");
		setforegroundcolor_240057(((NU8) 37), NIM_FALSE);
	}
	LA1: ;
	exit(((NI) 0));
}

NIM_EXTERNC N_NOINLINE(void, example2DatInit)(void) {
}

