/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/nimFinLib_example1.o /data4/NimStuff/NimFinLib/nimcache/nimFinLib_example1.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Df246013 Df246013;
typedef struct Nf246011 Nf246011;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY246021 TY246021;
typedef struct TY120008 TY120008;
typedef struct TY246026 TY246026;
typedef struct TY246038 TY246038;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Format232215 Format232215;
typedef struct Runningstat159047 Runningstat159047;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  Nf246011  {
TNimType* m_type;
NimStringDesc* nx;
TY246021* dx;
};
struct  Df246013  {
  Nf246011 Sup;
NimStringDesc* stock;
TY120008* date;
TY246026* open;
TY246026* high;
TY246026* low;
TY246026* close;
TY246026* vol;
TY246026* adjc;
TY246038* rc;
TY246038* rca;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
struct Format232215 {
NU8 Field0;
NI Field1;
NI Field2;
NimStringDesc* Field3;
NU8 Field4;
NU8 Field5;
NIM_BOOL Field6;
NIM_BOOL Field7;
NIM_BOOL Field8;
NimStringDesc* Field9;
};
struct  Runningstat159047  {
NI n;
NF sum;
NF min;
NF max;
NF mean;
NF oldm;
NF olds;
NF news;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
struct TY120008 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY246026 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct TY246021 {
  TGenericSeq Sup;
  Df246013 data[SEQ_DECL_SIZE];
};
struct TY246038 {
  TGenericSeq Sup;
  Runningstat159047 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, showcurrentstocks_275823)(NimStringDesc* stcks);
N_NIMCALL(void, decho_259601)(NI z);
N_NIMCALL(void, initdf_258854)(Df246013* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, getsymbol2_276133)(NimStringDesc* symb, NimStringDesc* startdate, NimStringDesc* enddate, Df246013* Result);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(void, showhistdata_278922)(Df246013* adf, NI n);
N_NIMCALL(void, showhistdata_288458)(Df246013* adf, NimStringDesc* s, NimStringDesc* e);
N_NIMCALL(void, showdailyreturnscl_294941)(Df246013* self, NI N);
N_NIMCALL(void, setforegroundcolor_240057)(NU8 fg, NIM_BOOL bright);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, addformat_246404)(NimStringDesc** o, NimStringDesc* x, Format232215* fmt);
N_NIMCALL(void, writeformat_248004)(NimStringDesc** o, NimStringDesc* s, Format232215* fmt);
static N_INLINE(void, addformat_232850)(NimStringDesc** s, NimStringDesc* x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, last_317024)(TY120008* self);
N_NIMCALL(NF, last_317042)(TY246026* self);
static N_INLINE(void, addformat_251004)(NimStringDesc** o, NF x, Format232215* fmt);
N_NIMCALL(void, writeformat_252604)(NimStringDesc** o, NF x, Format232215* fmt_252614);
N_NIMCALL(void, showcurrentforex_309965)(TY120008* curs);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_fenvInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_fenvDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pegsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pegsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimfinlib_nimFinLibInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimfinlib_nimFinLibDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, example1Init)(void);
NIM_EXTERNC N_NOINLINE(void, example1DatInit)(void);
STRING_LITERAL(TMP259, "IBM+BP.L+0001.HK", 16);
STRING_LITERAL(TMP311, "IBM", 3);
STRING_LITERAL(TMP312, "2000-01-01", 10);
STRING_LITERAL(TMP395, "2015-01-12", 10);
STRING_LITERAL(TMP396, "2015-01-19", 10);
STRING_LITERAL(TMP407, "Code", 4);
STRING_LITERAL(TMP408, "Date", 4);
STRING_LITERAL(TMP409, "Adj.Close", 9);
NIM_CONST Format232215 TMP410 = {((NU8) 0),
((NI) -1),
((NI) 8),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP411, " ", 1);
NIM_CONST Format232215 TMP412 = {((NU8) 0),
((NI) -1),
((NI) 11),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format232215 TMP413 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format232215 TMP414 = {((NU8) 0),
((NI) -1),
((NI) 8),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format232215 TMP415 = {((NU8) 0),
((NI) -1),
((NI) 11),
NIM_NIL,
((NU8) 1),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
NIM_CONST Format232215 TMP416 = {((NU8) 0),
((NI) -1),
((NI) 15),
NIM_NIL,
((NU8) 2),
((NU8) 0),
NIM_FALSE,
NIM_FALSE,
NIM_FALSE,
NIM_NIL}
;
STRING_LITERAL(TMP434, "EURUSD", 6);
STRING_LITERAL(TMP435, "GBPHKD", 6);
STRING_LITERAL(TMP436, "CADEUR", 6);
STRING_LITERAL(TMP437, "AUDNZD", 6);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[4];
} CNSTSEQ439 = {{4, 4}, {((NimStringDesc*) &TMP434),
((NimStringDesc*) &TMP435),
((NimStringDesc*) &TMP436),
((NimStringDesc*) &TMP437)}};
NIM_CONST TY120008* TMP433 = ((TY120008*)&CNSTSEQ439);
Df246013 ibm_315010;
extern TNimType NTI246013; /* Df */
NimStringDesc* ret_315031;
extern Gcheap46616 gch_46648;
NimStringDesc* arg0_315032;
NimStringDesc* arg1_315033;
NimStringDesc* arg2_315034;
NimStringDesc* ret_317059;
NimStringDesc* arg0_317060;
NimStringDesc* arg1_317061;
NF arg2_317062;

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell44747* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_48246(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell44747* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_48246((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_49804(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

static N_INLINE(void, addformat_246404)(NimStringDesc** o, NimStringDesc* x, Format232215* fmt) {
	writeformat_248004(o, x, fmt);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, addformat_232850)(NimStringDesc** s, NimStringDesc* x) {
	(*s) = resizeString((*s), x->Sup.len + 0);
appendString((*s), x);
}

static N_INLINE(void, addformat_251004)(NimStringDesc** o, NF x, Format232215* fmt) {
	writeformat_252604(o, x, fmt);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_timesDatInit();
	stdlib_posixDatInit();
	stdlib_osDatInit();
	stdlib_sequtilsDatInit();
	stdlib_unsignedDatInit();
	stdlib_rawsocketsDatInit();
	stdlib_opensslDatInit();
	stdlib_netDatInit();
	stdlib_uriDatInit();
	stdlib_etcprivDatInit();
	stdlib_hashesDatInit();
	stdlib_strtabsDatInit();
	stdlib_base64DatInit();
	stdlib_mimetypesDatInit();
	stdlib_mathDatInit();
	stdlib_endiansDatInit();
	stdlib_oidsDatInit();
	stdlib_tablesDatInit();
	stdlib_macrosDatInit();
	stdlib_epollDatInit();
	stdlib_selectorsDatInit();
	stdlib_asyncdispatchDatInit();
	stdlib_asyncnetDatInit();
	stdlib_httpclientDatInit();
	stdlib_unicodeDatInit();
	stdlib_fenvDatInit();
	stdlib_pegsDatInit();
	stdlib_streamsDatInit();
	HEX00_strfmtDatInit();
	stdlib_termiosDatInit();
	stdlib_terminalDatInit();
	stdlib_lexbaseDatInit();
	stdlib_parsecsvDatInit();
	stdlib_algorithmDatInit();
	nimfinlib_nimFinLibDatInit();
	example1DatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_timesInit();
	stdlib_posixInit();
	stdlib_osInit();
	stdlib_sequtilsInit();
	stdlib_unsignedInit();
	stdlib_rawsocketsInit();
	stdlib_opensslInit();
	stdlib_netInit();
	stdlib_uriInit();
	stdlib_etcprivInit();
	stdlib_hashesInit();
	stdlib_strtabsInit();
	stdlib_base64Init();
	stdlib_mimetypesInit();
	stdlib_mathInit();
	stdlib_endiansInit();
	stdlib_oidsInit();
	stdlib_tablesInit();
	stdlib_macrosInit();
	stdlib_epollInit();
	stdlib_selectorsInit();
	stdlib_asyncdispatchInit();
	stdlib_asyncnetInit();
	stdlib_httpclientInit();
	stdlib_unicodeInit();
	stdlib_fenvInit();
	stdlib_pegsInit();
	stdlib_streamsInit();
	HEX00_strfmtInit();
	stdlib_termiosInit();
	stdlib_terminalInit();
	stdlib_lexbaseInit();
	stdlib_parsecsvInit();
	stdlib_algorithmInit();
	nimfinlib_nimFinLibInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	example1Init();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, example1Init)(void) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	ibm_315010.Sup.m_type = (&NTI246013);
	showcurrentstocks_275823(((NimStringDesc*) &TMP259));
	decho_259601(((NI) 2));
	chckNil((void*)(&ibm_315010));
	genericReset((void*)(&ibm_315010), (&NTI246013));
	ibm_315010.Sup.m_type = (&NTI246013);
	initdf_258854((&ibm_315010));
	LOC1 = 0;
	LOC1 = ntgetDateStr();
	chckNil((void*)(&ibm_315010));
	genericReset((void*)(&ibm_315010), (&NTI246013));
	ibm_315010.Sup.m_type = (&NTI246013);
	getsymbol2_276133(((NimStringDesc*) &TMP311), ((NimStringDesc*) &TMP312), LOC1, (&ibm_315010));
	showhistdata_278922((&ibm_315010), ((NI) 5));
	showhistdata_288458((&ibm_315010), ((NimStringDesc*) &TMP395), ((NimStringDesc*) &TMP396));
	showdailyreturnscl_294941((&ibm_315010), ((NI) 5));
	decho_259601(((NI) 3));
	setforegroundcolor_240057(((NU8) 32), NIM_FALSE);
	asgnRefNoCycle((void**) (&ret_315031), mnewString(((NI) 0)));
	LOC2 = 0;
	LOC2 = arg0_315032; arg0_315032 = copyStringRC1(((NimStringDesc*) &TMP407));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	LOC3 = 0;
	LOC3 = arg1_315033; arg1_315033 = copyStringRC1(((NimStringDesc*) &TMP408));
	if (LOC3) nimGCunrefNoCycle(LOC3);
	LOC4 = 0;
	LOC4 = arg2_315034; arg2_315034 = copyStringRC1(((NimStringDesc*) &TMP409));
	if (LOC4) nimGCunrefNoCycle(LOC4);
	addformat_246404((&ret_315031), arg0_315032, (&TMP410));
	addformat_232850((&ret_315031), ((NimStringDesc*) &TMP411));
	addformat_246404((&ret_315031), arg1_315033, (&TMP412));
	addformat_232850((&ret_315031), ((NimStringDesc*) &TMP411));
	addformat_246404((&ret_315031), arg2_315034, (&TMP413));
	printf("%s\012", ret_315031? (ret_315031)->data:"nil");
	setforegroundcolor_240057(((NU8) 37), NIM_FALSE);
	asgnRefNoCycle((void**) (&ret_317059), mnewString(((NI) 0)));
	LOC5 = 0;
	LOC5 = arg0_317060; arg0_317060 = copyStringRC1(ibm_315010.stock);
	if (LOC5) nimGCunrefNoCycle(LOC5);
	asgnRefNoCycle((void**) (&arg1_317061), last_317024(ibm_315010.date));
	arg2_317062 = last_317042(ibm_315010.adjc);
	addformat_246404((&ret_317059), arg0_317060, (&TMP414));
	addformat_232850((&ret_317059), ((NimStringDesc*) &TMP411));
	addformat_246404((&ret_317059), arg1_317061, (&TMP415));
	addformat_232850((&ret_317059), ((NimStringDesc*) &TMP411));
	addformat_251004((&ret_317059), arg2_317062, (&TMP416));
	printf("%s\012", ret_317059? (ret_317059)->data:"nil");
	decho_259601(((NI) 1));
	showcurrentforex_309965(TMP433);
	decho_259601(((NI) 3));
}

NIM_EXTERNC N_NOINLINE(void, example1DatInit)(void) {
}

