/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/random_common.o /data4/NimStuff/NimFinLib/nimcache/random_common.c */
#define NIM_INTBITS 64
#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, random_commonInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, random_commonDatInit)(void) {
}

