/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/random_mt19937ar.o /data4/NimStuff/NimFinLib/nimcache/random_mt19937ar.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct Mersennetwister197035 Mersennetwister197035;
typedef NU32 TY197036[624];
struct  Mersennetwister197035  {
TY197036 mt;
NI mti;
};
typedef NU32 TY197330[2];
N_NIMCALL(void, initgenrand_197053)(Mersennetwister197035* s, NU32 seed);
N_NIMCALL(NU32, genrandint32_197324)(Mersennetwister197035* s);

N_NIMCALL(Mersennetwister197035, initmtstate_197043)(void) {
	Mersennetwister197035 result;
	memset((void*)(&result), 0, sizeof(result));
	result.mti = ((NI) 625);
	return result;
}

N_NIMCALL(void, initgenrand_197053)(Mersennetwister197035* s, NU32 seed) {
	(*s).mt[(((NI) 0))- 0] = seed;
	(*s).mti = ((NI) 1);
	{
		while (1) {
			if (!((*s).mti < ((NI) 624))) goto LA2;
			(*s).mt[((*s).mti)- 0] = (NU32)((NU32)((NU32)((NU32)(((NU32) 1812433253)) * (NU32)((NU32)((*s).mt[((NI)((*s).mti - ((NI) 1)))- 0] ^ (NU32)((NU64)((*s).mt[((NI)((*s).mti - ((NI) 1)))- 0]) >> (NU64)(((NI) 30))))))) + (NU32)(((NU32) ((*s).mti))));
			(*s).mti += ((NI) 1);
		} LA2: ;
	}
}

N_NIMCALL(void, initbyarray_197116)(Mersennetwister197035* s, NU32* initkey, NI initkeyLen0) {
	NI keylength;
	NI i;
	NI j;
	keylength = initkeyLen0;
	initgenrand_197053(s, ((NU32) 19650218));
	i = ((NI) 1);
	j = ((NI) 0);
	{
		NI k_197143;
		NI HEX3Atmp_197286;
		NI res_197289;
		k_197143 = 0;
		HEX3Atmp_197286 = 0;
		{
			if (!(keylength < ((NI) 624))) goto LA4;
			HEX3Atmp_197286 = ((NI) 624);
		}
		goto LA2;
		LA4: ;
		{
			HEX3Atmp_197286 = keylength;
		}
		LA2: ;
		res_197289 = HEX3Atmp_197286;
		{
			while (1) {
				if (!(((NI) 1) <= res_197289)) goto LA8;
				k_197143 = res_197289;
				(*s).mt[(i)- 0] = (NU32)((NU32)((NU32)((NU32)((NU32)((*s).mt[(i)- 0] ^ (NU32)((NU32)((NU32)((*s).mt[((NI)(i - ((NI) 1)))- 0] ^ (NU32)((NU64)((*s).mt[((NI)(i - ((NI) 1)))- 0]) >> (NU64)(((NI) 30))))) * (NU32)(((NU32) 1664525))))) + (NU32)(initkey[j]))) + (NU32)(((NU32) (j))));
				i += ((NI) 1);
				j += ((NI) 1);
				{
					if (!(((NI) 624) <= i)) goto LA11;
					(*s).mt[(((NI) 0))- 0] = (*s).mt[(((NI) 623))- 0];
					i = ((NI) 1);
				}
				LA11: ;
				{
					if (!(keylength <= j)) goto LA15;
					j = ((NI) 0);
				}
				LA15: ;
				res_197289 -= ((NI) 1);
			} LA8: ;
		}
	}
	{
		NI k_197229;
		NI res_197296;
		k_197229 = 0;
		res_197296 = ((NI) 623);
		{
			while (1) {
				if (!(((NI) 1) <= res_197296)) goto LA19;
				k_197229 = res_197296;
				(*s).mt[(i)- 0] = (NU32)((NU32)((NU32)((*s).mt[(i)- 0] ^ (NU32)((NU32)((NU32)((*s).mt[((NI)(i - ((NI) 1)))- 0] ^ (NU32)((NU64)((*s).mt[((NI)(i - ((NI) 1)))- 0]) >> (NU64)(((NI) 30))))) * (NU32)(((NU32) 1566083941))))) - (NU32)(((NU32) (i))));
				i += ((NI) 1);
				{
					if (!(((NI) 624) <= i)) goto LA22;
					(*s).mt[(((NI) 0))- 0] = (*s).mt[(((NI) 623))- 0];
					i = ((NI) 1);
				}
				LA22: ;
				res_197296 -= ((NI) 1);
			} LA19: ;
		}
	}
	(*s).mt[(((NI) 0))- 0] = ((NU32) (-2147483647 -1));
}

N_NIMCALL(NU32, genrandint32_197324)(Mersennetwister197035* s) {
	NU32 result;
	NU32 y;
	TY197330 mag01;
{	result = 0;
	y = 0;
	memset((void*)mag01, 0, sizeof(mag01));
	mag01[0] = ((NU32) 0);
	mag01[1] = ((NU32) -1727483681);
	{
		if (!(((NI) 624) <= (*s).mti)) goto LA3;
		{
			if (!((*s).mti == ((NI) 625))) goto LA7;
			initgenrand_197053(s, ((NU32) 5489));
		}
		LA7: ;
		{
			NI kk_197354;
			NI res_197679;
			kk_197354 = 0;
			res_197679 = ((NI) 0);
			{
				while (1) {
					if (!(res_197679 <= ((NI) 226))) goto LA11;
					kk_197354 = res_197679;
					y = (unsigned int)((unsigned int)((*s).mt[(kk_197354)- 0] & ((NU32) (-2147483647 -1))) | ((unsigned int) ((NU32)((*s).mt[((NI)(kk_197354 + ((NI) 1)))- 0] & ((NU32) 2147483647)))));
					(*s).mt[(kk_197354)- 0] = (NU32)((NU32)((*s).mt[((NI)(kk_197354 + ((NI) 397)))- 0] ^ (NU32)((NU64)(y) >> (NU64)(((NI) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
					res_197679 += ((NI) 1);
				} LA11: ;
			}
		}
		{
			NI kk_197441;
			NI res_197686;
			kk_197441 = 0;
			res_197686 = ((NI) 227);
			{
				while (1) {
					if (!(res_197686 <= ((NI) 622))) goto LA14;
					kk_197441 = res_197686;
					y = (unsigned int)((unsigned int)((*s).mt[(kk_197441)- 0] & ((NU32) (-2147483647 -1))) | ((unsigned int) ((NU32)((*s).mt[((NI)(kk_197441 + ((NI) 1)))- 0] & ((NU32) 2147483647)))));
					(*s).mt[(kk_197441)- 0] = (NU32)((NU32)((*s).mt[((NI)(kk_197441 + ((NI) -227)))- 0] ^ (NU32)((NU64)(y) >> (NU64)(((NI) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
					res_197686 += ((NI) 1);
				} LA14: ;
			}
		}
		y = (unsigned int)((unsigned int)((*s).mt[(((NI) 623))- 0] & ((NU32) (-2147483647 -1))) | ((unsigned int) ((NU32)((*s).mt[(((NI) 0))- 0] & ((NU32) 2147483647)))));
		(*s).mt[(((NI) 623))- 0] = (NU32)((NU32)((*s).mt[(((NI) 396))- 0] ^ (NU32)((NU64)(y) >> (NU64)(((NI) 1)))) ^ mag01[((NU32)(y & ((NU32) 1)))- 0]);
		(*s).mti = ((NI) 0);
	}
	LA3: ;
	y = (*s).mt[((*s).mti)- 0];
	(*s).mti += ((NI) 1);
	y = (NU32)(y ^ (NU32)((NU64)(y) >> (NU64)(((NI) 11))));
	y = (NU32)(y ^ (unsigned int)((NU32)((NU64)(y) << (NU64)(((NI) 7))) & ((NU32) -1658038656)));
	y = (NU32)(y ^ (unsigned int)((NU32)((NU64)(y) << (NU64)(((NI) 15))) & ((NU32) -272236544)));
	y = (NU32)(y ^ (NU32)((NU64)(y) >> (NU64)(((NI) 18))));
	result = y;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NF, genrandres53_197780)(Mersennetwister197035* s) {
	NF result;
	NU32 a;
	NU32 LOC1;
	NU32 b;
	NU32 LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = genrandint32_197324(s);
	a = (NU32)((NU64)(LOC1) >> (NU64)(((NI) 5)));
	LOC2 = 0;
	LOC2 = genrandint32_197324(s);
	b = (NU32)((NU64)(LOC2) >> (NU64)(((NI) 6)));
	result = ((NF)(((NF)(((NF)(((NF) (a))) * (NF)(6.7108864000000000e+07))) + (NF)(((NF) (b))))) * (NF)(1.1102230246251565e-16));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, random_mt19937arInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, random_mt19937arDatInit)(void) {
}

