/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o nimcache/random_urandom.o nimcache/random_urandom.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct TY200225 TY200225;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct Oserror3433 Oserror3433;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Oserror3433  {
  Systemerror3429 Sup;
NI32 errorcode;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
struct TY200225 {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP66)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NIM_BOOL, open_13403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, readbuffer_13553)(FILE* f, void* buffer, NI len);
STRING_LITERAL(TMP72, "/dev/urandom", 12);
STRING_LITERAL(TMP74, "/dev/urandom is not available", 29);
STRING_LITERAL(TMP75, "Can\'t read enough bytes from /dev/urandom", 41);
extern TNimType NTI120; /* uint8 */
TNimType NTI200225; /* seq[uint8] */
extern TNimType NTI200404; /* ref OSError */
extern TNimType NTI3433; /* OSError */
extern Gcheap46616 gch_46648;
N_NIMCALL(void, TMP66)(void* p, NI op) {
	TY200225* a;
	NI LOC1;
	a = (TY200225*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

N_NIMCALL(TY200225*, urandom_200222)(NI size) {
	TY200225* result;
	FILE* file_200240;
	NI index_200242;
	result = 0;
	result = (TY200225*) newSeq((&NTI200225), size);
	file_200240 = 0;
	{
		NIM_BOOL LOC3;
		Oserror3433* e_200403;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = open_13403(&file_200240, ((NimStringDesc*) &TMP72), ((NU8) 0), ((NI) -1));
		if (!!(LOC3)) goto LA4;
		e_200403 = 0;
		e_200403 = (Oserror3433*) newObj((&NTI200404), sizeof(Oserror3433));
		(*e_200403).Sup.Sup.Sup.m_type = (&NTI3433);
		LOC6 = 0;
		LOC6 = (*e_200403).Sup.Sup.message; (*e_200403).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP74));
		if (LOC6) nimGCunrefNoCycle(LOC6);
		raiseException((Exception*)e_200403, "OSError");
	}
	LA4: ;
	index_200242 = ((NI) 0);
	{
		while (1) {
			NI bytesread_200244;
			if (!(index_200242 < ((NI) (size)))) goto LA8;
			bytesread_200244 = readbuffer_13553(file_200240, ((void*) ((&result->data[index_200242]))), ((NI) ((NI)(((NI) (size)) - index_200242))));
			{
				Oserror3433* e_200415;
				NimStringDesc* LOC13;
				if (!(bytesread_200244 <= ((NI) 0))) goto LA11;
				e_200415 = 0;
				e_200415 = (Oserror3433*) newObj((&NTI200404), sizeof(Oserror3433));
				(*e_200415).Sup.Sup.Sup.m_type = (&NTI3433);
				LOC13 = 0;
				LOC13 = (*e_200415).Sup.Sup.message; (*e_200415).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP75));
				if (LOC13) nimGCunrefNoCycle(LOC13);
				raiseException((Exception*)e_200415, "OSError");
			}
			LA11: ;
			index_200242 += bytesread_200244;
		} LA8: ;
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, random_urandomInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, random_urandomDatInit)(void) {
NTI200225.size = sizeof(TY200225*);
NTI200225.kind = 24;
NTI200225.base = (&NTI120);
NTI200225.flags = 2;
NTI200225.marker = TMP66;
}

