/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/stdlib_unicode.o /data4/NimStuff/NimFinLib/nimcache/stdlib_unicode.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI c);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);

N_NIMCALL(NI, nucruneLen)(NimStringDesc* s) {
	NI result;
	NI i;
	result = 0;
	i = ((NI) 0);
	{
		while (1) {
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			{
				if (!((NU64)(((NI) (((NU8)(s->data[i]))))) <= (NU64)(((NI) 127)))) goto LA5;
				i += ((NI) 1);
			}
			goto LA3;
			LA5: ;
			{
				if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA8;
				i += ((NI) 2);
			}
			goto LA3;
			LA8: ;
			{
				if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA11;
				i += ((NI) 3);
			}
			goto LA3;
			LA11: ;
			{
				if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA14;
				i += ((NI) 4);
			}
			goto LA3;
			LA14: ;
			{
				if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 2))) == ((NI) 62))) goto LA17;
				i += ((NI) 5);
			}
			goto LA3;
			LA17: ;
			{
				if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 1))) == ((NI) 126))) goto LA20;
				i += ((NI) 6);
			}
			goto LA3;
			LA20: ;
			{
				i += ((NI) 1);
			}
			LA3: ;
			result += ((NI) 1);
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NI, runelenat_146234)(NimStringDesc* s, NI i) {
	NI result;
	result = 0;
	{
		if (!((NU64)(((NI) (((NU8)(s->data[i]))))) <= (NU64)(((NI) 127)))) goto LA3;
		result = ((NI) 1);
	}
	goto LA1;
	LA3: ;
	{
		if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA6;
		result = ((NI) 2);
	}
	goto LA1;
	LA6: ;
	{
		if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA9;
		result = ((NI) 3);
	}
	goto LA1;
	LA9: ;
	{
		if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA12;
		result = ((NI) 4);
	}
	goto LA1;
	LA12: ;
	{
		if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 2))) == ((NI) 62))) goto LA15;
		result = ((NI) 5);
	}
	goto LA1;
	LA15: ;
	{
		if (!((NI)((NU64)(((NI) (((NU8)(s->data[i]))))) >> (NU64)(((NI) 1))) == ((NI) 126))) goto LA18;
		result = ((NI) 6);
	}
	goto LA1;
	LA18: ;
	{
		result = ((NI) 1);
	}
	LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI c) {
	NimStringDesc* result;
	NI i;
	result = 0;
	i = c;
	{
		if (!((NU64)(i) <= (NU64)(((NI) 127)))) goto LA3;
		result = mnewString(((NI) 1));
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) (i))));
	}
	goto LA1;
	LA3: ;
	{
		if (!((NU64)(i) <= (NU64)(((NI) 2047)))) goto LA6;
		result = mnewString(((NI) 2));
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) | ((NI) 192))))));
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128))))));
	}
	goto LA1;
	LA6: ;
	{
		if (!((NU64)(i) <= (NU64)(((NI) 65535)))) goto LA9;
		result = mnewString(((NI) 3));
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) | ((NI) 224))))));
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128))))));
	}
	goto LA1;
	LA9: ;
	{
		if (!((NU64)(i) <= (NU64)(((NI) 2097151)))) goto LA12;
		result = mnewString(((NI) 4));
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 18))) | ((NI) 240))))));
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128))))));
	}
	goto LA1;
	LA12: ;
	{
		if (!((NU64)(i) <= (NU64)(((NI) 67108863)))) goto LA15;
		result = mnewString(((NI) 5));
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 24))) | ((NI) 248))))));
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 18))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128))))));
	}
	goto LA1;
	LA15: ;
	{
		if (!((NU64)(i) <= (NU64)(((NI) 2147483647)))) goto LA18;
		result = mnewString(((NI) 6));
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 30))) | ((NI) 252))))));
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 24))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 18))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 12))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)((NI)((NU64)(i) >> (NU64)(((NI) 6))) & ((NI) 63)))) | ((NI) 128))))));
		result->data[((NI) 5)] = ((NIM_CHAR) (((NI) ((NI)(((NI) ((NI)(i & ((NI) 63)))) | ((NI) 128))))));
	}
	goto LA1;
	LA18: ;
	{
	}
	LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_147921)(NI rune) {
	NimStringDesc* result;
	result = 0;
	result = nuctoUTF8(rune);
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit)(void) {
}

