/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/stdlib_base64.o /data4/NimStuff/NimFinLib/nimcache/stdlib_base64.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
STRING_LITERAL(TMP289, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+"
"/", 64);

N_NIMCALL(NimStringDesc*, encode_226174)(NimStringDesc* s, NI linelen, NimStringDesc* newline) {
	NimStringDesc* result;
	NI total_226182;
	NI numlines_226184;
	NI i_226186;
	NI r_226188;
	NI currline_226190;
	result = 0;
	total_226182 = (NI)((NI)((NI)((s ? s->Sup.len : 0) + ((NI) 2)) / ((NI) 3)) * ((NI) 4));
	numlines_226184 = (NI)((NI)((NI)(total_226182 + linelen) - ((NI) 1)) / linelen);
	{
		if (!(((NI) 0) < numlines_226184)) goto LA3;
		total_226182 += (NI)((NI)(numlines_226184 - ((NI) 1)) * (newline ? newline->Sup.len : 0));
	}
	LA3: ;
	result = mnewString(((NI) (total_226182)));
	i_226186 = ((NI) 0);
	r_226188 = ((NI) 0);
	currline_226190 = ((NI) 0);
	{
		while (1) {
			NI a_226192;
			NI b_226194;
			NI c_226196;
			if (!(i_226186 < (NI)((s ? s->Sup.len : 0) - ((NI) 2)))) goto LA6;
			a_226192 = ((NU8)(s->data[i_226186]));
			b_226194 = ((NU8)(s->data[(NI)(i_226186 + ((NI) 1))]));
			c_226196 = ((NU8)(s->data[(NI)(i_226186 + ((NI) 2))]));
			result->data[r_226188] = ((NimStringDesc*) &TMP289)->data[(NI)((NU64)(((NI) (a_226192))) >> (NU64)(((NI) 2)))];
			result->data[(NI)(r_226188 + ((NI) 1))] = ((NimStringDesc*) &TMP289)->data[(NI)((NI)((NU64)(((NI) ((NI)(((NI) (a_226192)) & ((NI) 3))))) << (NU64)(((NI) 4))) | (NI)((NU64)((NI)(((NI) (b_226194)) & ((NI) 240))) >> (NU64)(((NI) 4))))];
			result->data[(NI)(r_226188 + ((NI) 2))] = ((NimStringDesc*) &TMP289)->data[(NI)((NI)((NU64)(((NI) ((NI)(((NI) (b_226194)) & ((NI) 15))))) << (NU64)(((NI) 2))) | (NI)((NU64)((NI)(((NI) (c_226196)) & ((NI) 192))) >> (NU64)(((NI) 6))))];
			result->data[(NI)(r_226188 + ((NI) 3))] = ((NimStringDesc*) &TMP289)->data[(NI)(((NI) (c_226196)) & ((NI) 63))];
			r_226188 += ((NI) 4);
			i_226186 += ((NI) 3);
			currline_226190 += ((NI) 4);
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = (linelen <= currline_226190);
				if (!(LOC9)) goto LA10;
				LOC9 = !((i_226186 == (NI)((s ? s->Sup.len : 0) - ((NI) 2))));
				LA10: ;
				if (!LOC9) goto LA11;
				{
					NIM_CHAR x_226198;
					NI i_226311;
					NI L_226313;
					x_226198 = 0;
					i_226311 = ((NI) 0);
					L_226313 = (newline ? newline->Sup.len : 0);
					{
						while (1) {
							if (!(i_226311 < L_226313)) goto LA15;
							x_226198 = newline->data[i_226311];
							result->data[r_226188] = x_226198;
							r_226188 += ((NI) 1);
							i_226311 += ((NI) 1);
						} LA15: ;
					}
				}
				currline_226190 = ((NI) 0);
			}
			LA11: ;
		} LA6: ;
	}
	{
		NI a_226200;
		NI b_226202;
		if (!(i_226186 < (NI)((s ? s->Sup.len : 0) - ((NI) 1)))) goto LA18;
		a_226200 = ((NU8)(s->data[i_226186]));
		b_226202 = ((NU8)(s->data[(NI)(i_226186 + ((NI) 1))]));
		result->data[r_226188] = ((NimStringDesc*) &TMP289)->data[(NI)((NU64)(((NI) (a_226200))) >> (NU64)(((NI) 2)))];
		result->data[(NI)(r_226188 + ((NI) 1))] = ((NimStringDesc*) &TMP289)->data[(NI)((NI)((NU64)(((NI) ((NI)(((NI) (a_226200)) & ((NI) 3))))) << (NU64)(((NI) 4))) | (NI)((NU64)((NI)(((NI) (b_226202)) & ((NI) 240))) >> (NU64)(((NI) 4))))];
		result->data[(NI)(r_226188 + ((NI) 2))] = ((NimStringDesc*) &TMP289)->data[(NI)((NU64)(((NI) ((NI)(((NI) (b_226202)) & ((NI) 15))))) << (NU64)(((NI) 2)))];
		result->data[(NI)(r_226188 + ((NI) 3))] = 61;
		{
			if (!!(((NI)(r_226188 + ((NI) 4)) == (result ? result->Sup.len : 0)))) goto LA22;
			result = setLengthStr(result, ((NI) ((NI)(r_226188 + ((NI) 4)))));
		}
		LA22: ;
	}
	goto LA16;
	LA18: ;
	{
		NI a_226204;
		if (!(i_226186 < (s ? s->Sup.len : 0))) goto LA25;
		a_226204 = ((NU8)(s->data[i_226186]));
		result->data[r_226188] = ((NimStringDesc*) &TMP289)->data[(NI)((NU64)(((NI) (a_226204))) >> (NU64)(((NI) 2)))];
		result->data[(NI)(r_226188 + ((NI) 1))] = ((NimStringDesc*) &TMP289)->data[(NI)((NU64)(((NI) ((NI)(((NI) (a_226204)) & ((NI) 3))))) << (NU64)(((NI) 4)))];
		result->data[(NI)(r_226188 + ((NI) 2))] = 61;
		result->data[(NI)(r_226188 + ((NI) 3))] = 61;
		{
			if (!!(((NI)(r_226188 + ((NI) 4)) == (result ? result->Sup.len : 0)))) goto LA29;
			result = setLengthStr(result, ((NI) ((NI)(r_226188 + ((NI) 4)))));
		}
		LA29: ;
	}
	goto LA16;
	LA25: ;
	{
	}
	LA16: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit)(void) {
}

