/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/stdlib_times.o /data4/NimStuff/NimFinLib/nimcache/stdlib_times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <time.h>

#include <sys/select.h>

#include <string.h>

#include <sys/time.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Timeinfo100408 Timeinfo100408;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY100570 TY100570;
typedef struct Slice83964 Slice83964;
typedef struct Valueerror3449 Valueerror3449;
typedef struct Exception Exception;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Timeinfo100408  {
  TNimObject Sup;
NI second;
NI minute;
NI hour;
NI monthday;
NU8 month;
NI year;
NU8 weekday;
NI yearday;
NIM_BOOL isdst;
NimStringDesc* tzname;
NI timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY101054[7];
struct TY100570 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY101073[7];
struct  Slice83964  {
NI a;
NI b;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3449  {
  Exception Sup;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
N_NIMCALL(void, getlocaltime_100475)(time_t t, Timeinfo100408* Result);
N_NIMCALL(void, tmtotimeinfo_101048)(struct tm* tm, NIM_BOOL local, Timeinfo100408* Result);
N_NIMCALL(void, gettzname_100568)(TY100570* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_100604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(time_t, gettime_100470)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_101068)(Timeinfo100408* t);
N_NIMCALL(void, parsetoken_102460)(Timeinfo100408* info, NimStringDesc* token, NimStringDesc* value, NI* j);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_83957)(NimStringDesc* s, Slice83964 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_74843, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice83964, HEX2EHEX2E_102273)(NI a, NI b);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(time_t, timeinfototime_100487)(Timeinfo100408* timeinfo);
NIM_CONST TY101054 weekdays_101053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
STRING_LITERAL(TMP234, "UTC", 3);
NIM_CONST TY101073 weekdays_101072 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP576, "", 0);
STRING_LITERAL(TMP577, "d", 1);
STRING_LITERAL(TMP578, "dd", 2);
STRING_LITERAL(TMP579, "ddd", 3);
STRING_LITERAL(TMP580, "dddd", 4);
STRING_LITERAL(TMP581, "h", 1);
STRING_LITERAL(TMP582, "H", 1);
STRING_LITERAL(TMP583, "hh", 2);
STRING_LITERAL(TMP584, "HH", 2);
STRING_LITERAL(TMP585, "m", 1);
STRING_LITERAL(TMP586, "mm", 2);
STRING_LITERAL(TMP587, "M", 1);
STRING_LITERAL(TMP588, "MM", 2);
STRING_LITERAL(TMP589, "MMM", 3);
STRING_LITERAL(TMP590, "MMMM", 4);
STRING_LITERAL(TMP591, "s", 1);
STRING_LITERAL(TMP592, "ss", 2);
STRING_LITERAL(TMP593, "t", 1);
STRING_LITERAL(TMP594, "tt", 2);
STRING_LITERAL(TMP595, "yy", 2);
STRING_LITERAL(TMP596, "yyyy", 4);
STRING_LITERAL(TMP597, "z", 1);
STRING_LITERAL(TMP598, "zz", 2);
STRING_LITERAL(TMP599, "zzz", 3);
STRING_LITERAL(TMP600, "ZZZ", 3);
STRING_LITERAL(TMP601, "sun", 3);
STRING_LITERAL(TMP602, "mon", 3);
STRING_LITERAL(TMP603, "tue", 3);
STRING_LITERAL(TMP604, "wed", 3);
STRING_LITERAL(TMP605, "thu", 3);
STRING_LITERAL(TMP606, "fri", 3);
STRING_LITERAL(TMP607, "sat", 3);
STRING_LITERAL(TMP608, "invalid day of week ", 20);
STRING_LITERAL(TMP609, "sunday", 6);
STRING_LITERAL(TMP610, "monday", 6);
STRING_LITERAL(TMP611, "tuesday", 7);
STRING_LITERAL(TMP612, "wednesday", 9);
STRING_LITERAL(TMP613, "thursday", 8);
STRING_LITERAL(TMP614, "friday", 6);
STRING_LITERAL(TMP615, "saturday", 8);
STRING_LITERAL(TMP616, "jan", 3);
STRING_LITERAL(TMP617, "feb", 3);
STRING_LITERAL(TMP618, "mar", 3);
STRING_LITERAL(TMP619, "apr", 3);
STRING_LITERAL(TMP620, "may", 3);
STRING_LITERAL(TMP621, "jun", 3);
STRING_LITERAL(TMP622, "jul", 3);
STRING_LITERAL(TMP623, "aug", 3);
STRING_LITERAL(TMP624, "sep", 3);
STRING_LITERAL(TMP625, "oct", 3);
STRING_LITERAL(TMP626, "nov", 3);
STRING_LITERAL(TMP627, "dec", 3);
STRING_LITERAL(TMP628, "invalid month", 13);
STRING_LITERAL(TMP629, "january", 7);
STRING_LITERAL(TMP630, "february", 8);
STRING_LITERAL(TMP631, "march", 5);
STRING_LITERAL(TMP632, "april", 5);
STRING_LITERAL(TMP633, "june", 4);
STRING_LITERAL(TMP634, "july", 4);
STRING_LITERAL(TMP635, "august", 6);
STRING_LITERAL(TMP636, "september", 9);
STRING_LITERAL(TMP637, "october", 7);
STRING_LITERAL(TMP638, "november", 8);
STRING_LITERAL(TMP639, "december", 8);
STRING_LITERAL(TMP640, "PM", 2);
STRING_LITERAL(TMP641, "Sign for timezone ", 18);
extern TNimType NTI3411; /* RootObj */
TNimType NTI100408; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI100411; /* range 0..61(int) */
TNimType NTI100414; /* range 0..59(int) */
TNimType NTI100416; /* range 0..23(int) */
TNimType NTI100419; /* range 1..31(int) */
TNimType NTI100006; /* Month */
TNimType NTI100008; /* WeekDay */
TNimType NTI100425; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
TNimType NTI100570; /* tuple[nonDST: string, DST: string] */
extern TNimType NTI21228; /* ref ValueError */
extern TNimType NTI3449; /* ValueError */
extern Gcheap46616 gch_46648;

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	struct timeval a;
	result = 0;
	memset((void*)(&a), 0, sizeof(a));
	gettimeofday((&a), NIM_NIL);
	result = ((NF)(((double) (a.tv_sec))) + (NF)(((NF)(((double) (a.tv_usec))) * (NF)(9.9999999999999995e-07))));
	return result;
}

N_NIMCALL(void, gettzname_100568)(TY100570* Result) {
{	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(((NI) 0))- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(((NI) 1))- 0]));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_100604)(void) {
	NI result;
{	result = 0;
	result = timezone;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_101048)(struct tm* tm, NIM_BOOL local, Timeinfo100408* Result) {
	Timeinfo100408 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI100408);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI100408);
	LOC1.second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.month = ((NU8) ((*tm).tm_mon));
	LOC1.year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.weekday = weekdays_101053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY100570 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_100568((&LOC10));
			LOC1.tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY100570 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_100568((&LOC12));
			LOC1.tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.tzname = copyString(((NimStringDesc*) &TMP234));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.timezone = gettimezone_100604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.timezone = ((NI) 0);
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI100408));
}

N_NIMCALL(void, getlocaltime_100475)(time_t t, Timeinfo100408* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime((&a));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI100408));
	(*Result).Sup.m_type = (&NTI100408);
	tmtotimeinfo_101048((&(*LOC1)), NIM_TRUE, Result);
}

N_NIMCALL(time_t, gettime_100470)(void) {
	time_t result;
{	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	Timeinfo100408 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI100408);
	LOC1 = 0;
	LOC1 = gettime_100470();
	chckNil((void*)(&ti));
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI100408);
	getlocaltime_100475(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(ti.year);
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI)(((NI) (ti.month)) + ((NI) 1)))), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.monthday)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_100630)(NI year) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(((NI) ((NI)(year % ((NI) 400)))) == ((NI) 0))) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 100)))) == ((NI) 0))) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 4)))) == ((NI) 0))) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NF, toseconds_100510)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(struct tm, timeinfototm_101068)(Timeinfo100408* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).second));
	result.tm_min = ((int) ((*t).minute));
	result.tm_hour = ((int) ((*t).hour));
	result.tm_mday = ((int) ((*t).monthday));
	result.tm_mon = ((int) ((*t).month));
	result.tm_year = ((int) ((NI)((*t).year - ((NI) 1900))));
	result.tm_wday = ((int) (weekdays_101072[((*t).weekday)- 0]));
	result.tm_yday = ((int) ((*t).yearday));
	LOC1 = 0;
	{
		if (!(*t).isdst) goto LA4;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(time_t, timeinfototime_100487)(Timeinfo100408* timeinfo) {
	time_t result;
	Timeinfo100408 ctimeinfo;
	struct tm LOC1;
{	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI100408);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI100408));
	LOC1 = timeinfototm_101068((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_83957)(NimStringDesc* s, Slice83964 x) {
	NimStringDesc* result;
	result = 0;
	result = copyStrLast(s, x.a, x.b);
	return result;
}

static N_INLINE(Slice83964, HEX2EHEX2E_102273)(NI a, NI b) {
	Slice83964 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell44747* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_48246(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell44747* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_48246((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_49804(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, parsetoken_102460)(Timeinfo100408* info, NimStringDesc* token, NimStringDesc* value, NI* j) {
	NI sv;
	sv = 0;
	switch (hashString(token) & 31) {
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP586))) goto LA8;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP577))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP594))) goto LA16;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP600))) goto LA22;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP581))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP587))) goto LA9;
if (eqStrings(token, ((NimStringDesc*) &TMP588))) goto LA10;
if (eqStrings(token, ((NimStringDesc*) &TMP592))) goto LA14;
if (eqStrings(token, ((NimStringDesc*) &TMP595))) goto LA17;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP589))) goto LA11;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP599))) goto LA21;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP580))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP593))) goto LA15;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP578))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP585))) goto LA7;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP591))) goto LA13;
if (eqStrings(token, ((NimStringDesc*) &TMP598))) goto LA20;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP582))) goto LA5;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP584))) goto LA6;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP590))) goto LA12;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP597))) goto LA19;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP579))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP583))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP596))) goto LA18;
break;
	}
	goto LA23;
	LA1: ;
	{
		NI pd;
		Slice83964 LOC26;
		NimStringDesc* LOC27;
		LOC26 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC27 = 0;
		LOC27 = HEX5BHEX5D_83957(value, LOC26);
		pd = npuParseInt(LOC27, (&sv), ((NI) 0));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA2: ;
	{
		Slice83964 LOC29;
		NimStringDesc* LOC30;
		NI LOC31;
		LOC29 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC30 = 0;
		LOC30 = HEX5BHEX5D_83957(value, LOC29);
		LOC31 = 0;
		LOC31 = nsuParseInt(LOC30);
		(*info).monthday = ((NI) (LOC31));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA3: ;
	{
		Slice83964 LOC33;
		NimStringDesc* LOC34;
		NimStringDesc* LOC35;
		LOC33 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 2)));
		LOC34 = 0;
		LOC34 = HEX5BHEX5D_83957(value, LOC33);
		LOC35 = 0;
		LOC35 = nsuToLowerStr(LOC34);
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP601))) goto LA36;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP602))) goto LA37;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP603))) goto LA38;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP604))) goto LA39;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP605))) goto LA40;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP606))) goto LA41;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP607))) goto LA42;
		goto LA43;
		LA36: ;
		{
			(*info).weekday = ((NU8) 6);
		}
		goto LA44;
		LA37: ;
		{
			(*info).weekday = ((NU8) 0);
		}
		goto LA44;
		LA38: ;
		{
			(*info).weekday = ((NU8) 1);
		}
		goto LA44;
		LA39: ;
		{
			(*info).weekday = ((NU8) 2);
		}
		goto LA44;
		LA40: ;
		{
			(*info).weekday = ((NU8) 3);
		}
		goto LA44;
		LA41: ;
		{
			(*info).weekday = ((NU8) 4);
		}
		goto LA44;
		LA42: ;
		{
			(*info).weekday = ((NU8) 5);
		}
		goto LA44;
		LA43: ;
		{
			Valueerror3449* e_102521;
			NimStringDesc* LOC53;
			e_102521 = 0;
			e_102521 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_102521).Sup.Sup.m_type = (&NTI3449);
			LOC53 = 0;
			LOC53 = (*e_102521).Sup.message; (*e_102521).Sup.message = copyStringRC1(((NimStringDesc*) &TMP608));
			if (LOC53) nimGCunrefNoCycle(LOC53);
			raiseException((Exception*)e_102521, "ValueError");
		}
		LA44: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA4: ;
	{
		{
			NIM_BOOL LOC57;
			Slice83964 LOC59;
			NimStringDesc* LOC60;
			NI LOC61;
			LOC57 = 0;
			LOC57 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC57)) goto LA58;
			LOC59 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 5)));
			LOC60 = 0;
			LOC60 = HEX5BHEX5D_83957(value, LOC59);
			LOC61 = 0;
			LOC61 = nsuCmpIgnoreCase(LOC60, ((NimStringDesc*) &TMP609));
			LOC57 = (LOC61 == ((NI) 0));
			LA58: ;
			if (!LOC57) goto LA62;
			(*info).weekday = ((NU8) 6);
			(*j) += ((NI) 6);
		}
		goto LA55;
		LA62: ;
		{
			NIM_BOOL LOC65;
			Slice83964 LOC67;
			NimStringDesc* LOC68;
			NI LOC69;
			LOC65 = 0;
			LOC65 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC65)) goto LA66;
			LOC67 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 5)));
			LOC68 = 0;
			LOC68 = HEX5BHEX5D_83957(value, LOC67);
			LOC69 = 0;
			LOC69 = nsuCmpIgnoreCase(LOC68, ((NimStringDesc*) &TMP610));
			LOC65 = (LOC69 == ((NI) 0));
			LA66: ;
			if (!LOC65) goto LA70;
			(*info).weekday = ((NU8) 0);
			(*j) += ((NI) 6);
		}
		goto LA55;
		LA70: ;
		{
			NIM_BOOL LOC73;
			Slice83964 LOC75;
			NimStringDesc* LOC76;
			NI LOC77;
			LOC73 = 0;
			LOC73 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC73)) goto LA74;
			LOC75 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 6)));
			LOC76 = 0;
			LOC76 = HEX5BHEX5D_83957(value, LOC75);
			LOC77 = 0;
			LOC77 = nsuCmpIgnoreCase(LOC76, ((NimStringDesc*) &TMP611));
			LOC73 = (LOC77 == ((NI) 0));
			LA74: ;
			if (!LOC73) goto LA78;
			(*info).weekday = ((NU8) 1);
			(*j) += ((NI) 7);
		}
		goto LA55;
		LA78: ;
		{
			NIM_BOOL LOC81;
			Slice83964 LOC83;
			NimStringDesc* LOC84;
			NI LOC85;
			LOC81 = 0;
			LOC81 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC81)) goto LA82;
			LOC83 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 8)));
			LOC84 = 0;
			LOC84 = HEX5BHEX5D_83957(value, LOC83);
			LOC85 = 0;
			LOC85 = nsuCmpIgnoreCase(LOC84, ((NimStringDesc*) &TMP612));
			LOC81 = (LOC85 == ((NI) 0));
			LA82: ;
			if (!LOC81) goto LA86;
			(*info).weekday = ((NU8) 2);
			(*j) += ((NI) 9);
		}
		goto LA55;
		LA86: ;
		{
			NIM_BOOL LOC89;
			Slice83964 LOC91;
			NimStringDesc* LOC92;
			NI LOC93;
			LOC89 = 0;
			LOC89 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC89)) goto LA90;
			LOC91 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 7)));
			LOC92 = 0;
			LOC92 = HEX5BHEX5D_83957(value, LOC91);
			LOC93 = 0;
			LOC93 = nsuCmpIgnoreCase(LOC92, ((NimStringDesc*) &TMP613));
			LOC89 = (LOC93 == ((NI) 0));
			LA90: ;
			if (!LOC89) goto LA94;
			(*info).weekday = ((NU8) 3);
			(*j) += ((NI) 8);
		}
		goto LA55;
		LA94: ;
		{
			NIM_BOOL LOC97;
			Slice83964 LOC99;
			NimStringDesc* LOC100;
			NI LOC101;
			LOC97 = 0;
			LOC97 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC97)) goto LA98;
			LOC99 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 5)));
			LOC100 = 0;
			LOC100 = HEX5BHEX5D_83957(value, LOC99);
			LOC101 = 0;
			LOC101 = nsuCmpIgnoreCase(LOC100, ((NimStringDesc*) &TMP614));
			LOC97 = (LOC101 == ((NI) 0));
			LA98: ;
			if (!LOC97) goto LA102;
			(*info).weekday = ((NU8) 4);
			(*j) += ((NI) 6);
		}
		goto LA55;
		LA102: ;
		{
			NIM_BOOL LOC105;
			Slice83964 LOC107;
			NimStringDesc* LOC108;
			NI LOC109;
			LOC105 = 0;
			LOC105 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC105)) goto LA106;
			LOC107 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 7)));
			LOC108 = 0;
			LOC108 = HEX5BHEX5D_83957(value, LOC107);
			LOC109 = 0;
			LOC109 = nsuCmpIgnoreCase(LOC108, ((NimStringDesc*) &TMP615));
			LOC105 = (LOC109 == ((NI) 0));
			LA106: ;
			if (!LOC105) goto LA110;
			(*info).weekday = ((NU8) 5);
			(*j) += ((NI) 8);
		}
		goto LA55;
		LA110: ;
		{
			Valueerror3449* e_102675;
			NimStringDesc* LOC113;
			e_102675 = 0;
			e_102675 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_102675).Sup.Sup.m_type = (&NTI3449);
			LOC113 = 0;
			LOC113 = (*e_102675).Sup.message; (*e_102675).Sup.message = copyStringRC1(((NimStringDesc*) &TMP608));
			if (LOC113) nimGCunrefNoCycle(LOC113);
			raiseException((Exception*)e_102675, "ValueError");
		}
		LA55: ;
	}
	goto LA24;
	LA5: ;
	{
		NI pd;
		Slice83964 LOC115;
		NimStringDesc* LOC116;
		LOC115 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC116 = 0;
		LOC116 = HEX5BHEX5D_83957(value, LOC115);
		pd = npuParseInt(LOC116, (&sv), ((NI) 0));
		(*info).hour = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA6: ;
	{
		Slice83964 LOC118;
		NimStringDesc* LOC119;
		NI LOC120;
		LOC118 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC119 = 0;
		LOC119 = HEX5BHEX5D_83957(value, LOC118);
		LOC120 = 0;
		LOC120 = nsuParseInt(LOC119);
		(*info).hour = ((NI) (LOC120));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA7: ;
	{
		NI pd;
		Slice83964 LOC122;
		NimStringDesc* LOC123;
		LOC122 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_83957(value, LOC122);
		pd = npuParseInt(LOC123, (&sv), ((NI) 0));
		(*info).minute = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA8: ;
	{
		Slice83964 LOC125;
		NimStringDesc* LOC126;
		NI LOC127;
		LOC125 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC126 = 0;
		LOC126 = HEX5BHEX5D_83957(value, LOC125);
		LOC127 = 0;
		LOC127 = nsuParseInt(LOC126);
		(*info).minute = ((NI) (LOC127));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA9: ;
	{
		NI pd;
		Slice83964 LOC129;
		NimStringDesc* LOC130;
		LOC129 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC130 = 0;
		LOC130 = HEX5BHEX5D_83957(value, LOC129);
		pd = npuParseInt(LOC130, (&sv), ((NI) 0));
		(*info).month = ((NU8) ((NI)(sv - ((NI) 1))));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA10: ;
	{
		NI month;
		Slice83964 LOC132;
		NimStringDesc* LOC133;
		LOC132 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC133 = 0;
		LOC133 = HEX5BHEX5D_83957(value, LOC132);
		month = nsuParseInt(LOC133);
		(*j) += ((NI) 2);
		(*info).month = ((NU8) ((NI)(month - ((NI) 1))));
	}
	goto LA24;
	LA11: ;
	{
		Slice83964 LOC135;
		NimStringDesc* LOC136;
		NimStringDesc* LOC137;
		LOC135 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 2)));
		LOC136 = 0;
		LOC136 = HEX5BHEX5D_83957(value, LOC135);
		LOC137 = 0;
		LOC137 = nsuToLowerStr(LOC136);
		switch (hashString(LOC137) & 15) {
		case 0: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP617))) goto LA139;
break;
		case 3: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP618))) goto LA140;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP620))) goto LA142;
break;
		case 5: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP627))) goto LA149;
break;
		case 8: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP616))) goto LA138;
break;
		case 9: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP623))) goto LA145;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP624))) goto LA146;
break;
		case 11: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP621))) goto LA143;
break;
		case 14: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP619))) goto LA141;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP626))) goto LA148;
break;
		case 15: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP622))) goto LA144;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP625))) goto LA147;
break;
		}
		goto LA150;
		LA138: ;
		{
			(*info).month = ((NU8) 0);
		}
		goto LA151;
		LA139: ;
		{
			(*info).month = ((NU8) 1);
		}
		goto LA151;
		LA140: ;
		{
			(*info).month = ((NU8) 2);
		}
		goto LA151;
		LA141: ;
		{
			(*info).month = ((NU8) 3);
		}
		goto LA151;
		LA142: ;
		{
			(*info).month = ((NU8) 4);
		}
		goto LA151;
		LA143: ;
		{
			(*info).month = ((NU8) 5);
		}
		goto LA151;
		LA144: ;
		{
			(*info).month = ((NU8) 6);
		}
		goto LA151;
		LA145: ;
		{
			(*info).month = ((NU8) 7);
		}
		goto LA151;
		LA146: ;
		{
			(*info).month = ((NU8) 8);
		}
		goto LA151;
		LA147: ;
		{
			(*info).month = ((NU8) 9);
		}
		goto LA151;
		LA148: ;
		{
			(*info).month = ((NU8) 10);
		}
		goto LA151;
		LA149: ;
		{
			(*info).month = ((NU8) 11);
		}
		goto LA151;
		LA150: ;
		{
			Valueerror3449* e_102818;
			NimStringDesc* LOC165;
			e_102818 = 0;
			e_102818 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_102818).Sup.Sup.m_type = (&NTI3449);
			LOC165 = 0;
			LOC165 = (*e_102818).Sup.message; (*e_102818).Sup.message = copyStringRC1(((NimStringDesc*) &TMP628));
			if (LOC165) nimGCunrefNoCycle(LOC165);
			raiseException((Exception*)e_102818, "ValueError");
		}
		LA151: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA12: ;
	{
		{
			NIM_BOOL LOC169;
			Slice83964 LOC171;
			NimStringDesc* LOC172;
			NI LOC173;
			LOC169 = 0;
			LOC169 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC169)) goto LA170;
			LOC171 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 6)));
			LOC172 = 0;
			LOC172 = HEX5BHEX5D_83957(value, LOC171);
			LOC173 = 0;
			LOC173 = nsuCmpIgnoreCase(LOC172, ((NimStringDesc*) &TMP629));
			LOC169 = (LOC173 == ((NI) 0));
			LA170: ;
			if (!LOC169) goto LA174;
			(*info).month = ((NU8) 0);
			(*j) += ((NI) 7);
		}
		goto LA167;
		LA174: ;
		{
			NIM_BOOL LOC177;
			Slice83964 LOC179;
			NimStringDesc* LOC180;
			NI LOC181;
			LOC177 = 0;
			LOC177 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC177)) goto LA178;
			LOC179 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 7)));
			LOC180 = 0;
			LOC180 = HEX5BHEX5D_83957(value, LOC179);
			LOC181 = 0;
			LOC181 = nsuCmpIgnoreCase(LOC180, ((NimStringDesc*) &TMP630));
			LOC177 = (LOC181 == ((NI) 0));
			LA178: ;
			if (!LOC177) goto LA182;
			(*info).month = ((NU8) 1);
			(*j) += ((NI) 8);
		}
		goto LA167;
		LA182: ;
		{
			NIM_BOOL LOC185;
			Slice83964 LOC187;
			NimStringDesc* LOC188;
			NI LOC189;
			LOC185 = 0;
			LOC185 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC185)) goto LA186;
			LOC187 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 4)));
			LOC188 = 0;
			LOC188 = HEX5BHEX5D_83957(value, LOC187);
			LOC189 = 0;
			LOC189 = nsuCmpIgnoreCase(LOC188, ((NimStringDesc*) &TMP631));
			LOC185 = (LOC189 == ((NI) 0));
			LA186: ;
			if (!LOC185) goto LA190;
			(*info).month = ((NU8) 2);
			(*j) += ((NI) 5);
		}
		goto LA167;
		LA190: ;
		{
			NIM_BOOL LOC193;
			Slice83964 LOC195;
			NimStringDesc* LOC196;
			NI LOC197;
			LOC193 = 0;
			LOC193 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC193)) goto LA194;
			LOC195 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 4)));
			LOC196 = 0;
			LOC196 = HEX5BHEX5D_83957(value, LOC195);
			LOC197 = 0;
			LOC197 = nsuCmpIgnoreCase(LOC196, ((NimStringDesc*) &TMP632));
			LOC193 = (LOC197 == ((NI) 0));
			LA194: ;
			if (!LOC193) goto LA198;
			(*info).month = ((NU8) 3);
			(*j) += ((NI) 5);
		}
		goto LA167;
		LA198: ;
		{
			NIM_BOOL LOC201;
			Slice83964 LOC203;
			NimStringDesc* LOC204;
			NI LOC205;
			LOC201 = 0;
			LOC201 = ((NI)((*j) + ((NI) 3)) <= (value ? value->Sup.len : 0));
			if (!(LOC201)) goto LA202;
			LOC203 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 2)));
			LOC204 = 0;
			LOC204 = HEX5BHEX5D_83957(value, LOC203);
			LOC205 = 0;
			LOC205 = nsuCmpIgnoreCase(LOC204, ((NimStringDesc*) &TMP620));
			LOC201 = (LOC205 == ((NI) 0));
			LA202: ;
			if (!LOC201) goto LA206;
			(*info).month = ((NU8) 4);
			(*j) += ((NI) 3);
		}
		goto LA167;
		LA206: ;
		{
			NIM_BOOL LOC209;
			Slice83964 LOC211;
			NimStringDesc* LOC212;
			NI LOC213;
			LOC209 = 0;
			LOC209 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC209)) goto LA210;
			LOC211 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 3)));
			LOC212 = 0;
			LOC212 = HEX5BHEX5D_83957(value, LOC211);
			LOC213 = 0;
			LOC213 = nsuCmpIgnoreCase(LOC212, ((NimStringDesc*) &TMP633));
			LOC209 = (LOC213 == ((NI) 0));
			LA210: ;
			if (!LOC209) goto LA214;
			(*info).month = ((NU8) 5);
			(*j) += ((NI) 4);
		}
		goto LA167;
		LA214: ;
		{
			NIM_BOOL LOC217;
			Slice83964 LOC219;
			NimStringDesc* LOC220;
			NI LOC221;
			LOC217 = 0;
			LOC217 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC217)) goto LA218;
			LOC219 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 3)));
			LOC220 = 0;
			LOC220 = HEX5BHEX5D_83957(value, LOC219);
			LOC221 = 0;
			LOC221 = nsuCmpIgnoreCase(LOC220, ((NimStringDesc*) &TMP634));
			LOC217 = (LOC221 == ((NI) 0));
			LA218: ;
			if (!LOC217) goto LA222;
			(*info).month = ((NU8) 6);
			(*j) += ((NI) 4);
		}
		goto LA167;
		LA222: ;
		{
			NIM_BOOL LOC225;
			Slice83964 LOC227;
			NimStringDesc* LOC228;
			NI LOC229;
			LOC225 = 0;
			LOC225 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC225)) goto LA226;
			LOC227 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 5)));
			LOC228 = 0;
			LOC228 = HEX5BHEX5D_83957(value, LOC227);
			LOC229 = 0;
			LOC229 = nsuCmpIgnoreCase(LOC228, ((NimStringDesc*) &TMP635));
			LOC225 = (LOC229 == ((NI) 0));
			LA226: ;
			if (!LOC225) goto LA230;
			(*info).month = ((NU8) 7);
			(*j) += ((NI) 6);
		}
		goto LA167;
		LA230: ;
		{
			NIM_BOOL LOC233;
			Slice83964 LOC235;
			NimStringDesc* LOC236;
			NI LOC237;
			LOC233 = 0;
			LOC233 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC233)) goto LA234;
			LOC235 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 8)));
			LOC236 = 0;
			LOC236 = HEX5BHEX5D_83957(value, LOC235);
			LOC237 = 0;
			LOC237 = nsuCmpIgnoreCase(LOC236, ((NimStringDesc*) &TMP636));
			LOC233 = (LOC237 == ((NI) 0));
			LA234: ;
			if (!LOC233) goto LA238;
			(*info).month = ((NU8) 8);
			(*j) += ((NI) 9);
		}
		goto LA167;
		LA238: ;
		{
			NIM_BOOL LOC241;
			Slice83964 LOC243;
			NimStringDesc* LOC244;
			NI LOC245;
			LOC241 = 0;
			LOC241 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC241)) goto LA242;
			LOC243 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 6)));
			LOC244 = 0;
			LOC244 = HEX5BHEX5D_83957(value, LOC243);
			LOC245 = 0;
			LOC245 = nsuCmpIgnoreCase(LOC244, ((NimStringDesc*) &TMP637));
			LOC241 = (LOC245 == ((NI) 0));
			LA242: ;
			if (!LOC241) goto LA246;
			(*info).month = ((NU8) 9);
			(*j) += ((NI) 7);
		}
		goto LA167;
		LA246: ;
		{
			NIM_BOOL LOC249;
			Slice83964 LOC251;
			NimStringDesc* LOC252;
			NI LOC253;
			LOC249 = 0;
			LOC249 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC249)) goto LA250;
			LOC251 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 7)));
			LOC252 = 0;
			LOC252 = HEX5BHEX5D_83957(value, LOC251);
			LOC253 = 0;
			LOC253 = nsuCmpIgnoreCase(LOC252, ((NimStringDesc*) &TMP638));
			LOC249 = (LOC253 == ((NI) 0));
			LA250: ;
			if (!LOC249) goto LA254;
			(*info).month = ((NU8) 10);
			(*j) += ((NI) 8);
		}
		goto LA167;
		LA254: ;
		{
			NIM_BOOL LOC257;
			Slice83964 LOC259;
			NimStringDesc* LOC260;
			NI LOC261;
			LOC257 = 0;
			LOC257 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC257)) goto LA258;
			LOC259 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 7)));
			LOC260 = 0;
			LOC260 = HEX5BHEX5D_83957(value, LOC259);
			LOC261 = 0;
			LOC261 = nsuCmpIgnoreCase(LOC260, ((NimStringDesc*) &TMP639));
			LOC257 = (LOC261 == ((NI) 0));
			LA258: ;
			if (!LOC257) goto LA262;
			(*info).month = ((NU8) 11);
			(*j) += ((NI) 8);
		}
		goto LA167;
		LA262: ;
		{
			Valueerror3449* e_103067;
			NimStringDesc* LOC265;
			e_103067 = 0;
			e_103067 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_103067).Sup.Sup.m_type = (&NTI3449);
			LOC265 = 0;
			LOC265 = (*e_103067).Sup.message; (*e_103067).Sup.message = copyStringRC1(((NimStringDesc*) &TMP628));
			if (LOC265) nimGCunrefNoCycle(LOC265);
			raiseException((Exception*)e_103067, "ValueError");
		}
		LA167: ;
	}
	goto LA24;
	LA13: ;
	{
		NI pd;
		Slice83964 LOC267;
		NimStringDesc* LOC268;
		LOC267 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC268 = 0;
		LOC268 = HEX5BHEX5D_83957(value, LOC267);
		pd = npuParseInt(LOC268, (&sv), ((NI) 0));
		(*info).second = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA14: ;
	{
		Slice83964 LOC270;
		NimStringDesc* LOC271;
		NI LOC272;
		LOC270 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC271 = 0;
		LOC271 = HEX5BHEX5D_83957(value, LOC270);
		LOC272 = 0;
		LOC272 = nsuParseInt(LOC271);
		(*info).second = ((NI) (LOC272));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA15: ;
	{
		{
			NIM_BOOL LOC276;
			NIM_BOOL LOC277;
			LOC276 = 0;
			LOC277 = 0;
			LOC277 = ((NU8)(value->data[(*j)]) == (NU8)(80));
			if (!(LOC277)) goto LA278;
			LOC277 = (((NI) 0) < ((NI) ((*info).hour)));
			LA278: ;
			LOC276 = LOC277;
			if (!(LOC276)) goto LA279;
			LOC276 = (((NI) ((*info).hour)) < ((NI) 12));
			LA279: ;
			if (!LOC276) goto LA280;
			(*info).hour += ((NI) 12);
		}
		LA280: ;
		(*j) += ((NI) 1);
	}
	goto LA24;
	LA16: ;
	{
		{
			NIM_BOOL LOC285;
			NIM_BOOL LOC286;
			Slice83964 LOC287;
			NimStringDesc* LOC288;
			LOC285 = 0;
			LOC286 = 0;
			LOC287 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
			LOC288 = 0;
			LOC288 = HEX5BHEX5D_83957(value, LOC287);
			LOC286 = eqStrings(LOC288, ((NimStringDesc*) &TMP640));
			if (!(LOC286)) goto LA289;
			LOC286 = (((NI) 0) < ((NI) ((*info).hour)));
			LA289: ;
			LOC285 = LOC286;
			if (!(LOC285)) goto LA290;
			LOC285 = (((NI) ((*info).hour)) < ((NI) 12));
			LA290: ;
			if (!LOC285) goto LA291;
			(*info).hour += ((NI) 12);
		}
		LA291: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA17: ;
	{
		NI year;
		Slice83964 LOC294;
		NimStringDesc* LOC295;
		NI thiscen;
		time_t LOC296;
		Timeinfo100408 LOC297;
		LOC294 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 1)));
		LOC295 = 0;
		LOC295 = HEX5BHEX5D_83957(value, LOC294);
		year = nsuParseInt(LOC295);
		LOC296 = 0;
		LOC296 = gettime_100470();
		memset((void*)(&LOC297), 0, sizeof(LOC297));
		LOC297.Sup.m_type = (&NTI100408);
		getlocaltime_100475(LOC296, (&LOC297));
		thiscen = (NI)(LOC297.year / ((NI) 100));
		(*info).year = (NI)((NI)(thiscen * ((NI) 100)) + year);
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA18: ;
	{
		Slice83964 LOC299;
		NimStringDesc* LOC300;
		LOC299 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 3)));
		LOC300 = 0;
		LOC300 = HEX5BHEX5D_83957(value, LOC299);
		(*info).year = nsuParseInt(LOC300);
		(*j) += ((NI) 4);
	}
	goto LA24;
	LA19: ;
	{
		{
			NimStringDesc* LOC306;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA304;
			LOC306 = 0;
			LOC306 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			(*info).timezone = nsuParseInt(LOC306);
		}
		goto LA302;
		LA304: ;
		{
			NimStringDesc* LOC310;
			NI LOC311;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA308;
			LOC310 = 0;
			LOC310 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			LOC311 = 0;
			LOC311 = nsuParseInt(LOC310);
			(*info).timezone = (NI)(((NI) 0) - LOC311);
		}
		goto LA302;
		LA308: ;
		{
			Valueerror3449* e_103207;
			NimStringDesc* LOC313;
			e_103207 = 0;
			e_103207 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_103207).Sup.Sup.m_type = (&NTI3449);
			LOC313 = 0;
			LOC313 = rawNewString(19);
appendString(LOC313, ((NimStringDesc*) &TMP641));
appendChar(LOC313, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_103207).Sup.message), LOC313);
			raiseException((Exception*)e_103207, "ValueError");
		}
		LA302: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA20: ;
	{
		{
			Slice83964 LOC319;
			NimStringDesc* LOC320;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA317;
			LOC319 = HEX2EHEX2E_102273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC320 = 0;
			LOC320 = HEX5BHEX5D_83957(value, LOC319);
			(*info).timezone = nsuParseInt(LOC320);
		}
		goto LA315;
		LA317: ;
		{
			Slice83964 LOC324;
			NimStringDesc* LOC325;
			NI LOC326;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA322;
			LOC324 = HEX2EHEX2E_102273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC325 = 0;
			LOC325 = HEX5BHEX5D_83957(value, LOC324);
			LOC326 = 0;
			LOC326 = nsuParseInt(LOC325);
			(*info).timezone = (NI)(((NI) 0) - LOC326);
		}
		goto LA315;
		LA322: ;
		{
			Valueerror3449* e_103248;
			NimStringDesc* LOC328;
			e_103248 = 0;
			e_103248 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_103248).Sup.Sup.m_type = (&NTI3449);
			LOC328 = 0;
			LOC328 = rawNewString(19);
appendString(LOC328, ((NimStringDesc*) &TMP641));
appendChar(LOC328, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_103248).Sup.message), LOC328);
			raiseException((Exception*)e_103248, "ValueError");
		}
		LA315: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA21: ;
	{
		{
			Slice83964 LOC334;
			NimStringDesc* LOC335;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA332;
			LOC334 = HEX2EHEX2E_102273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC335 = 0;
			LOC335 = HEX5BHEX5D_83957(value, LOC334);
			(*info).timezone = nsuParseInt(LOC335);
		}
		goto LA330;
		LA332: ;
		{
			Slice83964 LOC339;
			NimStringDesc* LOC340;
			NI LOC341;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA337;
			LOC339 = HEX2EHEX2E_102273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC340 = 0;
			LOC340 = HEX5BHEX5D_83957(value, LOC339);
			LOC341 = 0;
			LOC341 = nsuParseInt(LOC340);
			(*info).timezone = (NI)(((NI) 0) - LOC341);
		}
		goto LA330;
		LA337: ;
		{
			Valueerror3449* e_103289;
			NimStringDesc* LOC343;
			e_103289 = 0;
			e_103289 = (Valueerror3449*) newObj((&NTI21228), sizeof(Valueerror3449));
			(*e_103289).Sup.Sup.m_type = (&NTI3449);
			LOC343 = 0;
			LOC343 = rawNewString(19);
appendString(LOC343, ((NimStringDesc*) &TMP641));
appendChar(LOC343, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_103289).Sup.message), LOC343);
			raiseException((Exception*)e_103289, "ValueError");
		}
		LA330: ;
		(*j) += ((NI) 6);
	}
	goto LA24;
	LA22: ;
	{
		Slice83964 LOC345;
		NimStringDesc* LOC346;
		LOC345 = HEX2EHEX2E_102273((*j), (NI)((*j) + ((NI) 2)));
		LOC346 = 0;
		LOC346 = HEX5BHEX5D_83957(value, LOC345);
		unsureAsgnRef((void**) (&(*info).tzname), nsuToUpperStr(LOC346));
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA23: ;
	{
		(*j) += (token ? token->Sup.len : 0);
	}
	LA24: ;
}

N_NIMCALL(void, parse_103350)(NimStringDesc* value, NimStringDesc* layout, Timeinfo100408* Result) {
	NI i;
	NI j;
	NimStringDesc* token;
	Timeinfo100408 info;
	time_t LOC1;
	time_t LOC30;
	Timeinfo100408 LOC31;
{	i = ((NI) 0);
	j = ((NI) 0);
	token = copyString(((NimStringDesc*) &TMP576));
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI100408);
	LOC1 = 0;
	LOC1 = gettime_100470();
	chckNil((void*)(&info));
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI100408);
	getlocaltime_100475(LOC1, (&info));
	info.hour = ((NI) 0);
	info.minute = ((NI) 0);
	info.second = ((NI) 0);
	{
		while (1) {
			switch (((NU8)(layout->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				{
					if (!(((NI) 0) < (token ? token->Sup.len : 0))) goto LA7;
					parsetoken_102460((&info), token, value, (&j));
				}
				LA7: ;
				token = copyString(((NimStringDesc*) &TMP576));
				{
					if (!((NU8)(layout->data[i]) == (NU8)(0))) goto LA11;
					goto LA2;
				}
				LA11: ;
				{
					if (!((NU8)(layout->data[i]) == (NU8)(39))) goto LA15;
					i += ((NI) 1);
					j += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC19;
							LOC19 = 0;
							LOC19 = !(((NU8)(layout->data[i]) == (NU8)(39)));
							if (!(LOC19)) goto LA20;
							LOC19 = (i < (NI)((layout ? layout->Sup.len : 0) - ((NI) 1)));
							LA20: ;
							if (!LOC19) goto LA18;
							i += ((NI) 1);
							j += ((NI) 1);
						} LA18: ;
					}
				}
				goto LA13;
				LA15: ;
				{
					i += ((NI) 1);
					j += ((NI) 1);
				}
				LA13: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC25;
					LOC25 = 0;
					LOC25 = ((token ? token->Sup.len : 0) < ((NI) 1));
					if (LOC25) goto LA26;
					LOC25 = ((NU8)(token->data[(token ? (token->Sup.len-1) : -1)]) == (NU8)(layout->data[i]));
					LA26: ;
					if (!LOC25) goto LA27;
					token = addChar(token, layout->data[i]);
					i += ((NI) 1);
				}
				goto LA23;
				LA27: ;
				{
					parsetoken_102460((&info), token, value, (&j));
					token = copyString(((NimStringDesc*) &TMP576));
				}
				LA23: ;
			}
			break;
			}
		}
	} LA2: ;
	LOC30 = 0;
	LOC30 = timeinfototime_100487((&info));
	memset((void*)(&LOC31), 0, sizeof(LOC31));
	LOC31.Sup.m_type = (&NTI100408);
	getlocaltime_100475(LOC30, (&LOC31));
	info.weekday = LOC31.weekday;
	genericAssign((void*)Result, (void*)(&info), (&NTI100408));
	goto BeforeRet;
	}BeforeRet: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void) {
	tzset();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void) {
static TNimNode* TMP227[11];
static TNimNode* TMP228[12];
NI TMP230;
static char* NIM_CONST TMP229[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP231[7];
NI TMP233;
static char* NIM_CONST TMP232[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode* TMP325[2];
static TNimNode TMP11[36];
NTI100408.size = sizeof(Timeinfo100408);
NTI100408.kind = 17;
NTI100408.base = (&NTI3411);
TMP227[0] = &TMP11[1];
NTI100411.size = sizeof(NI);
NTI100411.kind = 20;
NTI100411.base = (&NTI108);
NTI100411.flags = 3;
TMP11[1].kind = 1;
TMP11[1].offset = offsetof(Timeinfo100408, second);
TMP11[1].typ = (&NTI100411);
TMP11[1].name = "second";
TMP227[1] = &TMP11[2];
NTI100414.size = sizeof(NI);
NTI100414.kind = 20;
NTI100414.base = (&NTI108);
NTI100414.flags = 3;
TMP11[2].kind = 1;
TMP11[2].offset = offsetof(Timeinfo100408, minute);
TMP11[2].typ = (&NTI100414);
TMP11[2].name = "minute";
TMP227[2] = &TMP11[3];
NTI100416.size = sizeof(NI);
NTI100416.kind = 20;
NTI100416.base = (&NTI108);
NTI100416.flags = 3;
TMP11[3].kind = 1;
TMP11[3].offset = offsetof(Timeinfo100408, hour);
TMP11[3].typ = (&NTI100416);
TMP11[3].name = "hour";
TMP227[3] = &TMP11[4];
NTI100419.size = sizeof(NI);
NTI100419.kind = 20;
NTI100419.base = (&NTI108);
NTI100419.flags = 3;
TMP11[4].kind = 1;
TMP11[4].offset = offsetof(Timeinfo100408, monthday);
TMP11[4].typ = (&NTI100419);
TMP11[4].name = "monthday";
TMP227[4] = &TMP11[5];
NTI100006.size = sizeof(NU8);
NTI100006.kind = 14;
NTI100006.base = 0;
NTI100006.flags = 3;
for (TMP230 = 0; TMP230 < 12; TMP230++) {
TMP11[TMP230+6].kind = 1;
TMP11[TMP230+6].offset = TMP230;
TMP11[TMP230+6].name = TMP229[TMP230];
TMP228[TMP230] = &TMP11[TMP230+6];
}
TMP11[18].len = 12; TMP11[18].kind = 2; TMP11[18].sons = &TMP228[0];
NTI100006.node = &TMP11[18];
TMP11[5].kind = 1;
TMP11[5].offset = offsetof(Timeinfo100408, month);
TMP11[5].typ = (&NTI100006);
TMP11[5].name = "month";
TMP227[5] = &TMP11[19];
TMP11[19].kind = 1;
TMP11[19].offset = offsetof(Timeinfo100408, year);
TMP11[19].typ = (&NTI108);
TMP11[19].name = "year";
TMP227[6] = &TMP11[20];
NTI100008.size = sizeof(NU8);
NTI100008.kind = 14;
NTI100008.base = 0;
NTI100008.flags = 3;
for (TMP233 = 0; TMP233 < 7; TMP233++) {
TMP11[TMP233+21].kind = 1;
TMP11[TMP233+21].offset = TMP233;
TMP11[TMP233+21].name = TMP232[TMP233];
TMP231[TMP233] = &TMP11[TMP233+21];
}
TMP11[28].len = 7; TMP11[28].kind = 2; TMP11[28].sons = &TMP231[0];
NTI100008.node = &TMP11[28];
TMP11[20].kind = 1;
TMP11[20].offset = offsetof(Timeinfo100408, weekday);
TMP11[20].typ = (&NTI100008);
TMP11[20].name = "weekday";
TMP227[7] = &TMP11[29];
NTI100425.size = sizeof(NI);
NTI100425.kind = 20;
NTI100425.base = (&NTI108);
NTI100425.flags = 3;
TMP11[29].kind = 1;
TMP11[29].offset = offsetof(Timeinfo100408, yearday);
TMP11[29].typ = (&NTI100425);
TMP11[29].name = "yearday";
TMP227[8] = &TMP11[30];
TMP11[30].kind = 1;
TMP11[30].offset = offsetof(Timeinfo100408, isdst);
TMP11[30].typ = (&NTI138);
TMP11[30].name = "isDST";
TMP227[9] = &TMP11[31];
TMP11[31].kind = 1;
TMP11[31].offset = offsetof(Timeinfo100408, tzname);
TMP11[31].typ = (&NTI149);
TMP11[31].name = "tzname";
TMP227[10] = &TMP11[32];
TMP11[32].kind = 1;
TMP11[32].offset = offsetof(Timeinfo100408, timezone);
TMP11[32].typ = (&NTI108);
TMP11[32].name = "timezone";
TMP11[0].len = 11; TMP11[0].kind = 2; TMP11[0].sons = &TMP227[0];
NTI100408.node = &TMP11[0];
NTI100570.size = sizeof(TY100570);
NTI100570.kind = 18;
NTI100570.base = 0;
NTI100570.flags = 2;
TMP325[0] = &TMP11[34];
TMP11[34].kind = 1;
TMP11[34].offset = offsetof(TY100570, Field0);
TMP11[34].typ = (&NTI149);
TMP11[34].name = "Field0";
TMP325[1] = &TMP11[35];
TMP11[35].kind = 1;
TMP11[35].offset = offsetof(TY100570, Field1);
TMP11[35].typ = (&NTI149);
TMP11[35].name = "Field1";
TMP11[33].len = 2; TMP11[33].kind = 2; TMP11[33].sons = &TMP325[0];
NTI100570.node = &TMP11[33];
}

