/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/stdlib_openssl.o /data4/NimStuff/NimFinLib/nimcache/stdlib_openssl.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Sslstruct210405 Sslstruct210405;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, TY211045) (void* a, void* b, void* c);
typedef N_CDECL_PTR(int, TY210582) (void);
typedef N_CDECL_PTR(void, TY210587) (void);
typedef N_CDECL_PTR(void, TY210592) (void);
typedef N_CDECL_PTR(void, TY211034) (void);
typedef N_CDECL_PTR(Sslstruct210405*, TY210634) (Sslstruct210405* meth);
typedef N_CDECL_PTR(Sslstruct210405*, TY210602) (void);
typedef N_CDECL_PTR(int, TY211029) (void);
typedef N_CDECL_PTR(NCSTRING, TY211017) (int e, NCSTRING buf);
typedef N_CDECL_PTR(Sslstruct210405*, TY210612) (void);
typedef N_CDECL_PTR(Sslstruct210405*, TY210617) (void);
typedef N_CDECL_PTR(int, TY210672) (Sslstruct210405* s, NCSTRING ciphers);
typedef N_CDECL_PTR(NI, TY210657) (NI a, void* b);
typedef N_CDECL_PTR(void, TY210654) (Sslstruct210405* s, NI mode, TY210657 cb);
typedef N_CDECL_PTR(NI, TY211408) (Sslstruct210405* ctx, int cmd, NI larg, void* parg);
typedef N_STDCALL_PTR(int, TY210687) (Sslstruct210405* ctx, NCSTRING filename);
typedef N_CDECL_PTR(int, TY210694) (Sslstruct210405* ctx, NCSTRING filename, int typ);
typedef N_CDECL_PTR(int, TY210702) (Sslstruct210405* ctx);
struct  Sslstruct210405  {
char dummy;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef N_CDECL_PTR(Sslstruct210405*, TY210622) (Sslstruct210405* context);
typedef N_CDECL_PTR(int, TY210708) (Sslstruct210405* ssl, int fd);
typedef N_CDECL_PTR(NI, TY211436) (Sslstruct210405* ssl, int cmd, NI larg, void* parg);
typedef N_CDECL_PTR(int, TY210734) (Sslstruct210405* ssl);
typedef N_CDECL_PTR(int, TY210756) (Sslstruct210405* s, int retcode);
typedef N_CDECL_PTR(int, TY210748) (Sslstruct210405* ssl, NCSTRING buf, NI num);
typedef N_CDECL_PTR(int, TY210769) (Sslstruct210405* ssl);
typedef N_CDECL_PTR(int, TY210740) (Sslstruct210405* ssl, void* buf, NI num);
typedef N_CDECL_PTR(void, TY211581) (void);
typedef N_CDECL_PTR(int, TY210715) (Sslstruct210405* ssl);
typedef N_CDECL_PTR(void, TY210628) (Sslstruct210405* ssl);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_CDECL(void*, allocwrapper_211049)(NI size);
N_NOCONV(void*, alloc_6001)(NI size);
N_CDECL(void*, reallocwrapper_211056)(void* p, NI newsize);
N_NOCONV(void, dealloc_6048)(void* p);
N_NOCONV(void*, realloc_6033)(void* p, NI newsize);
N_CDECL(void, deallocwrapper_211064)(void* p);
STRING_LITERAL(TMP89, "libcrypto.so.10", 15);
STRING_LITERAL(TMP90, "libcrypto.so.1.0.1", 18);
STRING_LITERAL(TMP91, "libcrypto.so.1.0.0", 18);
STRING_LITERAL(TMP92, "libcrypto.so.0.9.9", 18);
STRING_LITERAL(TMP93, "libcrypto.so.0.9.8", 18);
STRING_LITERAL(TMP94, "libcrypto.so(.10|.1.0.1|.1.0.0|.0.9.9|.0.9.8)", 45);
STRING_LITERAL(TMP99, "libssl.so.10", 12);
STRING_LITERAL(TMP100, "libssl.so.1.0.1", 15);
STRING_LITERAL(TMP101, "libssl.so.1.0.0", 15);
STRING_LITERAL(TMP102, "libssl.so.0.9.9", 15);
STRING_LITERAL(TMP103, "libssl.so.0.9.8", 15);
STRING_LITERAL(TMP104, "libssl.so(.10|.1.0.1|.1.0.0|.0.9.9|.0.9.8)", 42);
static void* TMP88;
TY211045 Dl_211044;
static void* TMP98;
TY210582 Dl_210581;
TY210587 Dl_210586;
TY210592 Dl_210591;
TY211034 Dl_211033;
TY210634 Dl_210633;
TY210602 Dl_210601;
TY211029 Dl_211028;
TY211017 Dl_211016;
TY210612 Dl_210611;
TY210617 Dl_210616;
TY210672 Dl_210671;
TY210654 Dl_210653;
TY211408 Dl_211407;
TY210687 Dl_210686;
TY210694 Dl_210693;
TY210702 Dl_210701;
TNimType NTI210405; /* SslStruct */
TNimType NTI210407; /* SslCtx */
TY210622 Dl_210621;
TY210708 Dl_210707;
TY211436 Dl_211435;
TY210734 Dl_210733;
TY210756 Dl_210755;
TY210748 Dl_210747;
TY210769 Dl_210768;
TY210740 Dl_210739;
TY211581 Dl_211580;
TY210715 Dl_210714;
TY210628 Dl_210627;

N_CDECL(void*, allocwrapper_211049)(NI size) {
	void* result;
	result = 0;
	result = alloc_6001(((NI) (size)));
	return result;
}

N_CDECL(void*, reallocwrapper_211056)(void* p, NI newsize) {
	void* result;
	result = 0;
	{
		if (!(p == NIM_NIL)) goto LA3;
		{
			if (!(((NI) 0) < newsize)) goto LA7;
			result = alloc_6001(((NI) (newsize)));
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		if (!(newsize == ((NI) 0))) goto LA10;
		dealloc_6048(p);
	}
	goto LA1;
	LA10: ;
	{
		result = realloc_6033(p, ((NI) (newsize)));
	}
	LA1: ;
	return result;
}

N_CDECL(void, deallocwrapper_211064)(void* p) {
	{
		if (!!((p == NIM_NIL))) goto LA3;
		dealloc_6048(p);
	}
	LA3: ;
}

N_NIMCALL(void, Cryptomallocinit_211204)(void) {
	Dl_211044(allocwrapper_211049, reallocwrapper_211056, deallocwrapper_211064);
}

N_NIMCALL(NI, Sslctxsetmode_211424)(Sslstruct210405* ctx, NI mode) {
	NI result;
	result = 0;
	result = Dl_211407(ctx, ((int) 33), mode, NIM_NIL);
	return result;
}

N_NIMCALL(NI, Sslsettlsexthostname_211444)(Sslstruct210405* ssl, NCSTRING name) {
	NI result;
	result = 0;
	result = Dl_211435(ssl, ((int) 55), ((NI) 0), ((void*) (name)));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_opensslInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_opensslDatInit)(void) {
static TNimNode TMP86[1];
NTI210405.size = sizeof(Sslstruct210405);
NTI210405.kind = 18;
NTI210405.base = 0;
NTI210405.flags = 3;
TMP86[0].len = 0; TMP86[0].kind = 2;
NTI210405.node = &TMP86[0];
NTI210407.size = sizeof(Sslstruct210405*);
NTI210407.kind = 21;
NTI210407.base = (&NTI210405);
NTI210407.flags = 3;
if (!((TMP88 = nimLoadLibrary((NimStringDesc*) &TMP89))
||(TMP88 = nimLoadLibrary((NimStringDesc*) &TMP90))
||(TMP88 = nimLoadLibrary((NimStringDesc*) &TMP91))
||(TMP88 = nimLoadLibrary((NimStringDesc*) &TMP92))
||(TMP88 = nimLoadLibrary((NimStringDesc*) &TMP93))
)) nimLoadLibraryError((NimStringDesc*) &TMP94);
	Dl_211044 = (TY211045) nimGetProcAddr(TMP88, "CRYPTO_set_mem_functions");
if (!((TMP98 = nimLoadLibrary((NimStringDesc*) &TMP99))
||(TMP98 = nimLoadLibrary((NimStringDesc*) &TMP100))
||(TMP98 = nimLoadLibrary((NimStringDesc*) &TMP101))
||(TMP98 = nimLoadLibrary((NimStringDesc*) &TMP102))
||(TMP98 = nimLoadLibrary((NimStringDesc*) &TMP103))
)) nimLoadLibraryError((NimStringDesc*) &TMP104);
	Dl_210581 = (TY210582) nimGetProcAddr(TMP98, "SSL_library_init");
	Dl_210586 = (TY210587) nimGetProcAddr(TMP98, "SSL_load_error_strings");
	Dl_210591 = (TY210592) nimGetProcAddr(TMP88, "ERR_load_BIO_strings");
	Dl_211033 = (TY211034) nimGetProcAddr(TMP88, "OPENSSL_add_all_algorithms_conf");
	Dl_210633 = (TY210634) nimGetProcAddr(TMP98, "SSL_CTX_new");
	Dl_210601 = (TY210602) nimGetProcAddr(TMP98, "SSLv23_method");
	Dl_211028 = (TY211029) nimGetProcAddr(TMP88, "ERR_peek_last_error");
	Dl_211016 = (TY211017) nimGetProcAddr(TMP88, "ERR_error_string");
	Dl_210611 = (TY210612) nimGetProcAddr(TMP98, "SSLv3_method");
	Dl_210616 = (TY210617) nimGetProcAddr(TMP98, "TLSv1_method");
	Dl_210671 = (TY210672) nimGetProcAddr(TMP98, "SSL_CTX_set_cipher_list");
	Dl_210653 = (TY210654) nimGetProcAddr(TMP98, "SSL_CTX_set_verify");
	Dl_211407 = (TY211408) nimGetProcAddr(TMP98, "SSL_CTX_ctrl");
	Dl_210686 = (TY210687) nimGetProcAddr(TMP98, "SSL_CTX_use_certificate_chain_file");
	Dl_210693 = (TY210694) nimGetProcAddr(TMP98, "SSL_CTX_use_PrivateKey_file");
	Dl_210701 = (TY210702) nimGetProcAddr(TMP98, "SSL_CTX_check_private_key");
	Dl_210621 = (TY210622) nimGetProcAddr(TMP98, "SSL_new");
	Dl_210707 = (TY210708) nimGetProcAddr(TMP98, "SSL_set_fd");
	Dl_211435 = (TY211436) nimGetProcAddr(TMP98, "SSL_ctrl");
	Dl_210733 = (TY210734) nimGetProcAddr(TMP98, "SSL_connect");
	Dl_210755 = (TY210756) nimGetProcAddr(TMP98, "SSL_get_error");
	Dl_210747 = (TY210748) nimGetProcAddr(TMP98, "SSL_write");
	Dl_210768 = (TY210769) nimGetProcAddr(TMP98, "SSL_pending");
	Dl_210739 = (TY210740) nimGetProcAddr(TMP98, "SSL_read");
	Dl_211580 = (TY211581) nimGetProcAddr(TMP88, "ERR_clear_error");
	Dl_210714 = (TY210715) nimGetProcAddr(TMP98, "SSL_shutdown");
	Dl_210627 = (TY210628) nimGetProcAddr(TMP98, "SSL_free");
}

