/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o nimcache/stdlib_strtabs.o nimcache/stdlib_strtabs.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct Stringtableobj224012 Stringtableobj224012;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Keyvaluepairseq224010 Keyvaluepairseq224010;
typedef struct TY100570 TY100570;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Stringtableobj224012  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq224010* data;
NU8 mode;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY100570 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
struct Keyvaluepairseq224010 {
  TGenericSeq Sup;
  TY100570 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP326)(void* p, NI op);
N_NIMCALL(void, TMP330)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NI, rawget_224418)(Stringtableobj224012* t, NimStringDesc* key);
N_NIMCALL(NI, myhash_224177)(Stringtableobj224012* t, NimStringDesc* key);
N_NIMCALL(NI, hash_158842)(NimStringDesc* x);
N_NIMCALL(NI, hashignorecase_158985)(NimStringDesc* x);
N_NIMCALL(NI, hashignorestyle_158890)(NimStringDesc* x);
N_NIMCALL(NIM_BOOL, mycmp_224188)(Stringtableobj224012* t, NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, cmp_4717)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, nexttry_224407)(NI h, NI maxhash);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, mustrehash_224200)(NI length, NI counter);
N_NIMCALL(void, enlarge_224510)(Stringtableobj224012* t);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, rawinsert_224488)(Stringtableobj224012* t, Keyvaluepairseq224010** data, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
STRING_LITERAL(TMP344, "", 0);
extern TNimType NTI3411; /* RootObj */
TNimType NTI224012; /* StringTableObj */
extern TNimType NTI108; /* int */
extern TNimType NTI100570; /* tuple[nonDST: string, DST: string] */
TNimType NTI224010; /* KeyValuePairSeq */
TNimType NTI224006; /* StringTableMode */
TNimType NTI224014; /* StringTableRef */
extern Gcheap46616 gch_46648;
N_NIMCALL(void, TMP326)(void* p, NI op) {
	Keyvaluepairseq224010* a;
	NI LOC1;
	a = (Keyvaluepairseq224010*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}
N_NIMCALL(void, TMP330)(void* p, NI op) {
	Stringtableobj224012* a;
	a = (Stringtableobj224012*)p;
	nimGCvisit((void*)(*a).data, op);
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

N_NIMCALL(Stringtableobj224012*, nstnewStringTable)(NU8 mode) {
	Stringtableobj224012* result;
	result = 0;
	result = (Stringtableobj224012*) newObj((&NTI224014), sizeof(Stringtableobj224012));
	(*result).Sup.m_type = (&NTI224012);
	(*result).mode = mode;
	(*result).counter = ((NI) 0);
	if ((*result).data) nimGCunrefNoCycle((*result).data);
	(*result).data = (Keyvaluepairseq224010*) newSeqRC1((&NTI224010), ((NI) 64));
	return result;
}

N_NIMCALL(NI, myhash_224177)(Stringtableobj224012* t, NimStringDesc* key) {
	NI result;
	result = 0;
	switch ((*t).mode) {
	case ((NU8) 0):
	{
		result = hash_158842(key);
	}
	break;
	case ((NU8) 1):
	{
		result = hashignorecase_158985(key);
	}
	break;
	case ((NU8) 2):
	{
		result = hashignorestyle_158890(key);
	}
	break;
	}
	return result;
}

N_NIMCALL(NIM_BOOL, mycmp_224188)(Stringtableobj224012* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	result = 0;
	switch ((*t).mode) {
	case ((NU8) 0):
	{
		NI LOC2;
		LOC2 = 0;
		LOC2 = cmp_4717(a, b);
		result = (LOC2 == ((NI) 0));
	}
	break;
	case ((NU8) 1):
	{
		NI LOC4;
		LOC4 = 0;
		LOC4 = nsuCmpIgnoreCase(a, b);
		result = (LOC4 == ((NI) 0));
	}
	break;
	case ((NU8) 2):
	{
		NI LOC6;
		LOC6 = 0;
		LOC6 = nsuCmpIgnoreStyle(a, b);
		result = (LOC6 == ((NI) 0));
	}
	break;
	}
	return result;
}

static N_INLINE(NI, nexttry_224407)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI)((NI)(((NI) 5) * h) + ((NI) 1)) & maxhash);
	return result;
}

N_NIMCALL(NI, rawget_224418)(Stringtableobj224012* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = myhash_224177(t, key);
	h = (NI)(LOC1 & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		while (1) {
			if (!!((*t).data->data[h].Field0 == 0)) goto LA3;
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				LOC6 = mycmp_224188(t, (*t).data->data[h].Field0, key);
				if (!LOC6) goto LA7;
				result = h;
				goto BeforeRet;
			}
			LA7: ;
			h = nexttry_224407(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA3: ;
	}
	result = ((NI) -1);
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, mustrehash_224200)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ((NI)(length * ((NI) 2)) < (NI)(counter * ((NI) 3)));
	if (LOC1) goto LA2;
	LOC1 = ((NI)(length - counter) < ((NI) 4));
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(void, rawinsert_224488)(Stringtableobj224012* t, Keyvaluepairseq224010** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	LOC1 = 0;
	LOC1 = myhash_224177(t, key);
	h = (NI)(LOC1 & ((*data) ? ((*data)->Sup.len-1) : -1));
	{
		while (1) {
			if (!!((*data)->data[h].Field0 == 0)) goto LA3;
			h = nexttry_224407(h, ((*data) ? ((*data)->Sup.len-1) : -1));
		} LA3: ;
	}
	LOC4 = 0;
	LOC4 = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	LOC5 = 0;
	LOC5 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (LOC5) nimGCunrefNoCycle(LOC5);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell44747* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_48246(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell44747* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_48246((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_49804(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

N_NIMCALL(void, enlarge_224510)(Stringtableobj224012* t) {
	Keyvaluepairseq224010* n;
	Keyvaluepairseq224010* LOC8;
	n = 0;
	n = (Keyvaluepairseq224010*) newSeq((&NTI224010), ((NI) ((NI)(((*t).data ? (*t).data->Sup.len : 0) * ((NI) 2)))));
	{
		NI i_224544;
		NI HEX3Atmp_224558;
		NI res_224561;
		i_224544 = 0;
		HEX3Atmp_224558 = 0;
		HEX3Atmp_224558 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		res_224561 = ((NI) 0);
		{
			while (1) {
				if (!(res_224561 <= HEX3Atmp_224558)) goto LA3;
				i_224544 = res_224561;
				{
					if (!!((*t).data->data[i_224544].Field0 == 0)) goto LA6;
					rawinsert_224488(t, (&n), (*t).data->data[i_224544].Field0, (*t).data->data[i_224544].Field1);
				}
				LA6: ;
				res_224561 += ((NI) 1);
			} LA3: ;
		}
	}
	LOC8 = 0;
	LOC8 = (*t).data;
	asgnRefNoCycle((void**) (&(*t).data), n);
	n = LOC8;
}

N_NIMCALL(void, nstPut)(Stringtableobj224012* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	index = rawget_224418(t, key);
	{
		NimStringDesc* LOC5;
		if (!(((NI) 0) <= index)) goto LA3;
		LOC5 = 0;
		LOC5 = (*t).data->data[index].Field1; (*t).data->data[index].Field1 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC9;
			LOC9 = 0;
			LOC9 = mustrehash_224200(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC9) goto LA10;
			enlarge_224510(t);
		}
		LA10: ;
		rawinsert_224488(t, (&(*t).data), key, val);
		(*t).counter += ((NI) 1);
	}
	LA1: ;
}

N_NIMCALL(NimStringDesc*, nstGet)(Stringtableobj224012* t, NimStringDesc* key) {
	NimStringDesc* result;
	NI index;
	result = 0;
	index = rawget_224418(t, key);
	{
		if (!(((NI) 0) <= index)) goto LA3;
		result = copyString((*t).data->data[index].Field1);
	}
	goto LA1;
	LA3: ;
	{
		result = copyString(((NimStringDesc*) &TMP344));
	}
	LA1: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void) {
static TNimNode* TMP324[3];
static TNimNode* TMP327[3];
NI TMP329;
static char* NIM_CONST TMP328[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TMP107[8];
NTI224012.size = sizeof(Stringtableobj224012);
NTI224012.kind = 17;
NTI224012.base = (&NTI3411);
TMP324[0] = &TMP107[1];
TMP107[1].kind = 1;
TMP107[1].offset = offsetof(Stringtableobj224012, counter);
TMP107[1].typ = (&NTI108);
TMP107[1].name = "counter";
TMP324[1] = &TMP107[2];
NTI224010.size = sizeof(Keyvaluepairseq224010*);
NTI224010.kind = 24;
NTI224010.base = (&NTI100570);
NTI224010.flags = 2;
NTI224010.marker = TMP326;
TMP107[2].kind = 1;
TMP107[2].offset = offsetof(Stringtableobj224012, data);
TMP107[2].typ = (&NTI224010);
TMP107[2].name = "data";
TMP324[2] = &TMP107[3];
NTI224006.size = sizeof(NU8);
NTI224006.kind = 14;
NTI224006.base = 0;
NTI224006.flags = 3;
for (TMP329 = 0; TMP329 < 3; TMP329++) {
TMP107[TMP329+4].kind = 1;
TMP107[TMP329+4].offset = TMP329;
TMP107[TMP329+4].name = TMP328[TMP329];
TMP327[TMP329] = &TMP107[TMP329+4];
}
TMP107[7].len = 3; TMP107[7].kind = 2; TMP107[7].sons = &TMP327[0];
NTI224006.node = &TMP107[7];
TMP107[3].kind = 1;
TMP107[3].offset = offsetof(Stringtableobj224012, mode);
TMP107[3].typ = (&NTI224006);
TMP107[3].name = "mode";
TMP107[0].len = 3; TMP107[0].kind = 2; TMP107[0].sons = &TMP324[0];
NTI224012.node = &TMP107[0];
NTI224014.size = sizeof(Stringtableobj224012*);
NTI224014.kind = 22;
NTI224014.base = (&NTI224012);
NTI224014.marker = TMP330;
}

