/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/stdlib_tables.o /data4/NimStuff/NimFinLib/nimcache/stdlib_tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct TY100570 TY100570;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Table329036 Table329036;
typedef struct Keyvaluepairseq329039 Keyvaluepairseq329039;
typedef struct Keyvaluepair329042 Keyvaluepair329042;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY100570 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Table329036  {
Keyvaluepairseq329039* data;
NI counter;
};
struct Keyvaluepair329042 {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
struct Keyvaluepairseq329039 {
  TGenericSeq Sup;
  Keyvaluepair329042 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, inittable_329056)(NI initialsize, Table329036* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP496)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, rightsize_160407)(NI count);
N_NIMCALL(NI, nextpoweroftwo_142531)(NI x);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX5BHEX5DHEX3D_329232)(Table329036* t, NimStringDesc* key, NimStringDesc* val);
static N_INLINE(NI, rawget_329246)(Table329036 t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_158842)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isfilled_160211)(NI hcode);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, nexttry_160420)(NI h, NI maxhash);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
static N_INLINE(NIM_BOOL, mustrehash_160313)(NI length, NI counter);
N_NIMCALL(void, enlarge_329282)(Table329036* t);
static N_INLINE(NI, rawgetknownhc_329336)(Table329036 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_329362)(Table329036* t, Keyvaluepairseq329039** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
TNimType NTI329042; /* KeyValuePair */
extern TNimType NTI158005; /* Hash */
extern TNimType NTI149; /* string */
TNimType NTI329039; /* KeyValuePairSeq */
TNimType NTI329036; /* Table */
extern TNimType NTI108; /* int */
extern Gcheap46616 gch_46648;
N_NIMCALL(void, TMP496)(void* p, NI op) {
	Keyvaluepairseq329039* a;
	NI LOC1;
	a = (Keyvaluepairseq329039*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	nimGCvisit((void*)a->data[LOC1].Field2, op);
	}
}

N_NIMCALL(void, inittable_329056)(NI initialsize, Table329036* Result) {
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq329039*) newSeq((&NTI329039), ((NI) (initialsize))));
}

static N_INLINE(NI, rightsize_160407)(NI count) {
	NI result;
	result = 0;
	result = nextpoweroftwo_142531(((NI) ((NI)(((NI) ((NI)(((NI) ((NI)(((NI) (count)) * ((NI) 3)))) / ((NI) 2)))) + ((NI) 4)))));
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_160211)(NI hcode) {
	NIM_BOOL result;
	result = 0;
	result = !((hcode == ((NI) 0)));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_160420)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI)(h + ((NI) 1)) & maxhash);
	return result;
}

static N_INLINE(NI, rawget_329246)(Table329036 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
{	result = 0;
	(*hc) = hash_158842(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		while (1) {
			NIM_BOOL LOC7;
			LOC7 = 0;
			LOC7 = isfilled_160211(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			h = nexttry_160420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet: ;
	return result;
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

static N_INLINE(NIM_BOOL, mustrehash_160313)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ((NI)(length * ((NI) 2)) < (NI)(counter * ((NI) 3)));
	if (LOC1) goto LA2;
	LOC1 = ((NI)(length - counter) < ((NI) 4));
	LA2: ;
	result = LOC1;
	return result;
}

static N_INLINE(NI, rawgetknownhc_329336)(Table329036 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
{	result = 0;
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = 0;
			LOC3 = isfilled_160211(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			h = nexttry_160420(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, rawinsert_329362)(Table329036* t, Keyvaluepairseq329039** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	LOC1 = 0;
	LOC1 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	LOC2 = 0;
	LOC2 = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(val);
	if (LOC2) nimGCunrefNoCycle(LOC2);
	(*data)->data[h].Field0 = hc;
}

N_NIMCALL(void, enlarge_329282)(Table329036* t) {
	Keyvaluepairseq329039* n;
	Keyvaluepairseq329039* LOC1;
	n = 0;
	n = (Keyvaluepairseq329039*) newSeq((&NTI329039), ((NI) ((NI)(((*t).data ? (*t).data->Sup.len : 0) * ((NI) 2)))));
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_329334;
		NI HEX3Atmp_329388;
		NI res_329391;
		i_329334 = 0;
		HEX3Atmp_329388 = 0;
		HEX3Atmp_329388 = (n ? (n->Sup.len-1) : -1);
		res_329391 = ((NI) 0);
		{
			while (1) {
				if (!(res_329391 <= HEX3Atmp_329388)) goto LA4;
				i_329334 = res_329391;
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					LOC7 = 0;
					LOC7 = isfilled_160211(n->data[i_329334].Field0);
					if (!LOC7) goto LA8;
					LOC10 = 0;
					LOC10 = rawgetknownhc_329336((*t), n->data[i_329334].Field1, n->data[i_329334].Field0);
					j = (NI)(((NI) -1) - LOC10);
					rawinsert_329362(t, (&(*t).data), n->data[i_329334].Field1, n->data[i_329334].Field2, n->data[i_329334].Field0, j);
				}
				LA8: ;
				res_329391 += ((NI) 1);
			} LA4: ;
		}
	}
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_329232)(Table329036* t, NimStringDesc* key, NimStringDesc* val) {
	NI hc;
	NI index;
	hc = 0;
	index = rawget_329246((*t), key, (&hc));
	{
		NimStringDesc* LOC5;
		if (!(((NI) 0) <= index)) goto LA3;
		LOC5 = 0;
		LOC5 = (*t).data->data[index].Field2; (*t).data->data[index].Field2 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		{
			NIM_BOOL LOC9;
			LOC9 = 0;
			LOC9 = mustrehash_160313(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC9) goto LA10;
			enlarge_329282(t);
			index = rawgetknownhc_329336((*t), key, hc);
		}
		LA10: ;
		index = (NI)(((NI) -1) - index);
		rawinsert_329362(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA1: ;
}

N_NIMCALL(void, totable_329026)(TY100570* pairs, NI pairsLen0, Table329036* Result) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = rightsize_160407(((NI) (pairsLen0)));
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI329036));
	inittable_329056(LOC1, Result);
	{
		NimStringDesc* key_329229;
		NimStringDesc* val_329230;
		NI i_329459;
		key_329229 = 0;
		val_329230 = 0;
		i_329459 = ((NI) 0);
		{
			while (1) {
				if (!(i_329459 < pairsLen0)) goto LA4;
				key_329229 = pairs[i_329459].Field0;
				val_329230 = pairs[i_329459].Field1;
				HEX5BHEX5DHEX3D_329232(Result, key_329229, val_329230);
				i_329459 += ((NI) 1);
			} LA4: ;
		}
	}
}

N_NIMCALL(NimStringDesc*, HEX5BHEX5D_329504)(Table329036 t, NimStringDesc* key) {
	NimStringDesc* result;
	NI hc;
	NI index;
	result = 0;
	hc = 0;
	index = rawget_329246(t, key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA3;
		result = copyString(t.data->data[index].Field2);
	}
	LA3: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void) {
static TNimNode* TMP495[3];
static TNimNode* TMP497[2];
static TNimNode TMP29[7];
NTI329042.size = sizeof(Keyvaluepair329042);
NTI329042.kind = 18;
NTI329042.base = 0;
NTI329042.flags = 2;
TMP495[0] = &TMP29[1];
TMP29[1].kind = 1;
TMP29[1].offset = offsetof(Keyvaluepair329042, Field0);
TMP29[1].typ = (&NTI158005);
TMP29[1].name = "Field0";
TMP495[1] = &TMP29[2];
TMP29[2].kind = 1;
TMP29[2].offset = offsetof(Keyvaluepair329042, Field1);
TMP29[2].typ = (&NTI149);
TMP29[2].name = "Field1";
TMP495[2] = &TMP29[3];
TMP29[3].kind = 1;
TMP29[3].offset = offsetof(Keyvaluepair329042, Field2);
TMP29[3].typ = (&NTI149);
TMP29[3].name = "Field2";
TMP29[0].len = 3; TMP29[0].kind = 2; TMP29[0].sons = &TMP495[0];
NTI329042.node = &TMP29[0];
NTI329039.size = sizeof(Keyvaluepairseq329039*);
NTI329039.kind = 24;
NTI329039.base = (&NTI329042);
NTI329039.flags = 2;
NTI329039.marker = TMP496;
NTI329036.size = sizeof(Table329036);
NTI329036.kind = 18;
NTI329036.base = 0;
NTI329036.flags = 2;
TMP497[0] = &TMP29[5];
TMP29[5].kind = 1;
TMP29[5].offset = offsetof(Table329036, data);
TMP29[5].typ = (&NTI329039);
TMP29[5].name = "data";
TMP497[1] = &TMP29[6];
TMP29[6].kind = 1;
TMP29[6].offset = offsetof(Table329036, counter);
TMP29[6].typ = (&NTI108);
TMP29[6].name = "counter";
TMP29[4].len = 2; TMP29[4].kind = 2; TMP29[4].sons = &TMP497[0];
NTI329036.node = &TMP29[4];
}

