/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o nimcache/stdlib_terminal.o nimcache/stdlib_terminal.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, write_13495)(FILE* f, NimStringDesc* s);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
STRING_LITERAL(TMP144, "\033[", 2);
STRING_LITERAL(TMP754, "\033[0m", 4);
NI gfg_137425;
NI gbg_137426;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(void, setforegroundcolor_138057)(NU8 fg, NIM_BOOL bright) {
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	gfg_137425 = ((NI) (fg));
	{
		if (!bright) goto LA3;
		gfg_137425 += ((NI) 60);
	}
	LA3: ;
	LOC5 = 0;
	LOC6 = 0;
	LOC6 = nimIntToStr(gfg_137425);
	LOC5 = rawNewString(LOC6->Sup.len + 3);
appendString(LOC5, ((NimStringDesc*) &TMP144));
appendString(LOC5, LOC6);
appendChar(LOC5, 109);
	write_13495(stdout, LOC5);
}

N_NOCONV(void, resetattributes_137209)(void) {
	write_13495(stdout, ((NimStringDesc*) &TMP754));
}
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit)(void) {
	gfg_137425 = ((NI) 0);
	gbg_137426 = ((NI) 0);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit)(void) {
}

