/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o nimcache/stdlib_streams.o nimcache/stdlib_streams.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <setjmp.h>
typedef struct Filestreamobj186984 Filestreamobj186984;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Streamobj186027 Streamobj186027;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Ioerror3431 Ioerror3431;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, TY186028) (Streamobj186027* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY186032) (Streamobj186027* s);
typedef N_NIMCALL_PTR(void, TY186036) (Streamobj186027* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY186041) (Streamobj186027* s);
typedef N_NIMCALL_PTR(NI, TY186045) (Streamobj186027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY186051) (Streamobj186027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY186057) (Streamobj186027* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY186063) (Streamobj186027* s);
struct  Streamobj186027  {
  TNimObject Sup;
TY186028 closeimpl;
TY186032 atendimpl;
TY186036 setpositionimpl;
TY186041 getpositionimpl;
TY186045 readdataimpl;
TY186051 peekdataimpl;
TY186057 writedataimpl;
TY186063 flushimpl;
};
struct  Filestreamobj186984  {
  Streamobj186027 Sup;
FILE* f;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY15611;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY15611 raiseAction;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Ioerror3431  {
  Systemerror3429 Sup;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
N_NIMCALL(NIM_BOOL, open_13403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(Filestreamobj186984*, newfilestream_187061)(FILE* f);
N_NIMCALL(void, TMP374)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, fsclose_186988)(Streamobj186027* s);
N_NIMCALL(NIM_BOOL, fsatend_187012)(Streamobj186027* s);
N_NIMCALL(NIM_BOOL, endoffile_13460)(FILE* f);
N_NIMCALL(void, fssetposition_187019)(Streamobj186027* s, NI pos);
N_NIMCALL(void, setfilepos_13580)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_187026)(Streamobj186027* s);
N_NIMCALL(NI64, getfilepos_13584)(FILE* f);
N_NIMCALL(NI, fsreaddata_187034)(Streamobj186027* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_13553)(FILE* f, void* buffer, NI len);
N_NIMCALL(NI, fspeekdata_187043)(Streamobj186027* s, void* buffer, NI buflen);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, fswritedata_187053)(Streamobj186027* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_13575)(FILE* f, void* buffer, NI len);
N_NIMCALL(Ioerror3431*, neweio_186005)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, fsflush_187006)(Streamobj186027* s);
N_NIMCALL(void, TMP381)(void* p, NI op);
STRING_LITERAL(TMP378, "cannot write to stream", 22);
extern TNimType NTI3411; /* RootObj */
TNimType NTI186027; /* StreamObj */
TNimType NTI186028; /* proc (s: Stream){.gcsafe.} */
TNimType NTI186032; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI186036; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI186041; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI186045; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI186051; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI186057; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI186063; /* proc (s: Stream){.gcsafe.} */
TNimType NTI186984; /* FileStreamObj */
extern TNimType NTI13204; /* File */
TNimType NTI186982; /* FileStream */
extern TSafePoint* exchandler_17043;
extern TNimType NTI212899; /* ref IOError */
extern TNimType NTI3431; /* IOError */
extern Gcheap46616 gch_46648;
TNimType NTI186025; /* Stream */
N_NIMCALL(void, TMP374)(void* p, NI op) {
	Filestreamobj186984* a;
	a = (Filestreamobj186984*)p;
}

N_NIMCALL(void, fsclose_186988)(Streamobj186027* s) {
	{
		if (!!(((*((Filestreamobj186984*) (s))).f == NIM_NIL))) goto LA3;
		fclose((*((Filestreamobj186984*) (s))).f);
		(*((Filestreamobj186984*) (s))).f = NIM_NIL;
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, fsatend_187012)(Streamobj186027* s) {
	NIM_BOOL result;
{	result = 0;
	result = endoffile_13460((*((Filestreamobj186984*) (s))).f);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, fssetposition_187019)(Streamobj186027* s, NI pos) {
	setfilepos_13580((*((Filestreamobj186984*) (s))).f, ((NI64) (pos)));
}

N_NIMCALL(NI, fsgetposition_187026)(Streamobj186027* s) {
	NI result;
	NI64 LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = getfilepos_13584((*((Filestreamobj186984*) (s))).f);
	result = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, fsreaddata_187034)(Streamobj186027* s, void* buffer, NI buflen) {
	NI result;
	result = 0;
	result = readbuffer_13553((*((Filestreamobj186984*) (s))).f, buffer, ((NI) (buflen)));
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_17043;
	exchandler_17043 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_17043 = (*exchandler_17043).prev;
}

N_NIMCALL(NI, fspeekdata_187043)(Streamobj186027* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP377;
	result = 0;
	pos = fsgetposition_187026(s);
	pushSafePoint(&TMP377);
	TMP377.status = setjmp(TMP377.context);
	if (TMP377.status == 0) {
		result = readbuffer_13553((*((Filestreamobj186984*) (s))).f, buffer, ((NI) (buflen)));
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		fssetposition_187019(s, pos);
	}
	if (TMP377.status != 0) reraiseException();
	return result;
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

N_NIMCALL(Ioerror3431*, neweio_186005)(NimStringDesc* msg) {
	Ioerror3431* result;
	NimStringDesc* LOC1;
	result = 0;
	result = (Ioerror3431*) newObj((&NTI212899), sizeof(Ioerror3431));
	(*result).Sup.Sup.Sup.m_type = (&NTI3431);
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	return result;
}

N_NIMCALL(void, fswritedata_187053)(Streamobj186027* s, void* buffer, NI buflen) {
	{
		NI LOC3;
		Ioerror3431* LOC6;
		LOC3 = 0;
		LOC3 = writebuffer_13575((*((Filestreamobj186984*) (s))).f, buffer, ((NI) (buflen)));
		if (!!((LOC3 == buflen))) goto LA4;
		LOC6 = 0;
		LOC6 = neweio_186005(((NimStringDesc*) &TMP378));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
}

N_NIMCALL(void, fsflush_187006)(Streamobj186027* s) {
	fflush((*((Filestreamobj186984*) (s))).f);
}

N_NIMCALL(Filestreamobj186984*, newfilestream_187061)(FILE* f) {
	Filestreamobj186984* result;
	result = 0;
	result = (Filestreamobj186984*) newObj((&NTI186982), sizeof(Filestreamobj186984));
	(*result).Sup.Sup.m_type = (&NTI186984);
	(*result).f = f;
	(*result).Sup.closeimpl = fsclose_186988;
	(*result).Sup.atendimpl = fsatend_187012;
	(*result).Sup.setpositionimpl = fssetposition_187019;
	(*result).Sup.getpositionimpl = fsgetposition_187026;
	(*result).Sup.readdataimpl = fsreaddata_187034;
	(*result).Sup.peekdataimpl = fspeekdata_187043;
	(*result).Sup.writedataimpl = fswritedata_187053;
	(*result).Sup.flushimpl = fsflush_187006;
	return result;
}

N_NIMCALL(Filestreamobj186984*, newfilestream_187076)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj186984* result;
	FILE* f;
	result = 0;
	f = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_13403(&f, filename, mode, ((NI) -1));
		if (!LOC3) goto LA4;
		result = newfilestream_187061(f);
	}
	LA4: ;
	return result;
}
N_NIMCALL(void, TMP381)(void* p, NI op) {
	Streamobj186027* a;
	a = (Streamobj186027*)p;
}

N_NIMCALL(NI, readdata_186180)(Streamobj186027* s, void* buffer, NI buflen) {
	NI result;
	result = 0;
	result = (*s).readdataimpl(s, buffer, buflen);
	return result;
}

N_NIMCALL(void, close_186091)(Streamobj186027* s) {
	{
		if (!!((*s).closeimpl == 0)) goto LA3;
		(*s).closeimpl(s);
	}
	LA3: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit)(void) {
static TNimNode* TMP373[8];
static TNimNode TMP41[10];
NTI186027.size = sizeof(Streamobj186027);
NTI186027.kind = 17;
NTI186027.base = (&NTI3411);
NTI186027.flags = 1;
TMP373[0] = &TMP41[1];
NTI186028.size = sizeof(TY186028);
NTI186028.kind = 25;
NTI186028.base = 0;
NTI186028.flags = 3;
TMP41[1].kind = 1;
TMP41[1].offset = offsetof(Streamobj186027, closeimpl);
TMP41[1].typ = (&NTI186028);
TMP41[1].name = "closeImpl";
TMP373[1] = &TMP41[2];
NTI186032.size = sizeof(TY186032);
NTI186032.kind = 25;
NTI186032.base = 0;
NTI186032.flags = 3;
TMP41[2].kind = 1;
TMP41[2].offset = offsetof(Streamobj186027, atendimpl);
TMP41[2].typ = (&NTI186032);
TMP41[2].name = "atEndImpl";
TMP373[2] = &TMP41[3];
NTI186036.size = sizeof(TY186036);
NTI186036.kind = 25;
NTI186036.base = 0;
NTI186036.flags = 3;
TMP41[3].kind = 1;
TMP41[3].offset = offsetof(Streamobj186027, setpositionimpl);
TMP41[3].typ = (&NTI186036);
TMP41[3].name = "setPositionImpl";
TMP373[3] = &TMP41[4];
NTI186041.size = sizeof(TY186041);
NTI186041.kind = 25;
NTI186041.base = 0;
NTI186041.flags = 3;
TMP41[4].kind = 1;
TMP41[4].offset = offsetof(Streamobj186027, getpositionimpl);
TMP41[4].typ = (&NTI186041);
TMP41[4].name = "getPositionImpl";
TMP373[4] = &TMP41[5];
NTI186045.size = sizeof(TY186045);
NTI186045.kind = 25;
NTI186045.base = 0;
NTI186045.flags = 3;
TMP41[5].kind = 1;
TMP41[5].offset = offsetof(Streamobj186027, readdataimpl);
TMP41[5].typ = (&NTI186045);
TMP41[5].name = "readDataImpl";
TMP373[5] = &TMP41[6];
NTI186051.size = sizeof(TY186051);
NTI186051.kind = 25;
NTI186051.base = 0;
NTI186051.flags = 3;
TMP41[6].kind = 1;
TMP41[6].offset = offsetof(Streamobj186027, peekdataimpl);
TMP41[6].typ = (&NTI186051);
TMP41[6].name = "peekDataImpl";
TMP373[6] = &TMP41[7];
NTI186057.size = sizeof(TY186057);
NTI186057.kind = 25;
NTI186057.base = 0;
NTI186057.flags = 3;
TMP41[7].kind = 1;
TMP41[7].offset = offsetof(Streamobj186027, writedataimpl);
TMP41[7].typ = (&NTI186057);
TMP41[7].name = "writeDataImpl";
TMP373[7] = &TMP41[8];
NTI186063.size = sizeof(TY186063);
NTI186063.kind = 25;
NTI186063.base = 0;
NTI186063.flags = 3;
TMP41[8].kind = 1;
TMP41[8].offset = offsetof(Streamobj186027, flushimpl);
TMP41[8].typ = (&NTI186063);
TMP41[8].name = "flushImpl";
TMP41[0].len = 8; TMP41[0].kind = 2; TMP41[0].sons = &TMP373[0];
NTI186027.node = &TMP41[0];
NTI186984.size = sizeof(Filestreamobj186984);
NTI186984.kind = 17;
NTI186984.base = (&NTI186027);
NTI186984.flags = 1;
TMP41[9].kind = 1;
TMP41[9].offset = offsetof(Filestreamobj186984, f);
TMP41[9].typ = (&NTI13204);
TMP41[9].name = "f";
NTI186984.node = &TMP41[9];
NTI186982.size = sizeof(Filestreamobj186984*);
NTI186982.kind = 22;
NTI186982.base = (&NTI186984);
NTI186982.marker = TMP374;
NTI186025.size = sizeof(Streamobj186027*);
NTI186025.kind = 22;
NTI186025.base = (&NTI186027);
NTI186025.marker = TMP381;
}

