/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/stdlib_httpclient.o /data4/NimStuff/NimFinLib/nimcache/stdlib_httpclient.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct Sslstruct210405 Sslstruct210405;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct ProxyHEX3Aobjecttype250023 ProxyHEX3Aobjecttype250023;
typedef struct Response250008 Response250008;
typedef struct Stringtableobj224012 Stringtableobj224012;
typedef struct Uri220012 Uri220012;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Socketimpl212410 Socketimpl212410;
typedef struct Protocolerror250016 Protocolerror250016;
typedef struct Ioerror3431 Ioerror3431;
typedef struct Systemerror3429 Systemerror3429;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct Slice83964 Slice83964;
typedef struct Httprequesterror250018 Httprequesterror250018;
typedef struct Keyvaluepairseq224010 Keyvaluepairseq224010;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
typedef struct TY100570 TY100570;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Response250008 {
NimStringDesc* Field0;
NimStringDesc* Field1;
Stringtableobj224012* Field2;
NimStringDesc* Field3;
};
struct  Uri220012  {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct  ProxyHEX3Aobjecttype250023  {
Uri220012 url;
NimStringDesc* auth;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3429  {
  Exception Sup;
};
struct  Ioerror3431  {
  Systemerror3429 Sup;
};
struct  Protocolerror250016  {
  Ioerror3431 Sup;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
struct  Slice83964  {
NI a;
NI b;
};
typedef NU8 TY90586[32];
typedef NimStringDesc* TY251249[4];
struct  Httprequesterror250018  {
  Ioerror3431 Sup;
};
struct  Sslstruct210405  {
char dummy;
};
struct  Stringtableobj224012  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq224010* data;
NU8 mode;
};
typedef NIM_CHAR TY212423[4001];
struct  Socketimpl212410  {
int fd;
NIM_BOOL isbuffered;
union{
struct {TY212423 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NIM_BOOL isssl;
union{
struct {Sslstruct210405* sslhandle;
Sslstruct210405* sslcontext;
NIM_BOOL sslnohandshake;
NIM_BOOL sslhaspeekchar;
NIM_CHAR sslpeekchar;
} S1;
} issslU;
NI32 lasterror;
};
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct TY100570 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
struct Keyvaluepairseq224010 {
  TGenericSeq Sup;
  TY100570 data[SEQ_DECL_SIZE];
};
N_NIMCALL(Sslstruct210405*, newcontext_212926)(NU8 protversion, NU8 verifymode, NimStringDesc* certfile, NimStringDesc* keyfile);
N_NIMCALL(NIM_BOOL, open_13403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, write_13495)(FILE* f, NimStringDesc* s);
N_NIMCALL(NimStringDesc*, getcontent_251365)(NimStringDesc* url, NimStringDesc* extraheaders, NI maxredirects, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy);
N_NIMCALL(void, get_251320)(NimStringDesc* url, NimStringDesc* extraheaders, NI maxredirects, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy, Response250008* Result);
N_NIMCALL(void, request_251220)(NimStringDesc* url, NU8 httpmethod, NimStringDesc* extraheaders, NimStringDesc* body, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy, Response250008* Result);
N_NIMCALL(void, request_251070)(NimStringDesc* url, NimStringDesc* httpmethod, NimStringDesc* extraheaders, NimStringDesc* body, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy, Response250008* Result);
N_NIMCALL(void, parseuri_222100)(NimStringDesc* uri, Uri220012* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, encode_226174)(NimStringDesc* s, NI linelen, NimStringDesc* newline);
N_NIMCALL(Socketimpl212410*, newsocket_212830)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
N_NIMCALL(void, raiseoserror_114809)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_114833)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, wrapsocket_213017)(Sslstruct210405* ctx, Socketimpl212410* socket);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(void, connect_214853)(Socketimpl212410* socket, NimStringDesc* address, NU16 port, NU8 af);
N_NIMCALL(void, connect_217618)(Socketimpl212410* socket, NimStringDesc* address, NU16 port, NI timeout, NU8 af);
N_NIMCALL(void, send_217409)(Socketimpl212410* socket, NimStringDesc* data, NU8 flags);
N_NIMCALL(void, parseresponse_250265)(Socketimpl212410* s, NIM_BOOL getbody, NI timeout, Response250008* Result);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(Stringtableobj224012*, nstnewStringTable)(NU8 mode);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, readline_216820)(Socketimpl212410* socket, NimStringDesc** line, NI timeout, NU8 flags);
N_NIMCALL(NI, skipignorecase_90447)(NimStringDesc* s, NimStringDesc* token, NI start);
N_NIMCALL(void, httperror_250048)(NimStringDesc* msg);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP336)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NI, skipwhitespace_90382)(NimStringDesc* s, NI start);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_83957)(NimStringDesc* s, Slice83964 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_74843, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice83964, HEX2EHEX2E_102273)(NI a, NI b);
static N_INLINE(NI, parseuntil_90623)(NimStringDesc* s, NimStringDesc** token, NIM_CHAR until, NI start);
N_NIMCALL(void, nstPut)(Stringtableobj224012* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, TY90586 chars);
N_NIMCALL(NimStringDesc*, parsebody_250216)(Socketimpl212410* s, Stringtableobj224012* headers, NI timeout);
N_NIMCALL(NimStringDesc*, nstGet)(Stringtableobj224012* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, parsechunks_250088)(Socketimpl212410* s, NI timeout);
N_NIMCALL(void, skip_216896)(Socketimpl212410* socket, NI size, NI timeout);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NI, recv_216441)(Socketimpl212410* socket, void* data, NI size, NI timeout);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, close_214617)(Socketimpl212410* socket);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e_80729, TNimType* typ);
N_NIMCALL(NIM_BOOL, redirection_251244)(NimStringDesc* status);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(NimStringDesc*, getnewlocation_251307)(NimStringDesc* lasturl, Stringtableobj224012* headers);
N_NIMCALL(void, TMP370)(void* p, NI op);
N_NIMCALL(void, fileerror_250068)(NimStringDesc* msg);
STRING_LITERAL(TMP134, "", 0);
STRING_LITERAL(TMP283, "?", 1);
STRING_LITERAL(TMP284, " ", 1);
STRING_LITERAL(TMP285, " HTTP/1.1\015\012", 11);
STRING_LITERAL(TMP286, "Host: ", 6);
STRING_LITERAL(TMP287, "\015\012", 2);
STRING_LITERAL(TMP288, "User-Agent: ", 12);
STRING_LITERAL(TMP290, "Proxy-Authorization: basic ", 27);
STRING_LITERAL(TMP295, "https", 5);
STRING_LITERAL(TMP335, "HTTP/", 5);
STRING_LITERAL(TMP337, "invalid http version", 20);
STRING_LITERAL(TMP338, "1.1", 3);
STRING_LITERAL(TMP339, "1.0", 3);
STRING_LITERAL(TMP340, "unsupported http version", 24);
STRING_LITERAL(TMP341, "invalid headers", 15);
static NIM_CONST TY90586 TMP342 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP343, "Connection was closed before full request has been made", 55);
STRING_LITERAL(TMP345, "Transfer-Encoding", 17);
STRING_LITERAL(TMP346, "chunked", 7);
STRING_LITERAL(TMP347, "Server terminated connection prematurely", 40);
STRING_LITERAL(TMP348, "Invalid chunk size: ", 20);
STRING_LITERAL(TMP351, "Content-Length", 14);
STRING_LITERAL(TMP352, "Got invalid content length. Expected: ", 38);
STRING_LITERAL(TMP353, " got: ", 6);
STRING_LITERAL(TMP354, "Connection", 10);
STRING_LITERAL(TMP355, "close", 5);
STRING_LITERAL(TMP356, "httpHEAD", 8);
STRING_LITERAL(TMP363, "301", 3);
STRING_LITERAL(TMP364, "302", 3);
STRING_LITERAL(TMP365, "303", 3);
STRING_LITERAL(TMP366, "307", 3);
NIM_CONST TY251249 redirectionnrs_251248 = {((NimStringDesc*) &TMP363),
((NimStringDesc*) &TMP364),
((NimStringDesc*) &TMP365),
((NimStringDesc*) &TMP366)}
;
STRING_LITERAL(TMP367, "Location", 8);
STRING_LITERAL(TMP368, "location header expected", 24);
STRING_LITERAL(TMP369, "/", 1);
STRING_LITERAL(TMP371, "Unable to open file", 19);
Sslstruct210405* defaultsslcontext_250379;
extern TNimType NTI220012; /* Uri */
extern TNimType NTI3431; /* IOError */
TNimType NTI250016; /* ProtocolError */
TNimType NTI250051; /* ref ProtocolError */
extern Gcheap46616 gch_46648;
TNimType NTI250008; /* Response */
extern TNimType NTI149; /* string */
extern TNimType NTI224014; /* StringTableRef */
TNimType NTI250363; /* HttpMethod */
TNimType NTI250018; /* HttpRequestError */
TNimType NTI251390; /* ref HttpRequestError */
extern TNimType NTI212899; /* ref IOError */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP336)(void* p, NI op) {
	Protocolerror250016* a;
	a = (Protocolerror250016*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

N_NIMCALL(void, httperror_250048)(NimStringDesc* msg) {
	Protocolerror250016* e;
	NimStringDesc* LOC1;
	e = 0;
	e = (Protocolerror250016*) newObj((&NTI250051), sizeof(Protocolerror250016));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI250016);
	LOC1 = 0;
	LOC1 = (*e).Sup.Sup.Sup.message; (*e).Sup.Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((Exception*)e, "ProtocolError");
}

static N_INLINE(NI, skipwhitespace_90382)(NimStringDesc* s, NI start) {
	NI result;
	result = 0;
	{
		while (1) {
			if (!(((NU8)(s->data[(NI)(start + result)])) == ((NU8)(32)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(9)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(11)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(13)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(10)) || ((NU8)(s->data[(NI)(start + result)])) == ((NU8)(12)))) goto LA2;
			result += ((NI) 1);
		} LA2: ;
	}
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_83957)(NimStringDesc* s, Slice83964 x) {
	NimStringDesc* result;
	result = 0;
	result = copyStrLast(s, x.a, x.b);
	return result;
}

static N_INLINE(Slice83964, HEX2EHEX2E_102273)(NI a, NI b) {
	Slice83964 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(NI, parseuntil_90623)(NimStringDesc* s, NimStringDesc** token, NIM_CHAR until, NI start) {
	NI result;
	NI i;
	result = 0;
	i = start;
	{
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = 0;
			LOC3 = (i < (s ? s->Sup.len : 0));
			if (!(LOC3)) goto LA4;
			LOC3 = !(((NU8)(s->data[i]) == (NU8)(until)));
			LA4: ;
			if (!LOC3) goto LA2;
			i += ((NI) 1);
		} LA2: ;
	}
	result = (NI)(i - start);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(i - ((NI) 1))));
	return result;
}

N_NIMCALL(NimStringDesc*, parsechunks_250088)(Socketimpl212410* s, NI timeout) {
	NimStringDesc* result;
	NI ri;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP134));
	ri = ((NI) 0);
	{
		while (1) {
			NimStringDesc* chunksizestr;
			NI chunksize;
			NI i;
			NI bytesread;
			chunksizestr = copyString(((NimStringDesc*) &TMP134));
			chunksize = ((NI) 0);
			readline_216820(s, (&chunksizestr), timeout, 2);
			i = ((NI) 0);
			{
				if (!((chunksizestr) && (chunksizestr)->Sup.len == 0)) goto LA5;
				httperror_250048(((NimStringDesc*) &TMP347));
			}
			LA5: ;
			{
				while (1) {
					switch (((NU8)(chunksizestr->data[i]))) {
					case 48 ... 57:
					{
						chunksize = (NI)((NI)((NU64)(chunksize) << (NU64)(((NI) 4))) | ((NI) ((NI)(((NI) (((NU8)(chunksizestr->data[i])))) - ((NI) 48)))));
					}
					break;
					case 97 ... 102:
					{
						chunksize = (NI)((NI)((NU64)(chunksize) << (NU64)(((NI) 4))) | ((NI) ((NI)(((NI) ((NI)(((NI) (((NU8)(chunksizestr->data[i])))) - ((NI) 97)))) + ((NI) 10)))));
					}
					break;
					case 65 ... 70:
					{
						chunksize = (NI)((NI)((NU64)(chunksize) << (NU64)(((NI) 4))) | ((NI) ((NI)(((NI) ((NI)(((NI) (((NU8)(chunksizestr->data[i])))) - ((NI) 65)))) + ((NI) 10)))));
					}
					break;
					case 0:
					{
						goto LA7;
					}
					break;
					case 59:
					{
						goto LA7;
					}
					break;
					default:
					{
						NimStringDesc* LOC15;
						LOC15 = 0;
						LOC15 = rawNewString(chunksizestr->Sup.len + 20);
appendString(LOC15, ((NimStringDesc*) &TMP348));
appendString(LOC15, chunksizestr);
						httperror_250048(LOC15);
					}
					break;
					}
					i += ((NI) 1);
				}
			} LA7: ;
			{
				if (!(chunksize <= ((NI) 0))) goto LA18;
				skip_216896(s, ((NI) 2), timeout);
				goto LA1;
			}
			LA18: ;
			result = setLengthStr(result, ((NI) ((NI)(ri + chunksize))));
			bytesread = ((NI) 0);
			{
				while (1) {
					NI ret;
					if (!!((bytesread == chunksize))) goto LA21;
					ret = recv_216441(s, ((void*) ((&result->data[ri]))), (NI)(chunksize - bytesread), timeout);
					ri += ret;
					bytesread += ret;
				} LA21: ;
			}
			skip_216896(s, ((NI) 2), timeout);
		}
	} LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, parsebody_250216)(Socketimpl212410* s, Stringtableobj224012* headers, NI timeout) {
	NimStringDesc* result;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP134));
	{
		NimStringDesc* LOC3;
		LOC3 = 0;
		LOC3 = nstGet(headers, ((NimStringDesc*) &TMP345));
		if (!eqStrings(LOC3, ((NimStringDesc*) &TMP346))) goto LA4;
		result = parsechunks_250088(s, timeout);
	}
	goto LA1;
	LA4: ;
	{
		NimStringDesc* contentlengthheader;
		contentlengthheader = nstGet(headers, ((NimStringDesc*) &TMP351));
		{
			NI length;
			if (!!(((contentlengthheader) && (contentlengthheader)->Sup.len == 0))) goto LA9;
			length = nsuParseInt(contentlengthheader);
			{
				NI received;
				if (!(((NI) 0) < length)) goto LA13;
				result = mnewString(((NI) (length)));
				received = ((NI) 0);
				{
					while (1) {
						NI r;
						{
							if (!(length <= received)) goto LA19;
							goto LA15;
						}
						LA19: ;
						r = recv_216441(s, ((void*) ((&result->data[received]))), (NI)(length - received), timeout);
						{
							if (!(r == ((NI) 0))) goto LA23;
							goto LA15;
						}
						LA23: ;
						received += r;
					}
				} LA15: ;
				{
					NimStringDesc* LOC29;
					NimStringDesc* LOC30;
					NimStringDesc* LOC31;
					if (!!((received == length))) goto LA27;
					LOC29 = 0;
					LOC30 = 0;
					LOC30 = nimIntToStr(length);
					LOC31 = 0;
					LOC31 = nimIntToStr(received);
					LOC29 = rawNewString(LOC30->Sup.len + LOC31->Sup.len + 44);
appendString(LOC29, ((NimStringDesc*) &TMP352));
appendString(LOC29, LOC30);
appendString(LOC29, ((NimStringDesc*) &TMP353));
appendString(LOC29, LOC31);
					httperror_250048(LOC29);
				}
				LA27: ;
			}
			LA13: ;
		}
		goto LA7;
		LA9: ;
		{
			{
				NimStringDesc* LOC35;
				NimStringDesc* buf;
				LOC35 = 0;
				LOC35 = nstGet(headers, ((NimStringDesc*) &TMP354));
				if (!eqStrings(LOC35, ((NimStringDesc*) &TMP355))) goto LA36;
				buf = copyString(((NimStringDesc*) &TMP134));
				{
					while (1) {
						NI r;
						buf = mnewString(((NI) 4000));
						r = recv_216441(s, ((void*) ((&buf->data[((NI) 0)]))), ((NI) 4000), timeout);
						{
							if (!(r == ((NI) 0))) goto LA42;
							goto LA38;
						}
						LA42: ;
						buf = setLengthStr(buf, ((NI) (r)));
						result = resizeString(result, buf->Sup.len + 0);
appendString(result, buf);
					}
				} LA38: ;
			}
			LA36: ;
		}
		LA7: ;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, parseresponse_250265)(Socketimpl212410* s, NIM_BOOL getbody, NI timeout, Response250008* Result) {
	NIM_BOOL parsedstatus;
	NI linei;
	NIM_BOOL fullyread;
	NimStringDesc* line;
	parsedstatus = NIM_FALSE;
	linei = ((NI) 0);
	fullyread = NIM_FALSE;
	line = copyString(((NimStringDesc*) &TMP134));
	unsureAsgnRef((void**) (&(*Result).Field2), nstnewStringTable(((NU8) 1)));
	{
		while (1) {
			line = copyString(((NimStringDesc*) &TMP134));
			linei = ((NI) 0);
			readline_216820(s, (&line), timeout, 2);
			{
				if (!((line) && (line)->Sup.len == 0)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!eqStrings(line, ((NimStringDesc*) &TMP287))) goto LA9;
				fullyread = NIM_TRUE;
				goto LA1;
			}
			LA9: ;
			{
				NI le;
				NI LOC28;
				Slice83964 LOC29;
				if (!!(parsedstatus)) goto LA13;
				le = skipignorecase_90447(line, ((NimStringDesc*) &TMP335), linei);
				{
					if (!(le <= ((NI) 0))) goto LA17;
					httperror_250048(((NimStringDesc*) &TMP337));
				}
				LA17: ;
				linei += le;
				le = skipignorecase_90447(line, ((NimStringDesc*) &TMP338), linei);
				{
					if (!(((NI) 0) < le)) goto LA21;
					unsureAsgnRef((void**) (&(*Result).Field0), copyString(((NimStringDesc*) &TMP338)));
				}
				goto LA19;
				LA21: ;
				{
					le = skipignorecase_90447(line, ((NimStringDesc*) &TMP339), linei);
					{
						if (!(le <= ((NI) 0))) goto LA26;
						httperror_250048(((NimStringDesc*) &TMP340));
					}
					LA26: ;
					unsureAsgnRef((void**) (&(*Result).Field0), copyString(((NimStringDesc*) &TMP339)));
				}
				LA19: ;
				linei += le;
				LOC28 = 0;
				LOC28 = skipwhitespace_90382(line, linei);
				linei += LOC28;
				LOC29 = HEX2EHEX2E_102273(linei, (NI)((line ? line->Sup.len : 0) - ((NI) 1)));
				unsureAsgnRef((void**) (&(*Result).Field1), HEX5BHEX5D_83957(line, LOC29));
				parsedstatus = NIM_TRUE;
			}
			goto LA11;
			LA13: ;
			{
				NimStringDesc* name;
				NI le;
				Slice83964 LOC39;
				NimStringDesc* LOC40;
				NimStringDesc* LOC41;
				name = copyString(((NimStringDesc*) &TMP134));
				le = parseuntil_90623(line, (&name), 58, linei);
				{
					if (!(le <= ((NI) 0))) goto LA33;
					httperror_250048(((NimStringDesc*) &TMP341));
				}
				LA33: ;
				linei += le;
				{
					if (!!(((NU8)(line->data[linei]) == (NU8)(58)))) goto LA37;
					httperror_250048(((NimStringDesc*) &TMP341));
				}
				LA37: ;
				linei += ((NI) 1);
				LOC39 = HEX2EHEX2E_102273(linei, (NI)((line ? line->Sup.len : 0) - ((NI) 1)));
				LOC40 = 0;
				LOC40 = HEX5BHEX5D_83957(line, LOC39);
				LOC41 = 0;
				LOC41 = nsuStrip(LOC40, NIM_TRUE, NIM_TRUE, TMP342);
				nstPut((*Result).Field2, name, LOC41);
			}
			LA11: ;
		}
	} LA1: ;
	{
		if (!!(fullyread)) goto LA44;
		httperror_250048(((NimStringDesc*) &TMP343));
	}
	LA44: ;
	{
		if (!getbody) goto LA48;
		unsureAsgnRef((void**) (&(*Result).Field3), parsebody_250216(s, (*Result).Field2, timeout));
	}
	goto LA46;
	LA48: ;
	{
		unsureAsgnRef((void**) (&(*Result).Field3), copyString(((NimStringDesc*) &TMP134)));
	}
	LA46: ;
}

N_NIMCALL(void, request_251070)(NimStringDesc* url, NimStringDesc* httpmethod, NimStringDesc* extraheaders, NimStringDesc* body, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy, Response250008* Result) {
	Uri220012 r;
	NimStringDesc* headers;
	NimStringDesc* LOC21;
	Socketimpl212410* s;
	NU16 port;
	memset((void*)(&r), 0, sizeof(r));
	{
		if (!(proxy == NIM_NIL)) goto LA3;
		chckNil((void*)(&r));
		memset((void*)(&r), 0, sizeof(r));
		parseuri_222100(url, (&r));
	}
	goto LA1;
	LA3: ;
	{
		genericAssign((void*)(&r), (void*)(&(*proxy).url), (&NTI220012));
	}
	LA1: ;
	headers = copyStr(httpmethod, ((NI) 4));
	{
		if (!(proxy == NIM_NIL)) goto LA8;
		headers = addChar(headers, 32);
		{
			if (!!(((NU8)(r.path->data[((NI) 0)]) == (NU8)(47)))) goto LA12;
			headers = addChar(headers, 47);
		}
		LA12: ;
		headers = resizeString(headers, r.path->Sup.len + 0);
appendString(headers, r.path);
		{
			NimStringDesc* LOC18;
			if (!(((NI) 0) < (r.query ? r.query->Sup.len : 0))) goto LA16;
			LOC18 = 0;
			LOC18 = rawNewString(r.query->Sup.len + 1);
appendString(LOC18, ((NimStringDesc*) &TMP283));
appendString(LOC18, r.query);
			headers = resizeString(headers, LOC18->Sup.len + 0);
appendString(headers, LOC18);
		}
		LA16: ;
	}
	goto LA6;
	LA8: ;
	{
		NimStringDesc* LOC20;
		LOC20 = 0;
		LOC20 = rawNewString(url->Sup.len + 1);
appendString(LOC20, ((NimStringDesc*) &TMP284));
appendString(LOC20, url);
		headers = resizeString(headers, LOC20->Sup.len + 0);
appendString(headers, LOC20);
	}
	LA6: ;
	headers = resizeString(headers, 11);
appendString(headers, ((NimStringDesc*) &TMP285));
	LOC21 = 0;
	LOC21 = rawNewString(r.hostname->Sup.len + 8);
appendString(LOC21, ((NimStringDesc*) &TMP286));
appendString(LOC21, r.hostname);
appendString(LOC21, ((NimStringDesc*) &TMP287));
	headers = resizeString(headers, LOC21->Sup.len + 0);
appendString(headers, LOC21);
	{
		NimStringDesc* LOC26;
		if (!!(((useragent) && (useragent)->Sup.len == 0))) goto LA24;
		LOC26 = 0;
		LOC26 = rawNewString(useragent->Sup.len + 14);
appendString(LOC26, ((NimStringDesc*) &TMP288));
appendString(LOC26, useragent);
appendString(LOC26, ((NimStringDesc*) &TMP287));
		headers = resizeString(headers, LOC26->Sup.len + 0);
appendString(headers, LOC26);
	}
	LA24: ;
	{
		NIM_BOOL LOC29;
		NimStringDesc* auth;
		NimStringDesc* LOC33;
		LOC29 = 0;
		LOC29 = !((proxy == NIM_NIL));
		if (!(LOC29)) goto LA30;
		LOC29 = !((((*proxy).auth) && ((*proxy).auth)->Sup.len == 0));
		LA30: ;
		if (!LOC29) goto LA31;
		auth = encode_226174((*proxy).auth, ((NI) 75), ((NimStringDesc*) &TMP134));
		LOC33 = 0;
		LOC33 = rawNewString(auth->Sup.len + 29);
appendString(LOC33, ((NimStringDesc*) &TMP290));
appendString(LOC33, auth);
appendString(LOC33, ((NimStringDesc*) &TMP287));
		headers = resizeString(headers, LOC33->Sup.len + 0);
appendString(headers, LOC33);
	}
	LA31: ;
	headers = resizeString(headers, extraheaders->Sup.len + 0);
appendString(headers, extraheaders);
	headers = resizeString(headers, 2);
appendString(headers, ((NimStringDesc*) &TMP287));
	s = newsocket_212830(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE);
	{
		NI32 LOC38;
		if (!(s == NIM_NIL)) goto LA36;
		LOC38 = 0;
		LOC38 = oslasterror_114833();
		raiseoserror_114809(LOC38);
	}
	LA36: ;
	port = ((NU16) 80);
	{
		if (!eqStrings(r.scheme, ((NimStringDesc*) &TMP295))) goto LA41;
		wrapsocket_213017(sslcontext, s);
		port = ((NU16) 443);
	}
	LA41: ;
	{
		NI LOC47;
		if (!!(((r.port) && (r.port)->Sup.len == 0))) goto LA45;
		LOC47 = 0;
		LOC47 = nsuParseInt(r.port);
		port = ((NU16) (LOC47));
	}
	LA45: ;
	{
		if (!(timeout == ((NI) -1))) goto LA50;
		connect_214853(s, r.hostname, port, ((NU8) 2));
	}
	goto LA48;
	LA50: ;
	{
		connect_217618(s, r.hostname, port, timeout, ((NU8) 2));
	}
	LA48: ;
	send_217409(s, headers, 2);
	{
		if (!!(((body) && (body)->Sup.len == 0))) goto LA55;
		send_217409(s, body, 2);
	}
	LA55: ;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI250008));
	parseresponse_250265(s, !(eqStrings(httpmethod, ((NimStringDesc*) &TMP356))), timeout, Result);
	close_214617(s);
}

N_NIMCALL(void, request_251220)(NimStringDesc* url, NU8 httpmethod, NimStringDesc* extraheaders, NimStringDesc* body, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy, Response250008* Result) {
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI250008));
	request_251070(url, reprEnum(httpmethod, (&NTI250363)), extraheaders, body, sslcontext, timeout, useragent, proxy, Result);
}

N_NIMCALL(NIM_BOOL, redirection_251244)(NimStringDesc* status) {
	NIM_BOOL result;
{	result = 0;
	{
		NimStringDesc* i_251287;
		NI i_251291;
		i_251287 = 0;
		i_251291 = ((NI) 0);
		{
			if (!(((NI) (i_251291)) <= ((NI) 3))) goto LA4;
			{
				while (1) {
					i_251287 = redirectionnrs_251248[(i_251291)- 0];
					{
						NIM_BOOL LOC10;
						LOC10 = 0;
						LOC10 = nsuStartsWith(status, i_251287);
						if (!LOC10) goto LA11;
						result = NIM_TRUE;
						goto BeforeRet;
					}
					LA11: ;
					{
						if (!(((NI) 3) <= ((NI) (i_251291)))) goto LA15;
						goto LA6;
					}
					LA15: ;
					i_251291 += ((NI) 1);
				}
			} LA6: ;
		}
		LA4: ;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, getnewlocation_251307)(NimStringDesc* lasturl, Stringtableobj224012* headers) {
	NimStringDesc* result;
	Uri220012 r;
	result = 0;
	result = nstGet(headers, ((NimStringDesc*) &TMP367));
	{
		if (!((result) && (result)->Sup.len == 0)) goto LA3;
		httperror_250048(((NimStringDesc*) &TMP368));
	}
	LA3: ;
	memset((void*)(&r), 0, sizeof(r));
	chckNil((void*)(&r));
	memset((void*)(&r), 0, sizeof(r));
	parseuri_222100(result, (&r));
	{
		NIM_BOOL LOC7;
		Uri220012 origparsed;
		NimStringDesc* LOC11;
		LOC7 = 0;
		LOC7 = ((r.hostname) && (r.hostname)->Sup.len == 0);
		if (!(LOC7)) goto LA8;
		LOC7 = !(((r.path) && (r.path)->Sup.len == 0));
		LA8: ;
		if (!LOC7) goto LA9;
		memset((void*)(&origparsed), 0, sizeof(origparsed));
		chckNil((void*)(&origparsed));
		memset((void*)(&origparsed), 0, sizeof(origparsed));
		parseuri_222100(lasturl, (&origparsed));
		LOC11 = 0;
		LOC11 = rawNewString(origparsed.hostname->Sup.len + r.path->Sup.len + 1);
appendString(LOC11, origparsed.hostname);
appendString(LOC11, ((NimStringDesc*) &TMP369));
appendString(LOC11, r.path);
		result = LOC11;
	}
	LA9: ;
	return result;
}

N_NIMCALL(void, get_251320)(NimStringDesc* url, NimStringDesc* extraheaders, NI maxredirects, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy, Response250008* Result) {
	NimStringDesc* lasturl;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI250008));
	request_251220(url, ((NU8) 1), extraheaders, ((NimStringDesc*) &TMP134), sslcontext, timeout, useragent, proxy, Result);
	lasturl = copyString(url);
	{
		NI i_251341;
		NI res_251346;
		i_251341 = 0;
		res_251346 = ((NI) 1);
		{
			while (1) {
				if (!(res_251346 <= maxredirects)) goto LA3;
				i_251341 = res_251346;
				{
					NIM_BOOL LOC6;
					NimStringDesc* redirectto;
					LOC6 = 0;
					LOC6 = redirection_251244((*Result).Field1);
					if (!LOC6) goto LA7;
					redirectto = getnewlocation_251307(lasturl, (*Result).Field2);
					chckNil((void*)Result);
					genericReset((void*)Result, (&NTI250008));
					request_251220(redirectto, ((NU8) 1), extraheaders, ((NimStringDesc*) &TMP134), sslcontext, timeout, useragent, proxy, Result);
					lasturl = copyString(redirectto);
				}
				LA7: ;
				res_251346 += ((NI) 1);
			} LA3: ;
		}
	}
}
N_NIMCALL(void, TMP370)(void* p, NI op) {
	Httprequesterror250018* a;
	a = (Httprequesterror250018*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
}

N_NIMCALL(NimStringDesc*, getcontent_251365)(NimStringDesc* url, NimStringDesc* extraheaders, NI maxredirects, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy) {
	NimStringDesc* result;
	Response250008 r;
{	result = 0;
	memset((void*)(&r), 0, sizeof(r));
	chckNil((void*)(&r));
	memset((void*)(&r), 0, sizeof(r));
	get_251320(url, extraheaders, maxredirects, sslcontext, timeout, useragent, proxy, (&r));
	{
		Httprequesterror250018* e_251389;
		NimStringDesc* LOC5;
		if (!(((NU8)(r.Field1->data[((NI) 0)])) == ((NU8)(52)) || ((NU8)(r.Field1->data[((NI) 0)])) == ((NU8)(53)))) goto LA3;
		e_251389 = 0;
		e_251389 = (Httprequesterror250018*) newObj((&NTI251390), sizeof(Httprequesterror250018));
		(*e_251389).Sup.Sup.Sup.Sup.m_type = (&NTI250018);
		LOC5 = 0;
		LOC5 = (*e_251389).Sup.Sup.Sup.message; (*e_251389).Sup.Sup.Sup.message = copyStringRC1(r.Field1);
		if (LOC5) nimGCunrefNoCycle(LOC5);
		raiseException((Exception*)e_251389, "HttpRequestError");
	}
	goto LA1;
	LA3: ;
	{
		result = copyString(r.Field3);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, fileerror_250068)(NimStringDesc* msg) {
	Ioerror3431* e;
	NimStringDesc* LOC1;
	e = 0;
	e = (Ioerror3431*) newObj((&NTI212899), sizeof(Ioerror3431));
	(*e).Sup.Sup.Sup.m_type = (&NTI3431);
	LOC1 = 0;
	LOC1 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((Exception*)e, "IOError");
}

N_NIMCALL(void, downloadfile_251509)(NimStringDesc* url, NimStringDesc* outputfilename, Sslstruct210405* sslcontext, NI timeout, NimStringDesc* useragent, ProxyHEX3Aobjecttype250023* proxy) {
	FILE* f;
	f = 0;
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = open_13403(&f, outputfilename, ((NU8) 1), ((NI) -1));
		if (!LOC3) goto LA4;
		LOC6 = 0;
		LOC6 = getcontent_251365(url, ((NimStringDesc*) &TMP134), ((NI) 5), sslcontext, timeout, useragent, proxy);
		write_13495(f, LOC6);
		fclose(f);
	}
	goto LA1;
	LA4: ;
	{
		fileerror_250068(((NimStringDesc*) &TMP371));
	}
	LA1: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientInit)(void) {
	defaultsslcontext_250379 = newcontext_212926(((NU8) 3), ((NU8) 0), ((NimStringDesc*) &TMP134), ((NimStringDesc*) &TMP134));
}

NIM_EXTERNC N_NOINLINE(void, stdlib_httpclientDatInit)(void) {
static TNimNode* TMP357[4];
static TNimNode* TMP359[8];
NI TMP361;
static char* NIM_CONST TMP360[8] = {
"httpHEAD", 
"httpGET", 
"httpPOST", 
"httpPUT", 
"httpDELETE", 
"httpTRACE", 
"httpOPTIONS", 
"httpCONNECT"};
static TNimNode TMP80[16];
NTI250016.size = sizeof(Protocolerror250016);
NTI250016.kind = 17;
NTI250016.base = (&NTI3431);
TMP80[0].len = 0; TMP80[0].kind = 2;
NTI250016.node = &TMP80[0];
NTI250051.size = sizeof(Protocolerror250016*);
NTI250051.kind = 22;
NTI250051.base = (&NTI250016);
NTI250051.marker = TMP336;
NTI250008.size = sizeof(Response250008);
NTI250008.kind = 18;
NTI250008.base = 0;
TMP357[0] = &TMP80[2];
TMP80[2].kind = 1;
TMP80[2].offset = offsetof(Response250008, Field0);
TMP80[2].typ = (&NTI149);
TMP80[2].name = "Field0";
TMP357[1] = &TMP80[3];
TMP80[3].kind = 1;
TMP80[3].offset = offsetof(Response250008, Field1);
TMP80[3].typ = (&NTI149);
TMP80[3].name = "Field1";
TMP357[2] = &TMP80[4];
TMP80[4].kind = 1;
TMP80[4].offset = offsetof(Response250008, Field2);
TMP80[4].typ = (&NTI224014);
TMP80[4].name = "Field2";
TMP357[3] = &TMP80[5];
TMP80[5].kind = 1;
TMP80[5].offset = offsetof(Response250008, Field3);
TMP80[5].typ = (&NTI149);
TMP80[5].name = "Field3";
TMP80[1].len = 4; TMP80[1].kind = 2; TMP80[1].sons = &TMP357[0];
NTI250008.node = &TMP80[1];
NTI250363.size = sizeof(NU8);
NTI250363.kind = 14;
NTI250363.base = 0;
NTI250363.flags = 3;
for (TMP361 = 0; TMP361 < 8; TMP361++) {
TMP80[TMP361+6].kind = 1;
TMP80[TMP361+6].offset = TMP361;
TMP80[TMP361+6].name = TMP360[TMP361];
TMP359[TMP361] = &TMP80[TMP361+6];
}
TMP80[14].len = 8; TMP80[14].kind = 2; TMP80[14].sons = &TMP359[0];
NTI250363.node = &TMP80[14];
NTI250018.size = sizeof(Httprequesterror250018);
NTI250018.kind = 17;
NTI250018.base = (&NTI3431);
TMP80[15].len = 0; TMP80[15].kind = 2;
NTI250018.node = &TMP80[15];
NTI251390.size = sizeof(Httprequesterror250018*);
NTI251390.kind = 22;
NTI251390.base = (&NTI250018);
NTI251390.marker = TMP370;
}

