/* Generated by Nim Compiler v0.11.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -Os  -I/data4/NimCompiler/Nim/lib -o /data4/NimStuff/NimFinLib/nimcache/strfmt.o /data4/NimStuff/NimFinLib/nimcache/strfmt.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <math.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Format188215 Format188215;
typedef struct Formaterror188205 Formaterror188205;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell44747 Cell44747;
typedef struct Cellseq44763 Cellseq44763;
typedef struct Gcheap46616 Gcheap46616;
typedef struct Cellset44759 Cellset44759;
typedef struct Pagedesc44755 Pagedesc44755;
typedef struct Memregion26610 Memregion26610;
typedef struct Smallchunk25843 Smallchunk25843;
typedef struct Llchunk26604 Llchunk26604;
typedef struct Bigchunk25845 Bigchunk25845;
typedef struct Intset25817 Intset25817;
typedef struct Trunk25813 Trunk25813;
typedef struct Avlnode26608 Avlnode26608;
typedef struct Gcstat46614 Gcstat46614;
typedef struct TY188433 TY188433;
typedef struct Slice83964 Slice83964;
typedef struct Basechunk25841 Basechunk25841;
typedef struct Freecell25833 Freecell25833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Format188215 {
NU8 Field0;
NI Field1;
NI Field2;
NimStringDesc* Field3;
NU8 Field4;
NU8 Field5;
NIM_BOOL Field6;
NIM_BOOL Field7;
NIM_BOOL Field8;
NimStringDesc* Field9;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Formaterror188205  {
  Exception Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell44747  {
NI refcount;
TNimType* typ;
};
struct  Cellseq44763  {
NI len;
NI cap;
Cell44747** d;
};
struct  Cellset44759  {
NI counter;
NI max;
Pagedesc44755* head;
Pagedesc44755** data;
};
typedef Smallchunk25843* TY26622[512];
typedef Trunk25813* Trunkbuckets25815[256];
struct  Intset25817  {
Trunkbuckets25815 data;
};
struct  Memregion26610  {
NI minlargeobj;
NI maxlargeobj;
TY26622 freesmallchunks;
Llchunk26604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk25845* freechunkslist;
Intset25817 chunkstarts;
Avlnode26608* root;
Avlnode26608* deleted;
Avlnode26608* last;
Avlnode26608* freeavlnodes;
};
struct  Gcstat46614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap46616  {
void* stackbottom;
NI cyclethreshold;
Cellseq44763 zct;
Cellseq44763 decstack;
Cellset44759 cycleroots;
Cellseq44763 tempstack;
NI recgclock;
Memregion26610 region;
Gcstat46614 stat;
};
struct TY188433 {
NI Field0;
NI Field1;
};
typedef NIM_CHAR TY265681[32];
struct  Slice83964  {
NI a;
NI b;
};
typedef NIM_CHAR TY265721[3];
typedef NF TY188265[8];
typedef NI TY25820[8];
struct  Pagedesc44755  {
Pagedesc44755* next;
NI key;
TY25820 bits;
};
struct  Basechunk25841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk25843  {
  Basechunk25841 Sup;
Smallchunk25843* next;
Smallchunk25843* prev;
Freecell25833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk26604  {
NI size;
NI acc;
Llchunk26604* next;
};
struct  Bigchunk25845  {
  Basechunk25841 Sup;
Bigchunk25845* next;
Bigchunk25845* prev;
NI align;
NF data;
};
struct  Trunk25813  {
Trunk25813* next;
NI key;
TY25820 bits;
};
typedef Avlnode26608* TY26614[2];
struct  Avlnode26608  {
TY26614 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell25833  {
Freecell25833* next;
NI zerofield;
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP244)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell44747*, usrtocell_48246)(void* usr);
static N_INLINE(void, rtladdzct_49804)(Cell44747* c);
N_NOINLINE(void, addzct_48217)(Cellseq44763* s, Cell44747* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, nucruneLen)(NimStringDesc* s);
N_NIMCALL(TY188433, getalign_188428)(Format188215* fmt, NU8 defalign, NI slen);
N_NIMCALL(void, writefill_261204)(NimStringDesc** o, Format188215* fmt, NI n, NI signum);
N_NIMCALL(void, write_188278)(NimStringDesc** s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NI, runelenat_146234)(NimStringDesc* s, NI i);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NU8, classify_142426)(NF x);
static N_INLINE(void, HEX2AHEX3D_265699)(NF* x, NF y);
N_NIMCALL(void, HEX5BHEX5DHEX3D_265725)(NIM_CHAR* a, Slice83964 x, NIM_CHAR* b, NI bLen0);
static N_INLINE(Slice83964, HEX2EHEX2E_102273)(NI a, NI b);
static N_INLINE(void, HEX2FHEX3D_84502)(NF* x, NF y);
static N_INLINE(void, HEX2BHEX3D_100688)(NF* x, NF y);
static N_INLINE(void, HEX2AHEX3D_266000)(NI64* x, NI64 y);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, skipuntil_90514)(NimStringDesc* s, NIM_CHAR until, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_74843, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void, writeformat_261004)(NimStringDesc** o, NimStringDesc* s, Format188215* fmt);
N_NIMCALL(void, writeformat_265604)(NimStringDesc** o, NF x, Format188215* fmt_265614);
STRING_LITERAL(TMP245, "String variable must have \'s\' format type", 41);
STRING_LITERAL(TMP452, "Integer variable must of one of the following types: f,F,e,E,g,"
"G,%", 66);
NIM_CONST TY265721 TMP455 = {110,
97,
110}
;
NIM_CONST TY265721 TMP456 = {102,
110,
105}
;
NIM_CONST TY188265 roundnums_188264 = {5.0000000000000000e-01,
5.0000000000000003e-02,
5.0000000000000001e-03,
5.0000000000000001e-04,
5.0000000000000002e-05,
5.0000000000000004e-06,
4.9999999999999998e-07,
4.9999999999999998e-08}
;
STRING_LITERAL(TMP542, "\011", 1);
STRING_LITERAL(TMP543, "", 0);
extern TNimType NTI3427; /* Exception */
TNimType NTI188205; /* FormatError */
TNimType NTI261027; /* ref FormatError */
extern Gcheap46616 gch_46648;
TNimType NTI188215; /* Format */
TNimType NTI188213; /* FmtType */
extern TNimType NTI108; /* int */
extern TNimType NTI149; /* string */
TNimType NTI188209; /* FmtAlign */
TNimType NTI188211; /* FmtSign */
extern TNimType NTI138; /* bool */
N_NIMCALL(void, TMP244)(void* p, NI op) {
	Formaterror188205* a;
	a = (Formaterror188205*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(Cell44747*, usrtocell_48246)(void* usr) {
	Cell44747* result;
	result = 0;
	result = ((Cell44747*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell44747))))));
	return result;
}

static N_INLINE(void, rtladdzct_49804)(Cell44747* c) {
	addzct_48217((&gch_46648.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell44747* c;
	c = usrtocell_48246(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_49804(c);
	}
	LA3: ;
}

N_NIMCALL(TY188433, getalign_188428)(Format188215* fmt, NU8 defalign, NI slen) {
	TY188433 result;
	memset((void*)(&result), 0, sizeof(result));
	result.Field0 = ((NI) 0);
	result.Field1 = ((NI) 0);
	{
		NIM_BOOL LOC3;
		NU8 alg;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (*fmt).Field2);
		if (!(LOC3)) goto LA4;
		LOC3 = (slen < (*fmt).Field2);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			if (!((*fmt).Field4 == ((NU8) 0))) goto LA9;
			alg = defalign;
		}
		goto LA7;
		LA9: ;
		{
			alg = (*fmt).Field4;
		}
		LA7: ;
		switch (alg) {
		case ((NU8) 1):
		{
			result.Field1 = (NI)((*fmt).Field2 - slen);
		}
		break;
		case ((NU8) 2):
		case ((NU8) 4):
		{
			result.Field0 = (NI)((*fmt).Field2 - slen);
		}
		break;
		case ((NU8) 3):
		{
			result.Field0 = (NI)((NI)((*fmt).Field2 - slen) / ((NI) 2));
			result.Field1 = (NI)((NI)((*fmt).Field2 - slen) - result.Field0);
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA5: ;
	return result;
}

N_NIMCALL(void, write_188278)(NimStringDesc** s, NIM_CHAR c) {
	(*s) = addChar((*s), c);
}

N_NIMCALL(void, writefill_261204)(NimStringDesc** o, Format188215* fmt, NI n, NI signum) {
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ((*fmt).Field4 == ((NU8) 4));
		if (!(LOC3)) goto LA4;
		LOC3 = !((signum == ((NI) 0)));
		LA4: ;
		if (!LOC3) goto LA5;
		{
			if (!(signum < ((NI) 0))) goto LA9;
			write_188278(o, 45);
		}
		goto LA7;
		LA9: ;
		{
			if (!((*fmt).Field5 == ((NU8) 1))) goto LA12;
			write_188278(o, 43);
		}
		goto LA7;
		LA12: ;
		{
			if (!((*fmt).Field5 == ((NU8) 2))) goto LA15;
			write_188278(o, 32);
		}
		goto LA7;
		LA15: ;
		LA7: ;
	}
	LA5: ;
	{
		if (!((*fmt).Field3 == NIM_NIL)) goto LA19;
		{
			NI i_261253;
			NI res_261296;
			i_261253 = 0;
			res_261296 = ((NI) 1);
			{
				while (1) {
					if (!(res_261296 <= n)) goto LA23;
					i_261253 = res_261296;
					write_188278(o, 32);
					res_261296 += ((NI) 1);
				} LA23: ;
			}
		}
	}
	goto LA17;
	LA19: ;
	{
		{
			NI i_261264;
			NI res_261310;
			i_261264 = 0;
			res_261310 = ((NI) 1);
			{
				while (1) {
					if (!(res_261310 <= n)) goto LA27;
					i_261264 = res_261310;
					{
						NIM_CHAR c_261265;
						NimStringDesc* HEX3Atmp_261302;
						NI i_261305;
						NI L_261307;
						c_261265 = 0;
						HEX3Atmp_261302 = 0;
						HEX3Atmp_261302 = (*fmt).Field3;
						i_261305 = ((NI) 0);
						L_261307 = (HEX3Atmp_261302 ? HEX3Atmp_261302->Sup.len : 0);
						{
							while (1) {
								if (!(i_261305 < L_261307)) goto LA30;
								c_261265 = HEX3Atmp_261302->data[i_261305];
								write_188278(o, c_261265);
								i_261305 += ((NI) 1);
							} LA30: ;
						}
					}
					res_261310 += ((NI) 1);
				} LA27: ;
			}
		}
	}
	LA17: ;
	{
		NIM_BOOL LOC33;
		LOC33 = 0;
		LOC33 = !(((*fmt).Field4 == ((NU8) 4)));
		if (!(LOC33)) goto LA34;
		LOC33 = !((signum == ((NI) 0)));
		LA34: ;
		if (!LOC33) goto LA35;
		{
			if (!(signum < ((NI) 0))) goto LA39;
			write_188278(o, 45);
		}
		goto LA37;
		LA39: ;
		{
			if (!((*fmt).Field5 == ((NU8) 1))) goto LA42;
			write_188278(o, 43);
		}
		goto LA37;
		LA42: ;
		{
			if (!((*fmt).Field5 == ((NU8) 2))) goto LA45;
			write_188278(o, 32);
		}
		goto LA37;
		LA45: ;
		LA37: ;
	}
	LA35: ;
}

N_NIMCALL(void, writeformat_261004)(NimStringDesc** o, NimStringDesc* s, Format188215* fmt) {
	NI len;
	TY188433 alg;
	NI pos;
	{
		Formaterror188205* e_261026;
		NimStringDesc* LOC5;
		if (!!(((3 &(1<<(((*fmt).Field0)&15)))!=0))) goto LA3;
		e_261026 = 0;
		e_261026 = (Formaterror188205*) newObj((&NTI261027), sizeof(Formaterror188205));
		(*e_261026).Sup.Sup.m_type = (&NTI188205);
		LOC5 = 0;
		LOC5 = (*e_261026).Sup.message; (*e_261026).Sup.message = copyStringRC1(((NimStringDesc*) &TMP245));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		raiseException((Exception*)e_261026, "FormatError");
	}
	LA3: ;
	{
		if (!((*fmt).Field1 < ((NI) 0))) goto LA8;
		len = nucruneLen(s);
	}
	goto LA6;
	LA8: ;
	{
		NI LOC11;
		LOC11 = 0;
		LOC11 = nucruneLen(s);
		len = ((LOC11 <= (*fmt).Field1) ? LOC11 : (*fmt).Field1);
	}
	LA6: ;
	alg = getalign_188428(fmt, ((NU8) 1), len);
	writefill_261204(o, fmt, alg.Field0, ((NI) 0));
	pos = ((NI) 0);
	{
		NI i_261355;
		NI HEX3Atmp_261626;
		NI res_261629;
		i_261355 = 0;
		HEX3Atmp_261626 = 0;
		HEX3Atmp_261626 = (NI)(len - ((NI) 1));
		res_261629 = ((NI) 0);
		{
			while (1) {
				NI rlen;
				if (!(res_261629 <= HEX3Atmp_261626)) goto LA14;
				i_261355 = res_261629;
				rlen = runelenat_146234(s, ((NI) (pos)));
				{
					NI j_261367;
					NI HEX3Atmp_261619;
					NI res_261622;
					j_261367 = 0;
					HEX3Atmp_261619 = 0;
					HEX3Atmp_261619 = (NI)((NI)(pos + rlen) - ((NI) 1));
					res_261622 = pos;
					{
						while (1) {
							if (!(res_261622 <= HEX3Atmp_261619)) goto LA17;
							j_261367 = res_261622;
							write_188278(o, s->data[j_261367]);
							res_261622 += ((NI) 1);
						} LA17: ;
					}
				}
				pos += rlen;
				res_261629 += ((NI) 1);
			} LA14: ;
		}
	}
	writefill_261204(o, fmt, alg.Field1, ((NI) 0));
}

static N_INLINE(void, HEX2AHEX3D_265699)(NF* x, NF y) {
	(*x) = ((NF)((*x)) * (NF)(y));
}

static N_INLINE(Slice83964, HEX2EHEX2E_102273)(NI a, NI b) {
	Slice83964 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(void, HEX2FHEX3D_84502)(NF* x, NF y) {
	(*x) = ((NF)((*x)) / (NF)(y));
}

static N_INLINE(void, HEX2BHEX3D_100688)(NF* x, NF y) {
	(*x) = ((NF)((*x)) + (NF)(y));
}

static N_INLINE(void, HEX2AHEX3D_266000)(NI64* x, NI64 y) {
	(*x) = (NI64)((*x) * y);
}

N_NIMCALL(void, writeformat_265604)(NimStringDesc** o, NF x, Format188215* fmt_265614) {
	Format188215 fmt;
	NIM_BOOL positive;
	NIM_BOOL LOC14;
	NU8 LOC16;
	NI len;
	NI prec;
	NF y;
	NI exp;
	TY265681 numstr;
	TY265681 frstr;
	NI numlen;
	NI frbeg;
	NI frlen;
	NU8 LOC32;
	TY188433 alg;
	NI LOC102;
	memset((void*)(&fmt), 0, sizeof(fmt));
	genericAssign((void*)(&fmt), (void*)fmt_265614, (&NTI188215));
	{
		if (!(fmt.Field0 == ((NU8) 0))) goto LA3;
		fmt.Field0 = ((NU8) 9);
		{
			if (!(fmt.Field1 < ((NI) 0))) goto LA7;
			fmt.Field1 = ((NI) 6);
		}
		LA7: ;
	}
	LA3: ;
	{
		Formaterror188205* e_265637;
		NimStringDesc* LOC13;
		if (!!(((1920 &(1<<((fmt.Field0)&15)))!=0))) goto LA11;
		e_265637 = 0;
		e_265637 = (Formaterror188205*) newObj((&NTI261027), sizeof(Formaterror188205));
		(*e_265637).Sup.Sup.m_type = (&NTI188205);
		LOC13 = 0;
		LOC13 = (*e_265637).Sup.message; (*e_265637).Sup.message = copyStringRC1(((NimStringDesc*) &TMP452));
		if (LOC13) nimGCunrefNoCycle(LOC13);
		raiseException((Exception*)e_265637, "FormatError");
	}
	LA11: ;
	LOC14 = 0;
	LOC14 = (0.0 <= x);
	if (!(LOC14)) goto LA15;
	LOC16 = 0;
	LOC16 = classify_142426(x);
	LOC14 = !((LOC16 == ((NU8) 3)));
	LA15: ;
	positive = LOC14;
	len = ((NI) 0);
	{
		NIM_BOOL LOC19;
		LOC19 = 0;
		LOC19 = !((fmt.Field5 == ((NU8) 0)));
		if (LOC19) goto LA20;
		LOC19 = !(positive);
		LA20: ;
		if (!LOC19) goto LA21;
		len += ((NI) 1);
	}
	LA21: ;
	{
		if (!(fmt.Field1 < ((NI) 0))) goto LA25;
		prec = ((NI) 6);
	}
	goto LA23;
	LA25: ;
	{
		prec = fmt.Field1;
	}
	LA23: ;
	y = (x > 0? (x) : -(x));
	exp = ((NI) 0);
	memset((void*)numstr, 0, sizeof(numstr));
	memset((void*)frstr, 0, sizeof(frstr));
	numlen = ((NI) 0);
	frbeg = ((NI) 0);
	frlen = ((NI) 0);
	{
		if (!(fmt.Field0 == ((NU8) 10))) goto LA30;
		HEX2AHEX3D_265699((&y), 1.0000000000000000e+02);
	}
	LA30: ;
	LOC32 = 0;
	LOC32 = classify_142426(x);
	switch (LOC32) {
	case ((NU8) 4):
	{
		Slice83964 LOC34;
		LOC34 = HEX2EHEX2E_102273(((NI) 0), ((NI) 2));
		HEX5BHEX5DHEX3D_265725(numstr, LOC34, TMP455, 3);
		numlen = ((NI) 3);
	}
	break;
	case ((NU8) 5):
	case ((NU8) 6):
	{
		Slice83964 LOC36;
		LOC36 = HEX2EHEX2E_102273(((NI) 0), ((NI) 2));
		HEX5BHEX5DHEX3D_265725(numstr, LOC36, TMP456, 3);
		numlen = ((NI) 3);
	}
	break;
	case ((NU8) 2):
	case ((NU8) 3):
	{
		numstr[(((NI) 0))- 0] = 48;
		numlen = ((NI) 1);
	}
	break;
	default:
	{
		NI64 mult;
		NI64 num;
		NI64 fr;
		{
			NF LOC43;
			NF LOC44;
			if (!!(((1152 &(1<<((fmt.Field0)&15)))!=0))) goto LA41;
			LOC43 = 0;
			LOC43 = log10(y);
			LOC44 = 0;
			LOC44 = floor(LOC43);
			exp = ((NI) (LOC44));
			{
				if (!(fmt.Field0 == ((NU8) 9))) goto LA47;
				{
					if (!(prec == ((NI) 0))) goto LA51;
					prec = ((NI) 1);
				}
				LA51: ;
				{
					NIM_BOOL LOC55;
					LOC55 = 0;
					LOC55 = (((NI) -4) <= exp);
					if (!(LOC55)) goto LA56;
					LOC55 = (exp < prec);
					LA56: ;
					if (!LOC55) goto LA57;
					prec = (NI)((NI)(prec - ((NI) 1)) - exp);
					exp = ((NI) 0);
				}
				goto LA53;
				LA57: ;
				{
					prec = (NI)(prec - ((NI) 1));
					len += ((NI) 4);
				}
				LA53: ;
			}
			goto LA45;
			LA47: ;
			{
				len += ((NI) 4);
			}
			LA45: ;
			{
				NF LOC65;
				if (!(((NI) 0) < exp)) goto LA63;
				LOC65 = 0;
				LOC65 = pow(1.0000000000000000e+01, ((NF) ((exp > 0? (exp) : -(exp)))));
				HEX2FHEX3D_84502((&y), LOC65);
			}
			goto LA61;
			LA63: ;
			{
				NF LOC69;
				if (!(exp < ((NI) 0))) goto LA67;
				LOC69 = 0;
				LOC69 = pow(1.0000000000000000e+01, ((NF) ((exp > 0? (exp) : -(exp)))));
				HEX2AHEX3D_265699((&y), LOC69);
			}
			goto LA61;
			LA67: ;
			LA61: ;
		}
		goto LA39;
		LA41: ;
		{
			if (!(fmt.Field0 == ((NU8) 10))) goto LA71;
			len += ((NI) 1);
		}
		goto LA39;
		LA71: ;
		LA39: ;
		{
			if (!(prec < ((NI) 8))) goto LA75;
			HEX2BHEX3D_100688((&y), roundnums_188264[(prec)- 0]);
		}
		LA75: ;
		mult = IL64(1);
		{
			NI i_265998;
			NI res_266431;
			i_265998 = 0;
			res_266431 = ((NI) 1);
			{
				while (1) {
					if (!(res_266431 <= prec)) goto LA79;
					i_265998 = res_266431;
					HEX2AHEX3D_266000((&mult), ((NI) 10));
					res_266431 += ((NI) 1);
				} LA79: ;
			}
		}
		num = ((NI64) (y));
		fr = ((NI64) (((NF)(((NF)(y) - (NF)(((NF) (num))))) * (NF)(((NF) (mult))))));
		{
			while (1) {
				if (!!((num == IL64(0)))) goto LA81;
				numstr[(numlen)- 0] = ((NIM_CHAR) ((NI64)(((NI) 48) + ((NI) ((NI64)(num % IL64(10)))))));
				numlen += ((NI) 1);
				num = (NI64)(num / IL64(10));
			} LA81: ;
		}
		{
			if (!(numlen == ((NI) 0))) goto LA84;
			numstr[(((NI) 0))- 0] = 48;
			numlen += ((NI) 1);
		}
		LA84: ;
		{
			while (1) {
				if (!!((fr == IL64(0)))) goto LA87;
				frstr[(frlen)- 0] = ((NIM_CHAR) ((NI64)(((NI) 48) + ((NI) ((NI64)(fr % IL64(10)))))));
				frlen += ((NI) 1);
				fr = (NI64)(fr / IL64(10));
			} LA87: ;
		}
		{
			while (1) {
				if (!(frlen < prec)) goto LA89;
				frstr[(frlen)- 0] = 48;
				frlen += ((NI) 1);
			} LA89: ;
		}
		{
			if (!(fmt.Field0 == ((NU8) 9))) goto LA92;
			{
				while (1) {
					NIM_BOOL LOC96;
					LOC96 = 0;
					LOC96 = (frbeg < frlen);
					if (!(LOC96)) goto LA97;
					LOC96 = ((NU8)(frstr[(frbeg)- 0]) == (NU8)(48));
					LA97: ;
					if (!LOC96) goto LA95;
					frbeg += ((NI) 1);
				} LA95: ;
			}
		}
		LA92: ;
	}
	break;
	}
	len += numlen;
	{
		if (!(frbeg < frlen)) goto LA100;
		len += (NI)((NI)(((NI) 1) + frlen) - frbeg);
	}
	LA100: ;
	alg = getalign_188428((&fmt), ((NU8) 2), len);
	LOC102 = 0;
	{
		if (!positive) goto LA105;
		LOC102 = ((NI) 1);
	}
	goto LA103;
	LA105: ;
	{
		LOC102 = ((NI) -1);
	}
	LA103: ;
	writefill_261204(o, (&fmt), alg.Field0, LOC102);
	{
		NI i_266227;
		NI HEX3Atmp_266448;
		NI res_266451;
		i_266227 = 0;
		HEX3Atmp_266448 = 0;
		HEX3Atmp_266448 = (NI)(numlen - ((NI) 1));
		res_266451 = HEX3Atmp_266448;
		{
			while (1) {
				if (!(((NI) 0) <= res_266451)) goto LA110;
				i_266227 = res_266451;
				write_188278(o, numstr[(i_266227)- 0]);
				res_266451 -= ((NI) 1);
			} LA110: ;
		}
	}
	{
		if (!(frbeg < frlen)) goto LA113;
		write_188278(o, 46);
		{
			NI i_266239;
			NI HEX3Atmp_266456;
			NI res_266459;
			i_266239 = 0;
			HEX3Atmp_266456 = 0;
			HEX3Atmp_266456 = (NI)(frlen - ((NI) 1));
			res_266459 = HEX3Atmp_266456;
			{
				while (1) {
					if (!(frbeg <= res_266459)) goto LA117;
					i_266239 = res_266459;
					write_188278(o, frstr[(i_266239)- 0]);
					res_266459 -= ((NI) 1);
				} LA117: ;
			}
		}
	}
	LA113: ;
	{
		NIM_BOOL LOC120;
		NIM_BOOL LOC122;
		NIM_CHAR LOC126;
		LOC120 = 0;
		LOC120 = (fmt.Field0 == ((NU8) 8));
		if (LOC120) goto LA121;
		LOC122 = 0;
		LOC122 = (fmt.Field0 == ((NU8) 9));
		if (!(LOC122)) goto LA123;
		LOC122 = !((exp == ((NI) 0)));
		LA123: ;
		LOC120 = LOC122;
		LA121: ;
		if (!LOC120) goto LA124;
		LOC126 = 0;
		{
			if (!fmt.Field7) goto LA129;
			LOC126 = 69;
		}
		goto LA127;
		LA129: ;
		{
			LOC126 = 101;
		}
		LA127: ;
		write_188278(o, LOC126);
		{
			if (!(((NI) 0) <= exp)) goto LA134;
			write_188278(o, 43);
		}
		goto LA132;
		LA134: ;
		{
			write_188278(o, 45);
			exp = ((NI64)-(exp));
		}
		LA132: ;
		{
			if (!(exp < ((NI) 10))) goto LA139;
			write_188278(o, 48);
			write_188278(o, ((NIM_CHAR) ((NI)(((NI) 48) + exp))));
		}
		goto LA137;
		LA139: ;
		{
			NI i;
			i = ((NI) 0);
			{
				while (1) {
					if (!(((NI) 0) < exp)) goto LA143;
					numstr[(i)- 0] = ((NIM_CHAR) ((NI)(((NI) 48) + ((NI) ((NI)(exp % ((NI) 10)))))));
					i += ((NI) 1);
					exp = (NI)(exp / ((NI) 10));
				} LA143: ;
			}
			{
				while (1) {
					if (!(((NI) 0) < i)) goto LA145;
					i -= ((NI) 1);
					write_188278(o, numstr[(i)- 0]);
				} LA145: ;
			}
		}
		LA137: ;
	}
	LA124: ;
	{
		if (!(fmt.Field0 == ((NU8) 10))) goto LA148;
		write_188278(o, 37);
	}
	LA148: ;
	writefill_261204(o, (&fmt), alg.Field1, ((NI) 0));
}

static N_INLINE(NI, skipuntil_90514)(NimStringDesc* s, NIM_CHAR until, NI start) {
	NI result;
	result = 0;
	{
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = 0;
			LOC3 = !(((NU8)(s->data[(NI)(result + start)]) == (NU8)(until)));
			if (!(LOC3)) goto LA4;
			LOC3 = !(((NU8)(s->data[(NI)(result + start)]) == (NU8)(0)));
			LA4: ;
			if (!LOC3) goto LA2;
			result += ((NI) 1);
		} LA2: ;
	}
	return result;
}

N_NIMCALL(void, writeformat_334805)(NimStringDesc** o, NimStringDesc** ary, NI aryLen0, Format188215* fmt) {
	NimStringDesc* sep;
	Format188215 nxtfmt;
{	{
		if (!(aryLen0 == ((NI) 0))) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	sep = 0;
	memset((void*)(&nxtfmt), 0, sizeof(nxtfmt));
	genericAssign((void*)(&nxtfmt), (void*)fmt, (&NTI188215));
	{
		if (!((*fmt).Field9 == NIM_NIL)) goto LA7;
		sep = copyString(((NimStringDesc*) &TMP542));
	}
	goto LA5;
	LA7: ;
	{
		if (!(((*fmt).Field9 ? (*fmt).Field9->Sup.len : 0) == ((NI) 0))) goto LA10;
		sep = copyString(((NimStringDesc*) &TMP543));
	}
	goto LA5;
	LA10: ;
	{
		NIM_CHAR sepch;
		NI nxt;
		NI LOC13;
		sepch = (*fmt).Field9->data[((NI) 0)];
		LOC13 = 0;
		LOC13 = skipuntil_90514((*fmt).Field9, sepch, ((NI) 1));
		nxt = (NI)(((NI) 1) + LOC13);
		{
			if (!(((NI) 1) <= nxt)) goto LA16;
			nxtfmt.Field9 = copyStr((*fmt).Field9, nxt);
			sep = copyStrLast((*fmt).Field9, ((NI) 1), (NI)(nxt - ((NI) 1)));
		}
		goto LA14;
		LA16: ;
		{
			nxtfmt.Field9 = copyString(((NimStringDesc*) &TMP543));
			sep = copyStr((*fmt).Field9, ((NI) 1));
		}
		LA14: ;
	}
	LA5: ;
	writeformat_261004(o, ary[((NI) 0)], (&nxtfmt));
	{
		NI i_336431;
		NI HEX3Atmp_338022;
		NI res_338025;
		i_336431 = 0;
		HEX3Atmp_338022 = 0;
		HEX3Atmp_338022 = (NI)(aryLen0 - ((NI) 1));
		res_338025 = ((NI) 1);
		{
			while (1) {
				if (!(res_338025 <= HEX3Atmp_338022)) goto LA21;
				i_336431 = res_338025;
				{
					NIM_CHAR c_336432;
					NI i_338019;
					NI L_338021;
					c_336432 = 0;
					i_338019 = ((NI) 0);
					L_338021 = (sep ? sep->Sup.len : 0);
					{
						while (1) {
							if (!(i_338019 < L_338021)) goto LA24;
							c_336432 = sep->data[i_338019];
							write_188278(o, c_336432);
							i_338019 += ((NI) 1);
						} LA24: ;
					}
				}
				writeformat_261004(o, ary[i_336431], (&nxtfmt));
				res_338025 += ((NI) 1);
			} LA21: ;
		}
	}
	}BeforeRet: ;
}

N_NIMCALL(void, writeformat_340405)(NimStringDesc** o, NF* ary, NI aryLen0, Format188215* fmt) {
	NimStringDesc* sep;
	Format188215 nxtfmt;
{	{
		if (!(aryLen0 == ((NI) 0))) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	sep = 0;
	memset((void*)(&nxtfmt), 0, sizeof(nxtfmt));
	genericAssign((void*)(&nxtfmt), (void*)fmt, (&NTI188215));
	{
		if (!((*fmt).Field9 == NIM_NIL)) goto LA7;
		sep = copyString(((NimStringDesc*) &TMP542));
	}
	goto LA5;
	LA7: ;
	{
		if (!(((*fmt).Field9 ? (*fmt).Field9->Sup.len : 0) == ((NI) 0))) goto LA10;
		sep = copyString(((NimStringDesc*) &TMP543));
	}
	goto LA5;
	LA10: ;
	{
		NIM_CHAR sepch;
		NI nxt;
		NI LOC13;
		sepch = (*fmt).Field9->data[((NI) 0)];
		LOC13 = 0;
		LOC13 = skipuntil_90514((*fmt).Field9, sepch, ((NI) 1));
		nxt = (NI)(((NI) 1) + LOC13);
		{
			if (!(((NI) 1) <= nxt)) goto LA16;
			nxtfmt.Field9 = copyStr((*fmt).Field9, nxt);
			sep = copyStrLast((*fmt).Field9, ((NI) 1), (NI)(nxt - ((NI) 1)));
		}
		goto LA14;
		LA16: ;
		{
			nxtfmt.Field9 = copyString(((NimStringDesc*) &TMP543));
			sep = copyStr((*fmt).Field9, ((NI) 1));
		}
		LA14: ;
	}
	LA5: ;
	writeformat_265604(o, ary[((NI) 0)], (&nxtfmt));
	{
		NI i_342032;
		NI HEX3Atmp_343623;
		NI res_343626;
		i_342032 = 0;
		HEX3Atmp_343623 = 0;
		HEX3Atmp_343623 = (NI)(aryLen0 - ((NI) 1));
		res_343626 = ((NI) 1);
		{
			while (1) {
				if (!(res_343626 <= HEX3Atmp_343623)) goto LA21;
				i_342032 = res_343626;
				{
					NIM_CHAR c_342033;
					NI i_343620;
					NI L_343622;
					c_342033 = 0;
					i_343620 = ((NI) 0);
					L_343622 = (sep ? sep->Sup.len : 0);
					{
						while (1) {
							if (!(i_343620 < L_343622)) goto LA24;
							c_342033 = sep->data[i_343620];
							write_188278(o, c_342033);
							i_343620 += ((NI) 1);
						} LA24: ;
					}
				}
				writeformat_265604(o, ary[i_342032], (&nxtfmt));
				res_343626 += ((NI) 1);
			} LA21: ;
		}
	}
	}BeforeRet: ;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_strfmtDatInit)(void) {
static TNimNode* TMP442[10];
static TNimNode* TMP443[11];
NI TMP445;
static char* NIM_CONST TMP444[11] = {
"ftDefault", 
"ftStr", 
"ftChar", 
"ftDec", 
"ftBin", 
"ftOct", 
"ftHex", 
"ftFix", 
"ftSci", 
"ftGen", 
"ftPercent"};
static TNimNode* TMP446[5];
NI TMP448;
static char* NIM_CONST TMP447[5] = {
"faDefault", 
"faLeft", 
"faRight", 
"faCenter", 
"faPadding"};
static TNimNode* TMP449[3];
NI TMP451;
static char* NIM_CONST TMP450[3] = {
"fsMinus", 
"fsPlus", 
"fsSpace"};
static TNimNode TMP35[34];
NTI188205.size = sizeof(Formaterror188205);
NTI188205.kind = 17;
NTI188205.base = (&NTI3427);
TMP35[0].len = 0; TMP35[0].kind = 2;
NTI188205.node = &TMP35[0];
NTI261027.size = sizeof(Formaterror188205*);
NTI261027.kind = 22;
NTI261027.base = (&NTI188205);
NTI261027.marker = TMP244;
NTI188215.size = sizeof(Format188215);
NTI188215.kind = 18;
NTI188215.base = 0;
NTI188215.flags = 2;
TMP442[0] = &TMP35[2];
NTI188213.size = sizeof(NU8);
NTI188213.kind = 14;
NTI188213.base = 0;
NTI188213.flags = 3;
for (TMP445 = 0; TMP445 < 11; TMP445++) {
TMP35[TMP445+3].kind = 1;
TMP35[TMP445+3].offset = TMP445;
TMP35[TMP445+3].name = TMP444[TMP445];
TMP443[TMP445] = &TMP35[TMP445+3];
}
TMP35[14].len = 11; TMP35[14].kind = 2; TMP35[14].sons = &TMP443[0];
NTI188213.node = &TMP35[14];
TMP35[2].kind = 1;
TMP35[2].offset = offsetof(Format188215, Field0);
TMP35[2].typ = (&NTI188213);
TMP35[2].name = "Field0";
TMP442[1] = &TMP35[15];
TMP35[15].kind = 1;
TMP35[15].offset = offsetof(Format188215, Field1);
TMP35[15].typ = (&NTI108);
TMP35[15].name = "Field1";
TMP442[2] = &TMP35[16];
TMP35[16].kind = 1;
TMP35[16].offset = offsetof(Format188215, Field2);
TMP35[16].typ = (&NTI108);
TMP35[16].name = "Field2";
TMP442[3] = &TMP35[17];
TMP35[17].kind = 1;
TMP35[17].offset = offsetof(Format188215, Field3);
TMP35[17].typ = (&NTI149);
TMP35[17].name = "Field3";
TMP442[4] = &TMP35[18];
NTI188209.size = sizeof(NU8);
NTI188209.kind = 14;
NTI188209.base = 0;
NTI188209.flags = 3;
for (TMP448 = 0; TMP448 < 5; TMP448++) {
TMP35[TMP448+19].kind = 1;
TMP35[TMP448+19].offset = TMP448;
TMP35[TMP448+19].name = TMP447[TMP448];
TMP446[TMP448] = &TMP35[TMP448+19];
}
TMP35[24].len = 5; TMP35[24].kind = 2; TMP35[24].sons = &TMP446[0];
NTI188209.node = &TMP35[24];
TMP35[18].kind = 1;
TMP35[18].offset = offsetof(Format188215, Field4);
TMP35[18].typ = (&NTI188209);
TMP35[18].name = "Field4";
TMP442[5] = &TMP35[25];
NTI188211.size = sizeof(NU8);
NTI188211.kind = 14;
NTI188211.base = 0;
NTI188211.flags = 3;
for (TMP451 = 0; TMP451 < 3; TMP451++) {
TMP35[TMP451+26].kind = 1;
TMP35[TMP451+26].offset = TMP451;
TMP35[TMP451+26].name = TMP450[TMP451];
TMP449[TMP451] = &TMP35[TMP451+26];
}
TMP35[29].len = 3; TMP35[29].kind = 2; TMP35[29].sons = &TMP449[0];
NTI188211.node = &TMP35[29];
TMP35[25].kind = 1;
TMP35[25].offset = offsetof(Format188215, Field5);
TMP35[25].typ = (&NTI188211);
TMP35[25].name = "Field5";
TMP442[6] = &TMP35[30];
TMP35[30].kind = 1;
TMP35[30].offset = offsetof(Format188215, Field6);
TMP35[30].typ = (&NTI138);
TMP35[30].name = "Field6";
TMP442[7] = &TMP35[31];
TMP35[31].kind = 1;
TMP35[31].offset = offsetof(Format188215, Field7);
TMP35[31].typ = (&NTI138);
TMP35[31].name = "Field7";
TMP442[8] = &TMP35[32];
TMP35[32].kind = 1;
TMP35[32].offset = offsetof(Format188215, Field8);
TMP35[32].typ = (&NTI138);
TMP35[32].name = "Field8";
TMP442[9] = &TMP35[33];
TMP35[33].kind = 1;
TMP35[33].offset = offsetof(Format188215, Field9);
TMP35[33].typ = (&NTI149);
TMP35[33].name = "Field9";
TMP35[1].len = 10; TMP35[1].kind = 2; TMP35[1].sons = &TMP442[0];
NTI188215.node = &TMP35[1];
}

